#![no_main]

//! The verifier's core soundness property: a single structured mutation of a
//! genuine, accepted muldiv proof must be rejected.
//!
//! The honest bundle (preprocessing, public I/O, proof, trusted-advice
//! commitment) is decoded once from a checked-in fixture generated by
//! `tests/generate_fuzz_fixture.rs`. Each iteration clones the proof, applies
//! one fuzzer-chosen mutation, and asserts `verify` returns `Err`. Mutations
//! span cheap structural checks (trace length, RAM size, advice presence) and
//! commitment corruption that must be caught by the opening/pairing checks.

use std::sync::OnceLock;

use common::jolt_device::JoltDevice;
use jolt_crypto::{Bn254G1, Pedersen};
use jolt_dory::{DoryCommitment, DoryScheme};
use jolt_field::Fr;
use jolt_transcript::LegacyBlake2bTranscript;
use jolt_verifier::{verify, JoltProof, JoltVerifierPreprocessing};
use libfuzzer_sys::fuzz_target;

type Preprocessing = JoltVerifierPreprocessing<DoryScheme, Pedersen<Bn254G1>>;
type Proof = JoltProof<DoryScheme, Pedersen<Bn254G1>>;
type Bundle = (Preprocessing, JoltDevice, Proof, Option<DoryCommitment>);

static FIXTURE: &[u8] = include_bytes!("../fixtures/muldiv-bundle.bin");

fn bundle() -> &'static Bundle {
    static BUNDLE: OnceLock<Bundle> = OnceLock::new();
    BUNDLE.get_or_init(|| {
        let (bundle, consumed): (Bundle, usize) =
            bincode::serde::decode_from_slice(FIXTURE, bincode::config::standard())
                .expect("fixture decodes");
        assert_eq!(consumed, FIXTURE.len(), "fixture has trailing bytes");
        // The honest proof must verify, or every "rejection" below is vacuous.
        let (preprocessing, public_io, proof, advice) = &bundle;
        verify::<Fr, DoryScheme, Pedersen<Bn254G1>, LegacyBlake2bTranscript>(
            preprocessing,
            public_io,
            proof,
            advice.as_ref(),
        )
        .expect("honest fixture proof must verify before tampering");
        bundle
    })
}

/// Replaces a commitment with the default (identity) one. Returns false when
/// the target was already the default, so the mutation is a real change.
fn clobber(commitment: &mut DoryCommitment) -> bool {
    let default = DoryCommitment::default();
    if *commitment == default {
        return false;
    }
    *commitment = default;
    true
}

fuzz_target!(|data: &[u8]| {
    if data.len() < 2 {
        return;
    }
    let (preprocessing, public_io, honest_proof, advice) = bundle();
    let mut proof = honest_proof.clone();
    let selector = data[0];
    let index = data[1] as usize;

    let changed = match selector % 8 {
        0 => {
            // Non-power-of-two trace length (structural check).
            proof.trace_length = proof.trace_length.saturating_add(1);
            !proof.trace_length.is_power_of_two()
        }
        1 => {
            // Zero trace length.
            if proof.trace_length == 0 {
                return;
            }
            proof.trace_length = 0;
            true
        }
        2 => {
            proof.ram_K = proof.ram_K.wrapping_add(1);
            true
        }
        3 => clobber(&mut proof.commitments.rd_inc),
        4 => clobber(&mut proof.commitments.ram_inc),
        5 => {
            if proof.commitments.instruction_ra.is_empty() {
                return;
            }
            let i = index % proof.commitments.instruction_ra.len();
            clobber(&mut proof.commitments.instruction_ra[i])
        }
        6 => {
            if proof.commitments.bytecode_ra.is_empty() {
                return;
            }
            let i = index % proof.commitments.bytecode_ra.len();
            clobber(&mut proof.commitments.bytecode_ra[i])
        }
        _ => {
            // Toggle the untrusted-advice commitment presence.
            proof.untrusted_advice_commitment = match proof.untrusted_advice_commitment.take() {
                Some(_) => None,
                None => Some(DoryCommitment::default()),
            };
            true
        }
    };
    if !changed {
        return;
    }

    let result = verify::<Fr, DoryScheme, Pedersen<Bn254G1>, LegacyBlake2bTranscript>(
        preprocessing,
        public_io,
        &proof,
        advice.as_ref(),
    );
    assert!(
        result.is_err(),
        "verifier accepted a tampered proof (mutation class {})",
        selector % 8
    );
});
