#![no_main]

//! Argument-string mutation of accepted BlindFold proofs.
//!
//! The fixtures are generated by the real ZK prover and cover a plain program,
//! a committed program, and trusted plus untrusted advice. Each input applies
//! exactly one mutation to the argument string (committed sumcheck rounds,
//! the Dory opening, and the BlindFold proof all live there) or to the public
//! statement; see `jolt_verifier_fuzz::tamper_must_reject` for the input
//! layout. Every mutation that changes the verifier's input must be rejected
//! by the compiled ZK verifier.

use std::sync::OnceLock;

use jolt_verifier_fuzz::{tamper_must_reject, Bundle};
use libfuzzer_sys::fuzz_target;

static FIXTURES: [&[u8]; 3] = [
    include_bytes!("../fixtures/zk-muldiv-bundle.bin"),
    include_bytes!("../fixtures/zk-committed-muldiv-bundle.bin"),
    include_bytes!("../fixtures/zk-advice-consumer-bundle.bin"),
];

fn bundles() -> &'static [Bundle] {
    static BUNDLES: OnceLock<Vec<Bundle>> = OnceLock::new();
    BUNDLES.get_or_init(|| {
        FIXTURES
            .iter()
            .map(|bytes| Bundle::decode_verified(bytes))
            .collect()
    })
}

fuzz_target!(|data: &[u8]| {
    tamper_must_reject(bundles(), data, "ZK");
});
