#![no_main]

//! Structured mutation of accepted BlindFold proofs.
//!
//! The fixture is generated by the real ZK prover. Every non-skipped input
//! changes one committed-sumcheck, final-opening, or BlindFold component and
//! requires the compiled ZK verifier to reject it.

use std::sync::OnceLock;

use common::jolt_device::JoltDevice;
use jolt_crypto::{Bn254G1, Pedersen};
use jolt_dory::{DoryCommitment, DoryScheme};
use jolt_field::{Fr, FromPrimitiveInt};
use jolt_poly::CompressedPoly;
use jolt_sumcheck::{CompressedSumcheckProof, SumcheckProof};
use jolt_transcript::LegacyBlake2bTranscript;
use jolt_verifier::{
    verify, JoltProof, JoltProofClaims, JoltVerifierPreprocessing, ZkConfig,
};
use libfuzzer_sys::fuzz_target;

type Preprocessing = JoltVerifierPreprocessing<DoryScheme, Pedersen<Bn254G1>>;
type Proof = JoltProof<DoryScheme, Pedersen<Bn254G1>>;
type Bundle = (Preprocessing, JoltDevice, Proof, Option<DoryCommitment>);
type StageProof = SumcheckProof<Fr, Bn254G1>;

static FIXTURES: [&[u8]; 2] = [
    include_bytes!("../fixtures/zk-muldiv-bundle.bin"),
    include_bytes!("../fixtures/zk-committed-muldiv-bundle.bin"),
];

fn bundles() -> &'static [Bundle] {
    static BUNDLES: OnceLock<Vec<Bundle>> = OnceLock::new();
    BUNDLES.get_or_init(|| {
        FIXTURES
            .iter()
            .map(|bytes| {
                let (bundle, consumed): (Bundle, usize) =
                    bincode::serde::decode_from_slice(bytes, bincode::config::standard())
                        .expect("fixture decodes");
                assert_eq!(consumed, bytes.len(), "fixture has trailing bytes");
                let (preprocessing, public_io, proof, _) = &bundle;
                verify::<Fr, DoryScheme, Pedersen<Bn254G1>, LegacyBlake2bTranscript>(
                    preprocessing,
                    public_io,
                    proof,
                    None,
                )
                .expect("honest ZK fixture proof must verify before tampering");
                bundle
            })
            .collect()
    })
}

fn stage_proof(proof: &mut Proof, index: usize) -> &mut StageProof {
    match index % 10 {
        0 => &mut proof.stages.stage1_uni_skip_first_round_proof,
        1 => &mut proof.stages.stage1_sumcheck_proof,
        2 => &mut proof.stages.stage2_uni_skip_first_round_proof,
        3 => &mut proof.stages.stage2_sumcheck_proof,
        4 => &mut proof.stages.stage3_sumcheck_proof,
        5 => &mut proof.stages.stage4_sumcheck_proof,
        6 => &mut proof.stages.stage5_sumcheck_proof,
        7 => &mut proof.stages.stage6a_sumcheck_proof,
        8 => &mut proof.stages.stage6b_sumcheck_proof,
        _ => &mut proof.stages.stage7_sumcheck_proof,
    }
}

fn mutate_committed_sumcheck(proof: &mut StageProof, operation: u8, index: usize) -> bool {
    let SumcheckProof::Committed(committed) = proof else {
        return false;
    };
    match operation % 5 {
        0 => committed.rounds.pop().is_some(),
        1 => {
            let len = committed.rounds.len();
            if len == 0 {
                return false;
            }
            let round = &mut committed.rounds[index % len];
            round.degree = round.degree.saturating_add(1024);
            true
        }
        2 => {
            let len = committed.rounds.len();
            if len == 0 {
                return false;
            }
            let round = &mut committed.rounds[index % len];
            let before = round.commitment;
            round.commitment = Bn254G1::default();
            round.commitment != before
        }
        3 => committed.output_claims.commitments.pop().is_some(),
        _ => {
            let len = committed.output_claims.commitments.len();
            if len == 0 {
                return false;
            }
            let commitment = &mut committed.output_claims.commitments[index % len];
            let before = *commitment;
            *commitment = Bn254G1::default();
            *commitment != before
        }
    }
}

fn mutate_compressed(proof: &mut CompressedSumcheckProof<Fr>, operation: u8, index: usize) -> bool {
    match operation % 2 {
        0 => proof.round_polynomials.pop().is_some(),
        _ => {
            if proof.round_polynomials.is_empty() {
                return false;
            }
            let round = index % proof.round_polynomials.len();
            let replacement = CompressedPoly::new(vec![Fr::from_u64(index as u64 + 31)]);
            if proof.round_polynomials[round] == replacement {
                return false;
            }
            proof.round_polynomials[round] = replacement;
            true
        }
    }
}

fuzz_target!(|data: &[u8]| {
    if data.len() < 4 {
        return;
    }
    let fixture = &bundles()[data[0] as usize % bundles().len()];
    let mut preprocessing = fixture.0.clone();
    let mut public_io = fixture.1.clone();
    let mut proof = fixture.2.clone();
    let mutation = data[1] % 14;
    let index = data[2] as usize;
    let operation = data[3];

    let changed = match mutation {
        0 => {
            proof.protocol.zk = ZkConfig::Transparent;
            true
        }
        1 => {
            proof.trace_length = 3;
            true
        }
        2 => {
            proof.ram_K = 3;
            true
        }
        3 => {
            preprocessing.vc_setup = None;
            true
        }
        4 => mutate_committed_sumcheck(stage_proof(&mut proof, index), operation, index),
        5 => {
            proof.joint_opening_proof.0.y_com = None;
            true
        }
        6 => {
            let JoltProofClaims::Zk { blindfold_proof } = &mut proof.claims else {
                return;
            };
            blindfold_proof.random_u += Fr::from_u64(1);
            true
        }
        7 => {
            let JoltProofClaims::Zk { blindfold_proof } = &mut proof.claims else {
                return;
            };
            mutate_compressed(&mut blindfold_proof.outer_sumcheck, operation, index)
        }
        8 => {
            let JoltProofClaims::Zk { blindfold_proof } = &mut proof.claims else {
                return;
            };
            mutate_compressed(&mut blindfold_proof.inner_sumcheck, operation, index)
        }
        9 => {
            let JoltProofClaims::Zk { blindfold_proof } = &mut proof.claims else {
                return;
            };
            blindfold_proof.random_round_commitments.pop().is_some()
        }
        10 => {
            let JoltProofClaims::Zk { blindfold_proof } = &mut proof.claims else {
                return;
            };
            blindfold_proof
                .random_output_claim_row_commitments
                .pop()
                .is_some()
        }
        11 => {
            let JoltProofClaims::Zk { blindfold_proof } = &mut proof.claims else {
                return;
            };
            let Some(value) = blindfold_proof.folded_eval_outputs.first_mut() else {
                return;
            };
            *value += Fr::from_u64(1);
            true
        }
        12 => {
            if public_io.inputs.is_empty() {
                return;
            }
            let position = index % public_io.inputs.len();
            public_io.inputs[position] ^= operation.max(1);
            true
        }
        _ => {
            let before = proof.commitments.rd_inc.clone();
            proof.commitments.rd_inc = DoryCommitment::default();
            proof.commitments.rd_inc != before
        }
    };
    if !changed {
        return;
    }

    let result = verify::<Fr, DoryScheme, Pedersen<Bn254G1>, LegacyBlake2bTranscript>(
        &preprocessing,
        &public_io,
        &proof,
        None,
    );
    assert!(
        result.is_err(),
        "verifier accepted a tampered ZK proof (mutation class {mutation})"
    );
});
