name = "Extracted Jolt circuits"
defaultTargets = ["Jolt"]

[[lean_lib]]
name = "Jolt"

[[require]]
name = "zkLean"
git = "https://github.com/GaloisInc/zk-lean.git"
rev = "a061e494e4fc204e300ef72c1a4097826c4d192f"
subDir = "src"
