//! Canonical statement facts for the wrapper Spartan + HyperKZG protocol.

mod dimensions;
mod error;
mod protocol;

pub use dimensions::{
    PaddedR1csDimension, PublicInputSegment, SpartanRelationDimensions, WrapperPublicInputLayout,
    WrapperRelationDimensions,
};
pub use error::WrapperSpartanHyperKzgFactsError;
pub use protocol::{
    SpartanInnerBatchingCoefficients, SpartanInnerStatement, SpartanOuterEvaluationClaims,
    SpartanOuterReduction, SpartanWitnessOpeningStatement, WrapperSpartanHyperKzgStatementFacts,
    WRAPPER_PROTOCOL_ID_TRANSCRIPT_LABEL, WRAPPER_PUBLIC_INPUTS_TRANSCRIPT_LABEL,
    WRAPPER_PUBLIC_INPUTS_TRANSCRIPT_PREFIX, WRAPPER_PUBLIC_INPUT_LAYOUT_TRANSCRIPT_LABEL,
    WRAPPER_RELATION_DIMS_TRANSCRIPT_LABEL, WRAPPER_RELATION_MATRICES_TRANSCRIPT_LABEL,
    WRAPPER_RELATION_MATRIX_A_TRANSCRIPT_LABEL, WRAPPER_RELATION_MATRIX_B_TRANSCRIPT_LABEL,
    WRAPPER_RELATION_MATRIX_C_TRANSCRIPT_LABEL, WRAPPER_RELATION_MATRIX_ROW_TRANSCRIPT_LABEL,
    WRAPPER_SPARTAN_DIMS_TRANSCRIPT_LABEL, WRAPPER_SPARTAN_HYPERKZG_PROTOCOL_ID,
    WRAPPER_SPARTAN_INNER_BATCHING_TRANSCRIPT_LABEL, WRAPPER_SPARTAN_INNER_SUMCHECK_DEGREE,
    WRAPPER_SPARTAN_INNER_SUMCHECK_TRANSCRIPT_LABEL, WRAPPER_SPARTAN_OUTER_SUMCHECK_DEGREE,
    WRAPPER_SPARTAN_OUTER_SUMCHECK_TRANSCRIPT_LABEL, WRAPPER_SPARTAN_TAU_TRANSCRIPT_LABEL,
    WRAPPER_STATEMENT_TRANSCRIPT_LABEL, WRAPPER_TRANSCRIPT_LABEL,
    WRAPPER_WITNESS_COMMITMENT_TRANSCRIPT_LABEL,
};
