[package]
name = "blake2-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [] }
jolt-inlines-blake2 = { package = "jolt-inlines-blake2", path = "../../../jolt-inlines/blake2" }
