//! Transpile Jolt verifier stages 1-7 (all sumchecks) to circuit code for various proving backends.
//!
//! # Overview
//!
//! This binary performs symbolic execution of the Jolt verifier to generate circuit code.
//! Instead of computing with actual field elements, we use `MleAst`, a symbolic type that
//! records all arithmetic operations as an AST (Abstract Syntax Tree). This AST is then
//! converted to target-specific code (e.g., Go for gnark).
//!
//! # Supported Targets
//!
//! - **gnark** (default): Go/Groth16 circuit generation
//! - **ast-bundle**: Output only the AstBundle JSON (no code generation)
//!
//! # Scope: Stages 1-7 (All Sumcheck Verification)
//!
//! This transpiler covers stages 1-7, which verify all sumcheck proofs:
//! - Stages 1-6: Standard sumcheck verifications
//! - Stage 7: HammingWeight and AdviceClaimReduction sumchecks
//!
//! Stage 8 (PCS/Dory verification) is NOT transpiled because pairing operations
//! are too expensive in-circuit.
//!
//! Supports non-ZK proofs and the Poseidon transcript only, with field-aligned
//! absorption — see the crate-level SCOPE section in `lib.rs`.
//!
//! # Pipeline
//!
//! 1. Load proof, io_device, and preprocessing from files (generated by jolt-sdk)
//! 2. Convert proof values to symbolic variables (`MleAst`) with `symbolize_proof`
//! 3. Run the verifier with symbolic types: this records all operations to the AST
//! 4. Collect equality assertions (the verifier's `assert_eq!` calls become circuit constraints)
//! 5. Build AstBundle (target-agnostic intermediate representation)
//! 6. Generate target-specific circuit code from the AST
//! 7. Output witness values (captured during symbolization)

use ark_serialize::CanonicalDeserialize;
use clap::{Parser, ValueEnum};
use std::collections::HashMap;
use std::path::PathBuf;

use common::jolt_device::JoltDevice;
use jolt_core::curve::Bn254Curve;
use jolt_core::poly::commitment::dory::{ArkGT, DoryCommitmentScheme};
use jolt_core::zkvm::verifier::JoltVerifierPreprocessing;
use jolt_core::zkvm::RV64IMACProof;
use transpiler::gnark_codegen;
use transpiler::pipeline::{bundle_needs_non_native, run_symbolic_pipeline};

// Output file names (bundle is target-agnostic)
const BUNDLE_FILENAME: &str = "stages_bundle.json";

/// Transpilation target backends.
#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub enum TranspilationTarget {
    /// Go/gnark circuit for Groth16 proving
    #[default]
    Gnark,
    /// Output only the AstBundle (no code generation)
    AstBundle,
}

/// Transpile Jolt proofs to circuit code for various proving backends.
///
/// Takes a Jolt proof, io_device, and preprocessing files as input,
/// and generates circuit code and witness data for the specified target.
#[derive(Parser)]
#[command(name = "transpiler")]
#[command(version, about)]
struct Args {
    /// Path to the proof file (serialized JoltProof)
    #[arg(long, default_value = "/tmp/fib_proof.bin")]
    proof: PathBuf,

    /// Path to the io_device file (inputs/outputs)
    #[arg(long, default_value = "/tmp/fib_io_device.bin")]
    io_device: PathBuf,

    /// Path to the preprocessing file
    #[arg(long, default_value = "/tmp/jolt_verifier_preprocessing.dat")]
    preprocessing: PathBuf,

    /// Transpilation target language/framework
    #[arg(long, short = 't', default_value = "gnark", value_enum)]
    target: TranspilationTarget,

    /// Path to trusted advice commitment file (optional, for programs using TrustedAdvice)
    #[arg(long)]
    trusted_advice: Option<PathBuf>,

    /// Output directory (defaults to target-specific directory, e.g., "go" for gnark)
    #[arg(long, short = 'o')]
    output_dir: Option<PathBuf>,

    /// Also generate cross-validation circuit with api.Println hooks (crossval/circuit.go)
    #[arg(long)]
    crossval: bool,
}

fn main() {
    let args = Args::parse();

    println!(
        "=== Transpiling Jolt Verifier Stages 1-7 to {:?} ===\n",
        args.target
    );

    // Step 1: Load input files
    // These files are generated by running a Jolt program with --save flag:
    //   cargo run -p fibonacci --features transcript-poseidon -- --save 50
    //
    // - proof: The JoltProof containing commitments, sumcheck polynomials, etc.
    // - io_device: Program inputs/outputs (needed for transcript initialization)
    // - preprocessing: Verifier setup data (bytecode commitments, memory layout)

    println!("Loading proof from: {:?}", args.proof);
    let proof_bytes = std::fs::read(&args.proof)
        .unwrap_or_else(|e| panic!("Failed to read proof file {:?}: {}", args.proof, e));
    let real_proof: RV64IMACProof = CanonicalDeserialize::deserialize_compressed(&proof_bytes[..])
        .expect("Failed to deserialize proof");
    println!("  trace_length: {}", real_proof.trace_length);
    println!("  narg: {} bytes", real_proof.narg.len());

    println!("\nLoading io_device from: {:?}", args.io_device);
    let io_device_bytes = std::fs::read(&args.io_device)
        .unwrap_or_else(|e| panic!("Failed to read io_device file {:?}: {}", args.io_device, e));
    let io_device: JoltDevice = CanonicalDeserialize::deserialize_compressed(&io_device_bytes[..])
        .expect("Failed to deserialize io_device");
    println!("  inputs: {} bytes", io_device.inputs.len());
    println!("  outputs: {} bytes", io_device.outputs.len());

    // Preprocessing uses DoryCommitmentScheme, the default PCS in jolt-sdk.
    // We only need the `shared` field (memory layout, bytecode info) for transpilation;
    // the commitment scheme generators are replaced with stubs for symbolic execution.
    println!("\nLoading preprocessing from: {:?}", args.preprocessing);
    let preprocessing_bytes = std::fs::read(&args.preprocessing).unwrap_or_else(|e| {
        panic!(
            "Failed to read preprocessing file {:?}: {}",
            args.preprocessing, e
        )
    });
    let real_preprocessing: JoltVerifierPreprocessing<
        ark_bn254::Fr,
        Bn254Curve,
        DoryCommitmentScheme,
    > = CanonicalDeserialize::deserialize_compressed(&preprocessing_bytes[..])
        .expect("Failed to deserialize preprocessing");
    println!(
        "  memory_layout: {:?}",
        real_preprocessing.shared.memory_layout
    );

    // Step 2: Load trusted advice commitment (optional), then run the pipeline
    // The commitment is serialized separately from the proof (pre-committed by
    // the host); the file holds Option<ArkGT>.
    let real_trusted_advice = if let Some(ref path) = args.trusted_advice {
        println!("\nLoading trusted advice commitment from: {path:?}");
        let advice_bytes = std::fs::read(path)
            .unwrap_or_else(|e| panic!("Failed to read trusted advice file {path:?}: {e}"));
        let real_commitment: Option<ArkGT> =
            CanonicalDeserialize::deserialize_compressed(&advice_bytes[..])
                .expect("Failed to deserialize trusted advice commitment");
        Some(real_commitment.expect("Trusted advice file contains None (no commitment)"))
    } else {
        None
    };

    // Steps 2b-5: symbolize structural parts, split + replay the NARG through the
    // symbolic verifier (stages 1-7), and build the AstBundle. Same path the
    // integration test (`tests/symbolic_pipeline.rs`) drives.
    println!("\n=== Running Symbolic Pipeline (Stages 1-7) ===");
    let pipeline_output = run_symbolic_pipeline(
        &real_proof,
        io_device,
        &real_preprocessing,
        real_trusted_advice,
    )
    .unwrap_or_else(|e| panic!("Symbolic pipeline failed: {e}"));
    let deployment_blockers = pipeline_output.deployment_blockers();
    let bundle = pipeline_output.bundle;
    let var_alloc = pipeline_output.var_alloc;
    println!("  NARG frames: {}", pipeline_output.num_frames);
    println!("  Assertions: {}", pipeline_output.num_assertions);
    println!("  Inputs: {}", bundle.inputs.len());
    println!("  Constraints: {}", bundle.constraints.len());
    println!(
        "  Canonicalize: {} nodes -> {} ({} duplicates merged, {} dead dropped)",
        pipeline_output.canon_stats.nodes_before,
        pipeline_output.canon_stats.nodes_after,
        pipeline_output.canon_stats.duplicates_merged,
        pipeline_output.canon_stats.dead_nodes_dropped,
    );

    // Loud, unmissable deploy guard. This binary produces a TEST artifact only; the
    // generated circuit is NOT a sound on-chain verifier while any blocker remains
    // (spec §7.12 no-partial-artifact rule) — the stage-8 (Dory PCS) blocker in
    // particular stands until stage 8 is transpiled.
    if !deployment_blockers.is_empty() {
        eprintln!("\n!!! NOT DEPLOYABLE — generated circuit is a TEST artifact, not a verifier:");
        for blocker in &deployment_blockers {
            eprintln!("  - {blocker}");
        }
        eprintln!();
    }

    // Non-native (Fq) arithmetic has no codegen yet — bail cleanly here rather than
    // warn and then panic deep inside codegen with no context. Stages 1-7 are
    // Fr-only, so this never fires on a well-formed proof. (code-review #9)
    if bundle_needs_non_native(&bundle) {
        eprintln!(
            "error: bundle contains non-native (Fq) field variables; Fq codegen is not \
             implemented. Stages 1-7 should be Fr-only — this indicates an unexpected proof."
        );
        std::process::exit(1);
    }

    // Step 6: Resolve output directory and write bundle
    let default_output_dir = match args.target {
        TranspilationTarget::Gnark => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("go"),
        TranspilationTarget::AstBundle => PathBuf::from("."),
    };
    let output_dir = args.output_dir.clone().unwrap_or(default_output_dir);
    std::fs::create_dir_all(&output_dir)
        .unwrap_or_else(|e| panic!("Failed to create output directory {output_dir:?}: {e}"));

    // Save bundle to JSON (common to all targets)
    let bundle_path = output_dir.join(BUNDLE_FILENAME);
    bundle
        .write_json(&bundle_path)
        .unwrap_or_else(|e| panic!("Failed to write bundle file {bundle_path:?}: {e}"));
    println!("  Bundle written to: {bundle_path:?}");

    // Step 7: Target-specific code generation
    match args.target {
        TranspilationTarget::Gnark => {
            // Generate gnark circuit
            // generate_circuit_from_bundle() traverses the AST and emits Go code:
            // - Each AST node (Add, Mul, Sub, etc.) becomes an api.Add/Mul/Sub call
            // - Common subexpressions are cached to avoid redundant computation
            // - The circuit struct contains all witness fields
            // - The Define() method contains all constraint logic
            println!("\n=== Generating Gnark Circuit ===");
            let circuit_code =
                gnark_codegen::generate_circuit_from_bundle(&bundle, "JoltStagesCircuit");

            let circuit_path = output_dir.join("stages_circuit.go");
            std::fs::write(&circuit_path, &circuit_code)
                .unwrap_or_else(|e| panic!("Failed to write circuit file {circuit_path:?}: {e}"));
            println!("  Circuit written to: {circuit_path:?}");
            println!("  Circuit size: {} bytes", circuit_code.len());

            if args.crossval {
                println!("\n=== Generating Crossval Circuit ===");
                let (crossval_code, _) = gnark_codegen::generate_circuit_from_bundle_with_stats(
                    &bundle,
                    "JoltStagesCircuit",
                    true,
                );
                let crossval_dir = output_dir.join("crossval");
                std::fs::create_dir_all(&crossval_dir).unwrap_or_else(|e| {
                    panic!("Failed to create crossval dir {crossval_dir:?}: {e}")
                });
                let crossval_path = crossval_dir.join("circuit.go");
                std::fs::write(&crossval_path, &crossval_code).unwrap_or_else(|e| {
                    panic!("Failed to write crossval circuit {crossval_path:?}: {e}")
                });
                println!("  Crossval circuit written to: {crossval_path:?}");
            }

            // Get witness values captured during symbolization.
            // VarAllocator records both symbolic variables AND concrete values in a single pass,
            // making mismatch bugs structurally impossible.
            println!("\n=== Generating Witness Data ===");
            let witness_values = var_alloc.witness_values();

            let mut witness_map: HashMap<String, String> = HashMap::new();
            // Track the original (pre-sanitization) name behind each key so a
            // collision can name both culprits. `sanitize_go_name` is many-to-one,
            // so two distinct descriptions can map to the same Go field name; a
            // silent overwrite would feed the circuit a wrong witness value.
            let mut origin: HashMap<String, String> = HashMap::new();
            for (idx, name, _target_field) in var_alloc.descriptions_with_fields() {
                let sanitized = gnark_codegen::sanitize_go_name(name);
                if let Some(value) = witness_values.get(&(*idx as usize)) {
                    if let Some(existing) = witness_map.get(&sanitized) {
                        if existing != value {
                            let prev = origin.get(&sanitized).map(String::as_str).unwrap_or("?");
                            panic!(
                                "witness key collision: sanitize_go_name mapped distinct \
                                 descriptions {prev:?} and {name:?} to the same Go field \
                                 {sanitized:?} with different values ({existing} != {value})"
                            );
                        }
                    }
                    origin.insert(sanitized.clone(), name.clone());
                    witness_map.insert(sanitized, value.clone());
                }
            }

            let witness_json =
                serde_json::to_string_pretty(&witness_map).expect("Failed to serialize witness");
            let witness_path = output_dir.join("stages_witness.json");
            std::fs::write(&witness_path, &witness_json)
                .unwrap_or_else(|e| panic!("Failed to write witness file {witness_path:?}: {e}"));
            println!("  Witness written to: {witness_path:?}");
            println!("  Witness variables: {}", witness_map.len());

            println!("\n=== SUCCESS ===");
            println!("Stages 1-7 transpiled to Gnark. Run 'go test' in {output_dir:?} to verify.",);
        }
        TranspilationTarget::AstBundle => {
            println!("\n=== SUCCESS ===");
            println!("AstBundle written to: {bundle_path:?}");
            println!("  Inputs: {}", bundle.inputs.len());
            println!("  Constraints: {}", bundle.constraints.len());
        }
    }
}
