//! Transpile Jolt verifier stages 1-7 (all sumchecks) to circuit code for various proving backends.
//!
//! # Overview
//!
//! This binary performs symbolic execution of the Jolt verifier to generate circuit code.
//! Instead of computing with actual field elements, we use `MleAst`, a symbolic type that
//! records all arithmetic operations as an AST (Abstract Syntax Tree). This AST is then
//! converted to target-specific code (e.g., Go for gnark).
//!
//! # Supported Targets
//!
//! - **gnark** (default): Go/Groth16 circuit generation
//! - **ast-bundle**: Output only the AstBundle JSON (no code generation)
//!
//! # Scope: Stages 1-7 (All Sumcheck Verification)
//!
//! This transpiler covers stages 1-7, which verify all sumcheck proofs:
//! - Stages 1-6: Standard sumcheck verifications
//! - Stage 7: HammingWeight claim reduction sumcheck
//!
//! Stage 8 (PCS/Hyrax verification) is NOT transpiled because:
//! - **Hyrax requires native curve operations**: MSM on Grumpkin must use native implementations.
//! - **Native implementation needed**: PCS verification must be implemented directly in the
//!   target framework using native curve operations.
//!
//! Note: Stage 7 does not include AdviceClaimReduction verifiers (they require state management
//! across stages 6-7). For proofs without advice, this is complete.
//!
//! # Pipeline
//!
//! 1. Load proof, io_device, and preprocessing from files (generated by jolt-sdk)
//! 2. Convert proof values to symbolic variables (`MleAst`) with `symbolize_proof`
//! 3. Run the verifier with symbolic types: this records all operations to the AST
//! 4. Collect equality assertions (the verifier's `assert_eq!` calls become circuit constraints)
//! 5. Build AstBundle (target-agnostic intermediate representation)
//! 6. Generate target-specific circuit code from the AST
//! 7. Output witness values (captured during symbolization)

use ark_serialize::CanonicalDeserialize;
use clap::{Parser, ValueEnum};
use std::collections::HashMap;
use std::path::PathBuf;

use common::jolt_device::JoltDevice;
use jolt_core::poly::commitment::dory::DoryCommitmentScheme;
use jolt_core::transcripts::Transcript;
use jolt_core::zkvm::transpilable_verifier::TranspilableVerifier;
use jolt_core::zkvm::verifier::JoltVerifierPreprocessing;
use jolt_core::zkvm::RV64IMACProof;
use transpiler::{
    gnark_codegen, symbolize_proof, AstCommitmentScheme, AstOpeningAccumulator,
    SelectedAstTranscript,
};
use zklean_extractor::mle_ast::{
    enable_constraint_mode, take_constraints as take_assertions, AstBundle, MleAst, TargetField,
    WitnessType,
};

// Output file names (bundle is target-agnostic)
const BUNDLE_FILENAME: &str = "stages_bundle.json";

/// Transpilation target backends.
#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub enum TranspilationTarget {
    /// Go/gnark circuit for Groth16 proving
    #[default]
    Gnark,
    /// Output only the AstBundle (no code generation)
    AstBundle,
}

/// Transpile Jolt proofs to circuit code for various proving backends.
///
/// Takes a Jolt proof, io_device, and preprocessing files as input,
/// and generates circuit code and witness data for the specified target.
#[derive(Parser)]
#[command(name = "transpiler")]
#[command(version, about)]
struct Args {
    /// Path to the proof file (serialized JoltProof)
    #[arg(long, default_value = "/tmp/fib_proof.bin")]
    proof: PathBuf,

    /// Path to the io_device file (inputs/outputs)
    #[arg(long, default_value = "/tmp/fib_io_device.bin")]
    io_device: PathBuf,

    /// Path to the preprocessing file
    #[arg(long, default_value = "/tmp/jolt_verifier_preprocessing.dat")]
    preprocessing: PathBuf,

    /// Transpilation target language/framework
    #[arg(long, short = 't', default_value = "gnark", value_enum)]
    target: TranspilationTarget,

    /// Output directory (defaults to target-specific directory, e.g., "go" for gnark)
    #[arg(long, short = 'o')]
    output_dir: Option<PathBuf>,
}

fn main() {
    let args = Args::parse();

    println!(
        "=== Transpiling Jolt Verifier Stages 1-7 to {:?} ===\n",
        args.target
    );

    // =========================================================================
    // Step 1: Load input files
    // =========================================================================
    // These files are generated by running a Jolt program with --save flag:
    //   cargo run -p fibonacci --features transcript-poseidon -- --save 50
    //
    // - proof: The JoltProof containing commitments, sumcheck polynomials, etc.
    // - io_device: Program inputs/outputs (needed for transcript initialization)
    // - preprocessing: Verifier setup data (bytecode commitments, memory layout)

    println!("Loading proof from: {:?}", args.proof);
    let proof_bytes = std::fs::read(&args.proof)
        .unwrap_or_else(|e| panic!("Failed to read proof file {:?}: {}", args.proof, e));
    let real_proof: RV64IMACProof = CanonicalDeserialize::deserialize_compressed(&proof_bytes[..])
        .expect("Failed to deserialize proof");
    println!("  trace_length: {}", real_proof.trace_length);
    println!("  commitments: {}", real_proof.commitments.len());

    println!("\nLoading io_device from: {:?}", args.io_device);
    let io_device_bytes = std::fs::read(&args.io_device)
        .unwrap_or_else(|e| panic!("Failed to read io_device file {:?}: {}", args.io_device, e));
    let io_device: JoltDevice = CanonicalDeserialize::deserialize_compressed(&io_device_bytes[..])
        .expect("Failed to deserialize io_device");
    println!("  inputs: {} bytes", io_device.inputs.len());
    println!("  outputs: {} bytes", io_device.outputs.len());

    // Preprocessing uses DoryCommitmentScheme, the default PCS in jolt-sdk.
    // We only need the `shared` field (memory layout, bytecode info) for transpilation;
    // the commitment scheme generators are replaced with stubs for symbolic execution.
    println!("\nLoading preprocessing from: {:?}", args.preprocessing);
    let preprocessing_bytes = std::fs::read(&args.preprocessing).unwrap_or_else(|e| {
        panic!(
            "Failed to read preprocessing file {:?}: {}",
            args.preprocessing, e
        )
    });
    let real_preprocessing: JoltVerifierPreprocessing<ark_bn254::Fr, DoryCommitmentScheme> =
        CanonicalDeserialize::deserialize_compressed(&preprocessing_bytes[..])
            .expect("Failed to deserialize preprocessing");
    println!(
        "  memory_layout: {:?}",
        real_preprocessing.shared.memory_layout
    );

    // Convert to symbolic preprocessing: replace Dory generators with AstVerifierSetup stub.
    // The `shared` field (memory layout, bytecode info) is reused as-is.
    // AstCommitmentScheme satisfies the CommitmentScheme trait but performs no cryptographic
    // operations. PCS verification is skipped in stages 1-6.
    let symbolic_preprocessing: JoltVerifierPreprocessing<MleAst, AstCommitmentScheme> =
        JoltVerifierPreprocessing {
            generators: transpiler::symbolic_traits::ast_commitment_scheme::AstVerifierSetup,
            shared: real_preprocessing.shared.clone(),
        };

    // =========================================================================
    // Step 2: Convert proof to symbolic representation
    // =========================================================================
    // symbolize_proof() converts each proof field (commitments, sumcheck polynomials,
    // opening proofs) into MleAst symbolic variables. Each variable gets a unique ID
    // and descriptive name (e.g., "Stage1_Sumcheck_R0_0" for round 0, coefficient 0).
    //
    // Returns:
    // - symbolic_proof: JoltProof<MleAst> with symbolic variables instead of Fr values
    // - accumulator: AstOpeningAccumulator to collect polynomial opening claims
    // - var_alloc: Tracks variable IDs and names for witness generation
    println!("\n=== Symbolizing Proof ===");
    let (symbolic_proof, accumulator, var_alloc) =
        symbolize_proof::<SelectedAstTranscript>(&real_proof);
    println!("  Total symbolic variables: {}", var_alloc.next_idx());

    // Create transcript for Fiat-Shamir challenges.
    // IMPORTANT: The proof must have been generated with the same transcript feature,
    // otherwise challenge values will mismatch and verification will fail.
    let transcript: SelectedAstTranscript = Transcript::new(b"Jolt");

    // =========================================================================
    // Step 3: Set up symbolic verifier
    // =========================================================================
    // TranspilableVerifier is the same as the normal Jolt verifier, but parameterized
    // with symbolic types (MleAst, AstCommitmentScheme, etc.) instead of concrete ones.
    // When verify() is called (Step 4), it executes the verification logic but records
    // all arithmetic operations to the AST instead of computing actual results.
    println!("\n=== Creating TranspilableVerifier ===");
    let verifier = TranspilableVerifier::<
        MleAst,
        AstCommitmentScheme,
        SelectedAstTranscript,
        AstOpeningAccumulator,
    >::new_with_accumulator(
        &symbolic_preprocessing,
        symbolic_proof,
        io_device,
        None, // trusted_advice_commitment (not used in stages 1-6)
        transcript,
        accumulator,
    );

    // =========================================================================
    // Step 4: Run symbolic verification
    // =========================================================================
    // Enable constraint mode so that equality comparisons (==) on MleAst values
    // register as constraints instead of returning bool. This captures the verifier's
    // assert_eq! calls as circuit constraints.
    enable_constraint_mode();

    // Execute verification stages 1-6. This performs symbolic execution:
    // - All field arithmetic (add, mul, sub, inv) builds up the AST
    // - Poseidon hashes for Fiat-Shamir challenges are computed symbolically
    // - Equality assertions are recorded as constraints
    //
    // Stages 1-7 cover all sumcheck verifications. Stage 8 (PCS/Hyrax verification)
    // is not transpiled, it requires native curve operations in Gnark.
    println!("\n=== Running Symbolic Verification (Stages 1-7) ===");
    match verifier.verify() {
        Ok(()) => println!("  Verification completed successfully"),
        Err(e) => {
            println!("  Verification error: {e:?}");
            return;
        }
    }

    // Collect the assertions that were registered during verification.
    // Each assertion is an equality check: (lhs == rhs) becomes (lhs - rhs == 0).
    // These become api.AssertIsEqual(lhs, rhs) calls in the Gnark circuit.
    let assertions = take_assertions();
    println!("\n=== Accumulated Assertions ===");
    println!("  Total assertions: {}", assertions.len());

    // =========================================================================
    // Step 5: Build AstBundle for code generation
    // =========================================================================
    // AstBundle is the intermediate representation that bridges symbolic execution
    // and code generation. It contains:
    // - inputs: All symbolic variables (proof data that becomes circuit witness)
    // - constraints: Equality assertions that the circuit must enforce
    // - arena snapshot: The AST nodes representing all computed expressions
    println!("\n=== Building AstBundle ===");
    let mut bundle = AstBundle::new();
    bundle.snapshot_arena();

    // Register all symbolic variables as circuit inputs (witness values).
    // These will become struct fields in the generated Gnark circuit.
    // Use descriptions_with_fields() to include target field metadata.
    for (idx, name, target_field) in var_alloc.descriptions_with_fields() {
        bundle.add_input_with_field(*idx, name.clone(), WitnessType::ProofData, *target_field);
    }

    // Early warning if emulated arithmetic is needed (not yet implemented)
    if bundle.requires_emulated_arithmetic() {
        let fr_count = bundle.count_inputs_for_field(TargetField::Fr);
        let fq_count = bundle.count_inputs_for_field(TargetField::Fq);
        eprintln!(
            "⚠️  Bundle contains {} emulated-field variables (and {} native Fr variables).",
            fq_count, fr_count
        );
        eprintln!("    Emulated arithmetic codegen is not yet implemented — codegen will panic.");
    }
    println!("  Inputs: {}", bundle.inputs.len());

    // Register all equality assertions as circuit constraints.
    // Each assertion (lhs == rhs) becomes api.AssertIsEqual(lhs, rhs) in Gnark.
    for (i, assertion) in assertions.iter().enumerate() {
        bundle.add_constraint_eq_zero(format!("assertion_{i}"), assertion.root());
    }
    println!("  Constraints: {}", bundle.constraints.len());

    // Run CSE (Common Subexpression Elimination) at the AST level.
    // This pre-computes which nodes should be hoisted to named variables,
    // making codegen simpler (just reads pre-computed decisions).
    bundle.run_cse();
    println!(
        "  CSE bindings: {} total across {} constraints",
        bundle.constraint_cse.iter().map(|c| c.bindings.len()).sum::<usize>(),
        bundle.constraint_cse.len()
    );

    // =========================================================================
    // Step 6: Resolve output directory and write bundle
    // =========================================================================
    let default_output_dir = match args.target {
        TranspilationTarget::Gnark => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("go"),
        TranspilationTarget::AstBundle => PathBuf::from("."),
    };
    let output_dir = args.output_dir.clone().unwrap_or(default_output_dir);

    // Save bundle to JSON (common to all targets)
    let bundle_path = output_dir.join(BUNDLE_FILENAME);
    bundle
        .write_json(&bundle_path)
        .unwrap_or_else(|e| panic!("Failed to write bundle file {bundle_path:?}: {e}"));
    println!("  Bundle written to: {bundle_path:?}");

    // =========================================================================
    // Step 7: Target-specific code generation
    // =========================================================================
    match args.target {
        TranspilationTarget::Gnark => {
            // Generate gnark circuit
            // generate_circuit_from_bundle() traverses the AST and emits Go code:
            // - Each AST node (Add, Mul, Sub, etc.) becomes an api.Add/Mul/Sub call
            // - Common subexpressions are cached to avoid redundant computation
            // - The circuit struct contains all witness fields
            // - The Define() method contains all constraint logic
            println!("\n=== Generating Gnark Circuit ===");
            let circuit_code =
                gnark_codegen::generate_circuit_from_bundle(&bundle, "JoltStagesCircuit");

            let circuit_path = output_dir.join("stages_circuit.go");
            std::fs::write(&circuit_path, &circuit_code)
                .unwrap_or_else(|e| panic!("Failed to write circuit file {circuit_path:?}: {e}"));
            println!("  Circuit written to: {circuit_path:?}");
            println!("  Circuit size: {} bytes", circuit_code.len());

            // Get witness values captured during symbolization.
            // VarAllocator records both symbolic variables AND concrete values in a single pass,
            // making mismatch bugs structurally impossible.
            println!("\n=== Generating Witness Data ===");
            let witness_values = var_alloc.witness_values();

            let mut witness_map: HashMap<String, String> = HashMap::new();
            for (idx, name, _target_field) in var_alloc.descriptions_with_fields() {
                let sanitized = gnark_codegen::sanitize_go_name(name);
                if let Some(value) = witness_values.get(&(*idx as usize)) {
                    witness_map.insert(sanitized, value.clone());
                }
            }

            let witness_json =
                serde_json::to_string_pretty(&witness_map).expect("Failed to serialize witness");
            let witness_path = output_dir.join("stages_witness.json");
            std::fs::write(&witness_path, &witness_json)
                .unwrap_or_else(|e| panic!("Failed to write witness file {witness_path:?}: {e}"));
            println!("  Witness written to: {witness_path:?}");
            println!("  Witness variables: {}", witness_map.len());

            println!("\n=== SUCCESS ===");
            println!(
                "Stages 1-7 transpiled to Gnark. Run 'go test' in {:?} to verify.",
                output_dir
            );
        }
        TranspilationTarget::AstBundle => {
            println!("\n=== SUCCESS ===");
            println!("AstBundle written to: {bundle_path:?}");
            println!("  Inputs: {}", bundle.inputs.len());
            println!("  Constraints: {}", bundle.constraints.len());
        }
    }
}
