---
date: 2026-01-16
status: partial
branch: feat/zk
---

goal: Fix witness sizing and final_output handling in BlindFold R1CS

now: Debug RoundCoefficientsMismatch(55) in muldiv_e2e_dory

done:
  - Fixed witness.rs batching_coeffs filter (line 238: .filter(|fo| fo.constraint.is_none()))
  - Deduplicated required_openings via collect_unique_openings() helper in output_constraint.rs
  - sample_random_satisfying_pair generates final_output vars (folding.rs:117-141)
  - verify_round_coefficients_consistency skips final_output vars (relaxed_r1cs.rs:320-337)
  - Added estimate_aux_var_count helper to folding.rs and relaxed_r1cs.rs
  - All 28 blindfold unit tests pass

pending:
  - muldiv_e2e_dory fails with RoundCoefficientsMismatch(55)

blockers:
  - Coefficient mismatch at round 55 during BlindFold verification after folding
  - Round 55 is BEFORE any stage with final_output - likely unrelated to output constraint work

git:
  branch: feat/zk
  uncommitted: true
  unpushed: 2

tests:
  ran: cargo nextest run -p jolt-core blindfold
  passed: 28
  failed: 0

next:
  - Add logging to verify_round_coefficients_consistency to trace w_idx at round 55
  - Compare W_real[w_idx] vs W_random[w_idx] before folding
  - Check if stage_configs alignment differs between prover and sample_random_satisfying_pair

files:
  modified:
    - jolt-core/src/subprotocols/blindfold/output_constraint.rs (new)
    - jolt-core/src/subprotocols/blindfold/folding.rs
    - jolt-core/src/subprotocols/blindfold/relaxed_r1cs.rs
    - jolt-core/src/subprotocols/blindfold/witness.rs
    - jolt-core/src/subprotocols/blindfold/r1cs.rs
    - jolt-core/src/subprotocols/blindfold/mod.rs
    - jolt-core/src/zkvm/prover.rs
    - jolt-core/src/zkvm/registers/read_write_checking.rs
    - jolt-core/src/zkvm/ram/val_evaluation.rs
    - jolt-core/src/zkvm/ram/val_final.rs

risks:
  - estimate_aux_var_count duplicated in 3 files - consider extracting to shared location
  - RoundCoefficientsMismatch may be pre-existing bug exposed by witness sizing fixes
