edition = "2021"
tab_spaces = 4
newline_style = "Unix"
use_try_shorthand = true
reorder_imports = true

# Nightly
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true
max_width = 100

