[package]
name = "jolt-inlines-common"
version = "0.1.0"
edition = "2021"
description = "Common constants and utilities for Jolt inline implementations"

[features]
default = []
save_trace = ["dep:tracer"]

[dependencies]
tracer = { path = "../../tracer", optional = true }
