[package]
name = "verifier-on-jolt"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
guest = { package = "verifier-on-jolt-guest", path = "./guest" }
mimalloc = { version = "0.1.47" }