//! Host-side entry point for the modular Bolt-based prover.
//!
//! `prove_program` takes a guest `Program` + inputs and returns a
//! verifiable `JoltProof` by driving the modular stack
//! (jolt-prover + jolt-verifier + Bolt goldens) end-to-end. The
//! companion `verify_proof` rebuilds verifier inputs from the prover
//! artifacts and closes the soundness loop without re-tracing the
//! guest. Together they form the host-side surface that
//! `#[jolt::provable(backend = "modular")]` lowers to.
//!
//! Mirrors `crates/jolt-equivalence/src/bolt_oracle.rs`'s canonical
//! staged-prove chain with three substitutions:
//!   1. Bolt program plans come from `default_prover_programs()` /
//!      `default_verifier_programs()` (committed `pub const` goldens)
//!      instead of being regenerated by Bolt at runtime.
//!   2. Trace-derived data is built from a real tracer run on the
//!      supplied ELF rather than borrowed from a fixture.
//!   3. The monolithic `prove_jolt_with_witness_inputs` call is
//!      bypassed; we keep the staged artifacts and assemble `JoltProof`
//!      from them directly.

use common::constants::{BYTES_PER_INSTRUCTION, RAM_START_ADDRESS};
use common::jolt_device::{JoltDevice, MemoryLayout};
use jolt_core::host::Program;
use jolt_core::zkvm::instruction::InstructionLookup;
use jolt_core::zkvm::lookup_table::LookupTables as CoreLookupTables;
use jolt_core::zkvm::ram::gen_ram_memory_states;
use jolt_dory::{DoryProverSetup, DoryScheme};
use jolt_field::Fr;
use jolt_kernels::stage1::{Stage1OuterRv64Data, Stage1Rv64Cycle};
use jolt_kernels::stage2::{Stage2RamAccess, Stage2RamData, Stage2RamOutputLayout};
use jolt_kernels::stage3::Stage3Cycle;
use jolt_kernels::stage4::Stage4RegisterAccess;
use jolt_kernels::trace::{
    extract_trace_rows, stage1_rv64_cycles, stage2_instruction_lookup_cycles,
    stage2_product_virtual_cycles, stage2_ram_accesses, stage3_cycles, stage4_register_accesses,
    stage5_lookup_trace, stage6_bytecode_entries, CycleRow, Stage5LookupTrace,
};
use jolt_lookup_tables::tables::LookupTableKind;
use jolt_openings::CommitmentScheme as _;
use jolt_program::execution::TraceRow;
use jolt_program::preprocess::{BytecodePreprocessing, RAMPreprocessing};
use jolt_r1cs::{constraints::rv64, R1csKey};
use jolt_transcript::{Blake2bTranscript, Label, LabelWithCount, Transcript, U64Word};
use jolt_verifier::{
    default_verifier_programs, verify_jolt_with_programs, JoltProof, JoltVerifierInputs,
    JoltVerifyError,
};
use jolt_witness::{Stage6BytecodeEntry as WitnessStage6BytecodeEntry, Stage6WitnessParams};
use strum::EnumCount;
use tracer::emulator::memory::Memory;
use tracer::trace_row_from_cycle;

use jolt_prover::{default_prover_programs, JoltProveError, JoltProverArtifacts};

/// XLEN matches the rest of the modular stack (RV64).
const XLEN: usize = 64;

/// Dispatch `&NormalizedInstruction` to its modular lookup-table index
/// via jolt-core's `InstructionLookup` + the `CoreLookupTables` →
/// modular index conversion. Used as the closure for
/// `stage5_lookup_trace` and `stage6_bytecode_entries`.
fn instruction_lookup_table_index(instr: &jolt_riscv::NormalizedInstruction) -> Option<usize> {
    InstructionLookup::<XLEN>::lookup_table(instr)
        .map(|table| core_lookup_table_to_modular_index(&table))
}

/// Convert jolt-core's `LookupTables<XLEN>` variant to the modular
/// `LookupTableKind<XLEN>::index()`. Verbatim copy of
/// `jolt_equivalence::core_oracle::core_lookup_table_to_modular_index`;
/// kept private here to avoid a heavy dep on jolt-equivalence.
fn core_lookup_table_to_modular_index<const XL: usize>(table: &CoreLookupTables<XL>) -> usize {
    match table {
        CoreLookupTables::RangeCheck(_) => {
            LookupTableKind::<XL>::RangeCheck(Default::default()).index()
        }
        CoreLookupTables::RangeCheckAligned(_) => {
            LookupTableKind::<XL>::RangeCheckAligned(Default::default()).index()
        }
        CoreLookupTables::And(_) => LookupTableKind::<XL>::And(Default::default()).index(),
        CoreLookupTables::Andn(_) => LookupTableKind::<XL>::Andn(Default::default()).index(),
        CoreLookupTables::Or(_) => LookupTableKind::<XL>::Or(Default::default()).index(),
        CoreLookupTables::Xor(_) => LookupTableKind::<XL>::Xor(Default::default()).index(),
        CoreLookupTables::Equal(_) => LookupTableKind::<XL>::Equal(Default::default()).index(),
        CoreLookupTables::SignedGreaterThanEqual(_) => {
            LookupTableKind::<XL>::SignedGreaterThanEqual(Default::default()).index()
        }
        CoreLookupTables::UnsignedGreaterThanEqual(_) => {
            LookupTableKind::<XL>::UnsignedGreaterThanEqual(Default::default()).index()
        }
        CoreLookupTables::NotEqual(_) => {
            LookupTableKind::<XL>::NotEqual(Default::default()).index()
        }
        CoreLookupTables::SignedLessThan(_) => {
            LookupTableKind::<XL>::SignedLessThan(Default::default()).index()
        }
        CoreLookupTables::UnsignedLessThan(_) => {
            LookupTableKind::<XL>::UnsignedLessThan(Default::default()).index()
        }
        CoreLookupTables::Movsign(_) => LookupTableKind::<XL>::SignMask(Default::default()).index(),
        CoreLookupTables::UpperWord(_) => {
            LookupTableKind::<XL>::UpperWord(Default::default()).index()
        }
        CoreLookupTables::LessThanEqual(_) => {
            LookupTableKind::<XL>::UnsignedLessThanEqual(Default::default()).index()
        }
        CoreLookupTables::ValidUnsignedRemainder(_) => {
            LookupTableKind::<XL>::ValidUnsignedRemainder(Default::default()).index()
        }
        CoreLookupTables::ValidDiv0(_) => {
            LookupTableKind::<XL>::ValidDiv0(Default::default()).index()
        }
        CoreLookupTables::HalfwordAlignment(_) => {
            LookupTableKind::<XL>::HalfwordAlignment(Default::default()).index()
        }
        CoreLookupTables::WordAlignment(_) => {
            LookupTableKind::<XL>::WordAlignment(Default::default()).index()
        }
        CoreLookupTables::LowerHalfWord(_) => {
            LookupTableKind::<XL>::LowerHalfWord(Default::default()).index()
        }
        CoreLookupTables::SignExtendHalfWord(_) => {
            LookupTableKind::<XL>::SignExtendHalfWord(Default::default()).index()
        }
        CoreLookupTables::Pow2(_) => LookupTableKind::<XL>::Pow2(Default::default()).index(),
        CoreLookupTables::Pow2W(_) => LookupTableKind::<XL>::Pow2W(Default::default()).index(),
        CoreLookupTables::ShiftRightBitmask(_) => {
            LookupTableKind::<XL>::ShiftRightBitmask(Default::default()).index()
        }
        CoreLookupTables::VirtualRev8W(_) => {
            LookupTableKind::<XL>::VirtualRev8W(Default::default()).index()
        }
        CoreLookupTables::VirtualSRL(_) => {
            LookupTableKind::<XL>::VirtualSRL(Default::default()).index()
        }
        CoreLookupTables::VirtualSRA(_) => {
            LookupTableKind::<XL>::VirtualSRA(Default::default()).index()
        }
        CoreLookupTables::VirtualROTR(_) => {
            LookupTableKind::<XL>::VirtualROTR(Default::default()).index()
        }
        CoreLookupTables::VirtualROTRW(_) => {
            LookupTableKind::<XL>::VirtualROTRW(Default::default()).index()
        }
        CoreLookupTables::VirtualChangeDivisor(_) => {
            LookupTableKind::<XL>::VirtualChangeDivisor(Default::default()).index()
        }
        CoreLookupTables::VirtualChangeDivisorW(_) => {
            LookupTableKind::<XL>::VirtualChangeDivisorW(Default::default()).index()
        }
        CoreLookupTables::MulUNoOverflow(_) => {
            LookupTableKind::<XL>::MulUNoOverflow(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROT32(_) => {
            LookupTableKind::<XL>::VirtualXORROT32(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROT24(_) => {
            LookupTableKind::<XL>::VirtualXORROT24(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROT16(_) => {
            LookupTableKind::<XL>::VirtualXORROT16(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROT63(_) => {
            LookupTableKind::<XL>::VirtualXORROT63(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROTW16(_) => {
            LookupTableKind::<XL>::VirtualXORROTW16(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROTW12(_) => {
            LookupTableKind::<XL>::VirtualXORROTW12(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROTW8(_) => {
            LookupTableKind::<XL>::VirtualXORROTW8(Default::default()).index()
        }
        CoreLookupTables::VirtualXORROTW7(_) => {
            LookupTableKind::<XL>::VirtualXORROTW7(Default::default()).index()
        }
    }
}

/// Transcript label used by the modular prover (matches jolt-equivalence's).
pub const TRANSCRIPT_LABEL: &[u8] = b"Jolt";

/// Goldens-baked shape. Must equal `JoltProtocolParams::fixture()` in bolt.
pub const FIXTURE_LOG_T: usize = 18;
pub const FIXTURE_LOG_K_BYTECODE: usize = 14;
pub const FIXTURE_LOG_K_RAM: usize = 14;

#[derive(Debug)]
pub enum ProveProgramError {
    Prove(JoltProveError),
    Openings(jolt_prover::prover::JoltOpeningInputError),
    Trace(jolt_program::execution::TraceError),
    Preprocessing(jolt_program::preprocess::PreprocessingError),
    UnsupportedShape {
        log_t: usize,
        log_k_bytecode: usize,
        log_k_ram: usize,
    },
}

impl From<JoltProveError> for ProveProgramError {
    fn from(value: JoltProveError) -> Self {
        Self::Prove(value)
    }
}

impl From<jolt_prover::prover::JoltOpeningInputError> for ProveProgramError {
    fn from(value: jolt_prover::prover::JoltOpeningInputError) -> Self {
        Self::Openings(value)
    }
}

impl From<jolt_program::execution::TraceError> for ProveProgramError {
    fn from(value: jolt_program::execution::TraceError) -> Self {
        Self::Trace(value)
    }
}

impl From<jolt_program::preprocess::PreprocessingError> for ProveProgramError {
    fn from(value: jolt_program::preprocess::PreprocessingError) -> Self {
        Self::Preprocessing(value)
    }
}

#[derive(Debug)]
pub enum VerifyProgramError {
    Verify(JoltVerifyError),
    Openings(jolt_prover::prover::JoltOpeningInputError),
    Preprocessing(jolt_program::preprocess::PreprocessingError),
    MissingEvaluation,
    UnsupportedShape {
        log_t: usize,
        log_k_bytecode: usize,
        log_k_ram: usize,
    },
}

impl From<JoltVerifyError> for VerifyProgramError {
    fn from(value: JoltVerifyError) -> Self {
        Self::Verify(value)
    }
}

impl From<jolt_prover::prover::JoltOpeningInputError> for VerifyProgramError {
    fn from(value: jolt_prover::prover::JoltOpeningInputError) -> Self {
        Self::Openings(value)
    }
}

impl From<jolt_program::preprocess::PreprocessingError> for VerifyProgramError {
    fn from(value: jolt_program::preprocess::PreprocessingError) -> Self {
        Self::Preprocessing(value)
    }
}

/// Bundle returned by `prove_program` carrying everything needed to
/// verify the proof end-to-end via `verify_proof`.
pub struct ProofBundle {
    pub proof: JoltProof,
    pub io_device: JoltDevice,
    pub artifacts: JoltProverArtifacts,
    pub bytecode_entries: Vec<WitnessStage6BytecodeEntry<Fr>>,
    pub entry_bytecode_index: usize,
    pub lookup_table_count: usize,
    pub initial_ram_state: Vec<u64>,
    pub final_ram_state: Vec<u64>,
    pub lowest_addr: u64,
    pub entry_address: u64,
    params: ModularJoltParams,
    pcs_setup: DoryProverSetup,
}

/// `JoltProtocolParams` equivalent without the MLIR/LLVM dependency.
/// Hand-port of `JoltProtocolParams::new` from
/// `crates/bolt/src/protocols/jolt/params.rs`.
#[derive(Clone, Copy, Debug)]
struct ModularJoltParams {
    log_t: usize,
    trace_length: usize,
    log_k_bytecode: usize,
    #[expect(dead_code, reason = "kept for symmetry with JoltProtocolParams::new")]
    bytecode_k: usize,
    log_k_ram: usize,
    ram_k: usize,
    log_k_chunk: usize,
    lookups_ra_virtual_log_k_chunk: usize,
    register_log_k: usize,
    instruction_d: usize,
    instruction_ra_virtual_d: usize,
    bytecode_d: usize,
    ram_d: usize,
}

impl ModularJoltParams {
    fn new(log_t: usize, log_k_bytecode: usize, log_k_ram: usize) -> Self {
        let log_k_chunk = if log_t < 25 { 4 } else { 8 };
        let instruction_log_k = 128;
        let lookups_ra_virtual_log_k_chunk = if log_t < 25 {
            instruction_log_k / 8
        } else {
            instruction_log_k / 4
        };
        let instruction_d = instruction_log_k / log_k_chunk;
        let instruction_ra_virtual_d = instruction_log_k / lookups_ra_virtual_log_k_chunk;
        let bytecode_d = log_k_bytecode.div_ceil(log_k_chunk);
        let ram_d = log_k_ram.div_ceil(log_k_chunk);
        Self {
            log_t,
            trace_length: 1usize << log_t,
            log_k_bytecode,
            bytecode_k: 1usize << log_k_bytecode,
            log_k_ram,
            ram_k: 1usize << log_k_ram,
            log_k_chunk,
            lookups_ra_virtual_log_k_chunk,
            register_log_k: 7,
            instruction_d,
            instruction_ra_virtual_d,
            bytecode_d,
            ram_d,
        }
    }

    fn stage6_witness_params(&self) -> Stage6WitnessParams {
        Stage6WitnessParams {
            trace_len: self.trace_length,
            log_k_chunk: self.log_k_chunk,
            log_k_bytecode: self.log_k_bytecode,
            log_k_ram: self.log_k_ram,
            lookups_ra_virtual_log_k_chunk: self.lookups_ra_virtual_log_k_chunk,
            instruction_d: self.instruction_d,
            instruction_ra_virtual_d: self.instruction_ra_virtual_d,
            bytecode_d: self.bytecode_d,
            ram_d: self.ram_d,
        }
    }
}

/// Top-level: build a Jolt proof from a guest program + inputs by
/// driving the modular Bolt-based prover end-to-end.
pub fn prove_program(
    program: &mut Program,
    inputs: &[u8],
    untrusted_advice: &[u8],
    trusted_advice: &[u8],
) -> Result<ProofBundle, ProveProgramError> {
    // Use the legacy `Program::trace` (not `TracerBackend`/MemoryImage)
    // so we retain the tracer's `Memory` for jolt-core's
    // `gen_ram_memory_states`. MemoryImage's byte-pair representation
    // discards info that gen_ram_memory_states reads via
    // `get_doubleword`, producing a different RAM state vs the verifier.
    let (bytecode_raw, init_mem, _program_size, entry_address) = program.decode();
    let (_lazy, cycles, final_memory, io_device, field_reg_events) =
        program.trace(inputs, untrusted_advice, trusted_advice);
    let trace: Vec<TraceRow> = cycles.into_iter().map(trace_row_from_cycle).collect();

    let shape = check_shape(&trace, &io_device, &init_mem, bytecode_raw, entry_address)?;
    let params = ModularJoltParams::new(shape.log_t, shape.log_k_bytecode, shape.log_k_ram);

    let stages = assemble_and_prove(
        &trace,
        &shape.bytecode,
        &io_device,
        &init_mem,
        &final_memory,
        entry_address,
        &params,
        shape.trace_length,
        shape.ram_k,
        field_reg_events,
    )?;

    Ok(ProofBundle {
        proof: stages.proof,
        io_device,
        artifacts: stages.artifacts,
        bytecode_entries: stages.bytecode_entries,
        entry_bytecode_index: stages.entry_bytecode_index,
        lookup_table_count: stages.lookup_table_count,
        initial_ram_state: stages.initial_ram_state,
        final_ram_state: stages.final_ram_state,
        lowest_addr: stages.lowest_addr,
        entry_address,
        params,
        pcs_setup: stages.pcs_setup,
    })
}

struct ResolvedShape {
    bytecode: BytecodePreprocessing,
    trace_length: usize,
    ram_k: usize,
    log_t: usize,
    log_k_bytecode: usize,
    log_k_ram: usize,
}

fn check_shape(
    trace: &[TraceRow],
    io_device: &JoltDevice,
    init_mem: &[(u64, u8)],
    bytecode_raw: Vec<jolt_riscv::NormalizedInstruction>,
    entry_address: u64,
) -> Result<ResolvedShape, ProveProgramError> {
    let natural_trace_length = trace.len().next_power_of_two().max(256);
    let trace_length = natural_trace_length.max(1usize << FIXTURE_LOG_T);
    let bytecode = BytecodePreprocessing::preprocess_with_min_size(
        bytecode_raw,
        entry_address,
        1usize << FIXTURE_LOG_K_BYTECODE,
    )?;
    let memory_layout = io_device.memory_layout.clone();
    let natural_ram_k = compute_min_ram_k(init_mem, trace, &memory_layout);
    let ram_k = natural_ram_k.max(1usize << FIXTURE_LOG_K_RAM);

    let log_t = trace_length.trailing_zeros() as usize;
    let log_k_bytecode = bytecode.code_size.trailing_zeros() as usize;
    let log_k_ram = ram_k.trailing_zeros() as usize;

    if log_t != FIXTURE_LOG_T
        || log_k_bytecode != FIXTURE_LOG_K_BYTECODE
        || log_k_ram != FIXTURE_LOG_K_RAM
    {
        return Err(ProveProgramError::UnsupportedShape {
            log_t,
            log_k_bytecode,
            log_k_ram,
        });
    }

    Ok(ResolvedShape {
        bytecode,
        trace_length,
        ram_k,
        log_t,
        log_k_bytecode,
        log_k_ram,
    })
}

struct ProveStageOutput {
    proof: JoltProof,
    artifacts: JoltProverArtifacts,
    bytecode_entries: Vec<WitnessStage6BytecodeEntry<Fr>>,
    entry_bytecode_index: usize,
    lookup_table_count: usize,
    initial_ram_state: Vec<u64>,
    final_ram_state: Vec<u64>,
    lowest_addr: u64,
    pcs_setup: DoryProverSetup,
}

/// Per-cycle FR bytecode metadata derived from `NormalizedInstruction.instruction_kind`.
/// Per-kind FR read flags. FMUL/FADD/FSUB/FAssertEq are two-input;
/// FINV reads only frs1; FieldMov/FieldSLL* are integer-register bridges.
/// Audit finding C-A3 (`reads_frs2` overstatement on FINV) is fixed here
/// because we now have a distinct `FieldInv` kind to match on.
fn fr_bytecode_from_trace(trace: &[TraceRow]) -> Vec<jolt_witness::field_reg::FrCycleBytecode> {
    use jolt_witness::field_reg::FIELD_REG_ADDR_MASK;
    let mask_u8 = FIELD_REG_ADDR_MASK as u8;
    trace
        .iter()
        .map(|row| {
            let instr = row.instruction;
            let (reads_frs1, reads_frs2, writes_frd) = instr.instruction_kind.fr_access_flags();
            jolt_witness::field_reg::FrCycleBytecode {
                frs1: instr.operands.rs1.unwrap_or(0) & mask_u8,
                frs2: instr.operands.rs2.unwrap_or(0) & mask_u8,
                frd: instr.operands.rd.unwrap_or(0) & mask_u8,
                reads_frs1,
                reads_frs2,
                writes_frd,
            }
        })
        .collect()
}

/// Convert the tracer's `FieldRegEvent` stream to `jolt-witness` events.
///
/// `rd_written` is derived from `new != old` rather than hardcoded to `true`:
///   - FieldMul/Add/Sub/Inv almost always change `field_regs[frd]`.
///   - FieldAssertEq emits an event with `slot = frs1` (see
///     `tracer/src/instruction/field_assert_eq.rs`) and the value is
///     unchanged, so `new == old` and `rd_written = false` — keeping
///     FieldAssertEq out of the FR Twist's write-side accounting.
///   - FieldMov / FieldSLL* always change `field_regs[frd]` because they
///     write the (zero-extended) integer rs1.
///
/// Only `cycle`, `frd`, `rd_post`, and `rd_written` flow into the
/// materializer; `frs1/frs2/rs1_pre/rs2_pre` are populated separately by
/// `populate_r1cs_fr_slots` (which walks the trace + running state).
fn convert_fr_events(
    events: Vec<tracer::emulator::cpu::FieldRegEvent>,
) -> Vec<jolt_witness::field_reg::FieldRegEvent> {
    events
        .into_iter()
        .map(|ev| jolt_witness::field_reg::FieldRegEvent {
            cycle: ev.cycle_index as u64,
            frs1: 0,
            frs2: 0,
            frd: ev.slot,
            rs1_pre: jolt_witness::field_reg::FrLimbs::ZERO,
            rs2_pre: jolt_witness::field_reg::FrLimbs::ZERO,
            rd_post: jolt_witness::field_reg::FrLimbs::from_limbs(ev.new),
            rd_written: ev.new != ev.old,
        })
        .collect()
}

/// Post-process R1CS witness to populate FR slots (V_FIELD_RS1_VALUE,
/// V_FIELD_RS2_VALUE, V_FIELD_RD_WRITE_VALUE) on FR-active cycles.
///
/// `extract_trace_rows` leaves these slots at zero — the R1CS witness
/// generator doesn't know about FR events. Stage 3 FieldRegClaimReduction
/// reads these slots via the oracle plumbing and publishes the claim that
/// Stage 4 FieldRegRW must reconcile against materialized FR polynomials.
/// Without this pass the two sides disagree and Stage 4 fails with an
/// input-claim mismatch.
///
/// Walks the FR replay's running state to derive pre-values for each event
/// (rs1_pre = state[frs1] at cycle c, rs2_pre = state[frs2], rd_post = the
/// post-event new value). Encodes via `limbs_to_field` (natural-form
/// `a0 + a1·2^64 + a2·2^128 + a3·2^192`) to match the materializer.
fn populate_r1cs_fr_slots(
    r1cs_witness: &mut [Fr],
    num_vars_padded: usize,
    trace: &[TraceRow],
    replay: &jolt_witness::field_reg::FieldRegReplay,
) {
    use jolt_riscv::JoltInstructionKind;
    use jolt_witness::field_reg::{
        limbs_to_field, FieldRegEvent, FIELD_REG_ADDR_MASK, FIELD_REG_COUNT,
    };
    if replay.events.is_empty() {
        return;
    }
    let mut current: [Fr; FIELD_REG_COUNT] = [Fr::from_u64(0); FIELD_REG_COUNT];
    let mut events = replay.events.iter().peekable();
    let len = replay.num_cycles.min(trace.len());
    for (c, row) in trace.iter().take(len).enumerate() {
        let offset = c * num_vars_padded;
        let bc = replay.bytecode.get(c).copied().unwrap_or_default();
        let kind = row.instruction.instruction_kind;
        if bc.reads_frs1 {
            let slot = (bc.frs1 as usize) & FIELD_REG_ADDR_MASK;
            r1cs_witness[offset + rv64::V_FIELD_RS1_VALUE] = current[slot];
        }
        if bc.reads_frs2 {
            let slot = (bc.frs2 as usize) & FIELD_REG_ADDR_MASK;
            r1cs_witness[offset + rv64::V_FIELD_RS2_VALUE] = current[slot];
        }
        // Populate V_FIELD_RD_WRITE_VALUE on every cycle where bytecode says
        // writes_frd=true. When the event lacks rd_written=true (rare new==old
        // case), the post value equals the current state — consistent with
        // Stage 4 RW's bytecode-anchored `frd_wa` polynomial (always 1 when
        // bc.writes_frd) and Stage 5 ValEvaluation.
        let event_opt = events.next_if(|ev: &&FieldRegEvent| ev.cycle as usize == c);
        let mut rd_post_opt: Option<Fr> = None;
        if bc.writes_frd {
            let slot = (bc.frd as usize) & FIELD_REG_ADDR_MASK;
            let post: Fr = match event_opt {
                Some(ev) if ev.rd_written => limbs_to_field(ev.rd_post.into_limbs()),
                _ => current[slot],
            };
            r1cs_witness[offset + rv64::V_FIELD_RD_WRITE_VALUE] = post;
            current[slot] = post;
            rd_post_opt = Some(post);
        }
        // FMUL / FINV route FR operands through the canonical product gate
        // (R1CS row 36: `Left × Right = Product`). The eq-rows 26-31 then
        // bind `Left = FieldRs1`, `Right = FieldRs2` (FMUL) or `FieldRd`
        // (FINV), and `Product = FieldRd` (FMUL) or `1` (FINV) — which
        // forces the multiplicative arithmetic to hold natively.
        // Row 6 / row 10 additionally tie LookupOperands to Left/Right on
        // non-Add/Sub/Mul-integer cycles, so we mirror Fr values there too.
        match kind {
            JoltInstructionKind::FieldMul => {
                let rs1 = r1cs_witness[offset + rv64::V_FIELD_RS1_VALUE];
                let rs2 = r1cs_witness[offset + rv64::V_FIELD_RS2_VALUE];
                let product = rs1 * rs2;
                r1cs_witness[offset + rv64::V_LEFT_INSTRUCTION_INPUT] = rs1;
                r1cs_witness[offset + rv64::V_RIGHT_INSTRUCTION_INPUT] = rs2;
                r1cs_witness[offset + rv64::V_PRODUCT] = product;
                r1cs_witness[offset + rv64::V_LEFT_LOOKUP_OPERAND] = rs1;
                r1cs_witness[offset + rv64::V_RIGHT_LOOKUP_OPERAND] = rs2;
            }
            JoltInstructionKind::FieldInv => {
                let rs1 = r1cs_witness[offset + rv64::V_FIELD_RS1_VALUE];
                let rd = rd_post_opt.unwrap_or_else(|| Fr::from_u64(0));
                r1cs_witness[offset + rv64::V_LEFT_INSTRUCTION_INPUT] = rs1;
                r1cs_witness[offset + rv64::V_RIGHT_INSTRUCTION_INPUT] = rd;
                r1cs_witness[offset + rv64::V_PRODUCT] = Fr::from_u64(1);
                r1cs_witness[offset + rv64::V_LEFT_LOOKUP_OPERAND] = rs1;
                r1cs_witness[offset + rv64::V_RIGHT_LOOKUP_OPERAND] = rd;
            }
            _ => {}
        }
    }
}

/// Walks the FR replay running state in lockstep with the materializer/R1CS
/// post-pass and stamps the FR fields on both `Stage1Rv64Cycle` (for the Stage 1
/// outer Spartan sumcheck's virtual oracle reads) and `Stage3Cycle` (for the
/// Stage 3 FieldRegClaimReduction sumcheck's factor population). Mutates the
/// vectors in place — non-FR cycles keep their `[0; 4]` defaults.
fn populate_fr_cycle_fields(
    rv64_cycles: &mut [Stage1Rv64Cycle],
    stage3_cycles: &mut [Stage3Cycle],
    replay: &jolt_witness::field_reg::FieldRegReplay,
) {
    use jolt_witness::field_reg::{FieldRegEvent, FIELD_REG_ADDR_MASK, FIELD_REG_COUNT};
    if replay.events.is_empty() {
        return;
    }
    let mut current: [[u64; 4]; FIELD_REG_COUNT] = [[0; 4]; FIELD_REG_COUNT];
    let mut events = replay.events.iter().peekable();
    let len = rv64_cycles
        .len()
        .min(stage3_cycles.len())
        .min(replay.num_cycles);
    for c in 0..len {
        let bc = replay.bytecode.get(c).copied().unwrap_or_default();
        let rs1 = if bc.reads_frs1 {
            current[(bc.frs1 as usize) & FIELD_REG_ADDR_MASK]
        } else {
            [0; 4]
        };
        let rs2 = if bc.reads_frs2 {
            current[(bc.frs2 as usize) & FIELD_REG_ADDR_MASK]
        } else {
            [0; 4]
        };
        // Bytecode-anchored: write the post-state to slot bc.frd on every
        // bc.writes_frd cycle, regardless of event.rd_written. When the event
        // is absent or rd_written=false, post equals the current state (no
        // change). Keeps field_rd in sync with the bytecode-anchored
        // V_FIELD_RD_WRITE_VALUE column.
        let event_opt = events.next_if(|ev: &&FieldRegEvent| ev.cycle as usize == c);
        let (rd, is_field_op) = if bc.writes_frd {
            let slot = (bc.frd as usize) & FIELD_REG_ADDR_MASK;
            let post = match event_opt {
                Some(ev) if ev.rd_written => ev.rd_post.into_limbs(),
                _ => current[slot],
            };
            current[slot] = post;
            (post, true)
        } else if event_opt.is_some() || bc.reads_frs1 || bc.reads_frs2 {
            ([0; 4], true)
        } else {
            ([0; 4], false)
        };
        rv64_cycles[c].field_rs1 = rs1;
        rv64_cycles[c].field_rs2 = rs2;
        rv64_cycles[c].field_rd = rd;
        stage3_cycles[c].field_rs1 = rs1;
        stage3_cycles[c].field_rs2 = rs2;
        stage3_cycles[c].field_rd = rd;
        stage3_cycles[c].is_field_op = is_field_op;
    }
}

#[expect(
    clippy::too_many_arguments,
    reason = "thin internal helper; arguments are derived state from prove_program"
)]
fn assemble_and_prove(
    trace: &[TraceRow],
    bytecode: &BytecodePreprocessing,
    io_device: &JoltDevice,
    init_mem: &[(u64, u8)],
    final_memory: &Memory,
    entry_address: u64,
    params: &ModularJoltParams,
    trace_length: usize,
    ram_k: usize,
    field_reg_events: Vec<tracer::emulator::cpu::FieldRegEvent>,
) -> Result<ProveStageOutput, ProveProgramError> {
    let memory_layout = io_device.memory_layout.clone();

    let r1cs_key = R1csKey::new(rv64::rv64_constraints::<Fr>(), trace_length);
    let (cycle_inputs, mut r1cs_witness) = extract_trace_rows::<Fr>(
        trace,
        trace_length,
        bytecode,
        &memory_layout,
        r1cs_key.num_vars_padded,
    );

    // Build the FR replay early so it can populate both the R1CS witness's
    // FR slots (V_FIELD_RS1/RS2/RD_WRITE_VALUE) and Stage 4/5 materializers
    // off the same event stream + bytecode metadata.
    let fr_replay = jolt_witness::field_reg::FieldRegReplay {
        num_cycles: trace_length,
        bytecode: {
            let mut bc = fr_bytecode_from_trace(trace);
            bc.resize(
                trace_length,
                jolt_witness::field_reg::FrCycleBytecode::default(),
            );
            bc
        },
        events: convert_fr_events(field_reg_events),
    };
    populate_r1cs_fr_slots(
        &mut r1cs_witness,
        r1cs_key.num_vars_padded,
        trace,
        &fr_replay,
    );
    let mut rv64_cycles: Vec<Stage1Rv64Cycle> = stage1_rv64_cycles(trace, trace_length, bytecode);
    let product_virtual_cycles = stage2_product_virtual_cycles(trace, trace_length);
    let instruction_lookup_cycles = stage2_instruction_lookup_cycles(trace, trace_length);
    let lowest_addr = memory_layout.get_lowest_address();
    let remap_addr = |addr: u64| {
        if addr == 0 || addr < lowest_addr {
            None
        } else {
            Some(((addr - lowest_addr) / 8) as usize)
        }
    };
    let ram_accesses: Vec<Stage2RamAccess> = stage2_ram_accesses(trace, trace_length, remap_addr);
    let mut stage3_cycles_vec: Vec<Stage3Cycle> = stage3_cycles(trace, trace_length, bytecode);
    populate_fr_cycle_fields(&mut rv64_cycles, &mut stage3_cycles_vec, &fr_replay);
    let stage4_register_accesses_vec: Vec<Stage4RegisterAccess> =
        stage4_register_accesses(trace, trace_length);
    let lookup_trace: Stage5LookupTrace = stage5_lookup_trace(trace, trace_length, |cycle| {
        instruction_lookup_table_index(&cycle.instruction())
    });
    let stage6_bytecode_entries_vec: Vec<WitnessStage6BytecodeEntry<Fr>> =
        stage6_bytecode_entries::<Fr, _>(bytecode, instruction_lookup_table_index);
    // Use jolt-core's canonical RAM state builder so prover/verifier
    // agree on init+final cells exactly. RAMPreprocessing handles the
    // bytecode-byte → u64-word packing the verifier-side RAM checks
    // expect.
    let ram_preprocessing = RAMPreprocessing::preprocess(init_mem.to_vec());
    // gen_ram_memory_states is generic over `F: jolt_core::field::JoltField`;
    // jolt_field::Fr is a transparent newtype around ark_bn254::Fr without
    // that bound, so we instantiate with the inner ark type.
    let (initial_ram_state, final_ram_state) =
        gen_ram_memory_states::<ark_bn254::Fr>(ram_k, &ram_preprocessing, io_device, final_memory);

    let pcs_setup = DoryScheme::setup_prover(params.log_t + params.log_k_chunk);

    let programs = default_prover_programs();
    let mut transcript = Blake2bTranscript::<Fr>::new(TRANSCRIPT_LABEL);
    append_bolt_preamble(
        &mut transcript,
        &PreambleData {
            io: io_device,
            params,
            entry_address,
        },
    );

    let commitment_sources = jolt_witness::commitment_trace_sources(&cycle_inputs);
    let oracle_inputs = jolt_prover::stages::commitment::CommitmentOracleInputs::from_trace_sources(
        &commitment_sources,
        None,
        None,
    );
    let mut commitment_inputs =
        jolt_prover::stages::commitment::SparseCommitmentInputs::new(oracle_inputs);
    let commitment_artifacts =
        jolt_prover::stages::commitment::prove_commitment_phase_with_program(
            programs.commitment,
            &mut commitment_inputs,
            &pcs_setup,
            &mut transcript,
        )
        .map_err(JoltProveError::Commitment)?;

    let stage1_data = Stage1OuterRv64Data::new(&r1cs_key, &r1cs_witness, &rv64_cycles)
        .map_err(JoltProveError::Stage1Outer)?;
    let stage1_artifacts = jolt_prover::prove_stage1_outer_with_witness_inputs(
        programs.stage1_outer,
        r1cs_key.num_cycle_vars(),
        &stage1_data,
        &mut transcript,
    )
    .map_err(JoltProveError::Stage1Outer)?;

    let ram_output_layout = Stage2RamOutputLayout {
        io_start: ((memory_layout.input_start - lowest_addr) / 8) as usize,
        io_end: ((RAM_START_ADDRESS - lowest_addr) / 8) as usize,
    };
    let ram_data = Stage2RamData {
        log_k: params.log_k_ram,
        start_address: lowest_addr,
        initial_ram: &initial_ram_state,
        final_ram: &final_ram_state,
        accesses: &ram_accesses,
        output_layout: Some(ram_output_layout),
    };
    let stage2_openings =
        jolt_prover::stage2_opening_inputs_from_artifacts(programs.stage2, &stage1_artifacts)?;
    let stage2_artifacts = jolt_prover::prove_stage2_with_witness_inputs(
        programs.stage2,
        &stage2_openings,
        &product_virtual_cycles,
        &instruction_lookup_cycles,
        &ram_data,
        &mut transcript,
    )
    .map_err(JoltProveError::Stage2)?;

    let stage3_openings = jolt_prover::stage3_opening_inputs_from_artifacts(
        programs.stage3,
        &stage1_artifacts,
        &stage2_artifacts,
    )?;
    let stage3_artifacts = jolt_prover::prove_stage3_with_witness_inputs(
        programs.stage3,
        &stage3_openings,
        &stage3_cycles_vec,
        &mut transcript,
    )
    .map_err(JoltProveError::Stage3)?;

    let stage4_openings = jolt_prover::stage4_opening_inputs_from_artifacts(
        programs.stage4,
        &initial_ram_state,
        &stage2_artifacts,
        &stage3_artifacts,
    )?;
    let mut stage45_witness = jolt_kernels::stage4::stage4_5_sparse_trace_witness_from_accesses::<Fr>(
        &stage4_register_accesses_vec,
        &ram_accesses,
    );
    stage45_witness = stage45_witness.with_field_reg_replay(fr_replay.clone());

    let stage4_artifacts = jolt_prover::prove_stage4_with_witness_inputs(
        programs.stage4,
        &stage4_openings,
        1usize << params.register_log_k,
        params.trace_length,
        params.ram_k,
        &stage4_register_accesses_vec,
        &stage45_witness,
        &mut transcript,
    )
    .map_err(JoltProveError::Stage4)?;

    let stage5_openings = jolt_prover::stage5_opening_inputs_from_artifacts(
        programs.stage5,
        &stage2_artifacts,
        &stage4_artifacts,
    )?;
    let stage5_artifacts = jolt_prover::prove_stage5_with_witness_inputs(
        programs.stage5,
        &stage5_openings,
        params.trace_length,
        params.ram_k,
        1usize << params.register_log_k,
        &lookup_trace.lookup_indices,
        &lookup_trace.lookup_table_indices,
        &lookup_trace.is_interleaved_operands,
        params.lookups_ra_virtual_log_k_chunk,
        &stage45_witness,
        &mut transcript,
    )
    .map_err(JoltProveError::Stage5)?;

    let stage6_openings = jolt_prover::stage6_opening_inputs_from_artifacts(
        programs.stage6,
        &stage1_artifacts,
        &stage2_artifacts,
        &stage3_artifacts,
        &stage4_artifacts,
        &stage5_artifacts,
    )?;
    let entry_bytecode_index = bytecode.entry_bytecode_index().unwrap_or(0);
    let lookup_table_count = <LookupTableKind<XLEN> as EnumCount>::COUNT;
    let stage6_bytecode_data = jolt_prover::stage6_bytecode_read_raf_data_from_witness_entries(
        &stage6_bytecode_entries_vec,
        entry_bytecode_index,
        lookup_table_count,
    );
    let stage6_artifacts = jolt_prover::prove_stage6_with_trace_witness_inputs(
        programs.stage6,
        &stage6_openings,
        stage6_bytecode_data.as_input(),
        params.stage6_witness_params(),
        &cycle_inputs,
        params.instruction_ra_virtual_d,
        &mut transcript,
    )
    .map_err(JoltProveError::Stage6)?;

    let stage7_openings = jolt_prover::stage7_opening_inputs_from_stage6_artifacts_with_program(
        programs.stage7,
        &stage6_artifacts,
    )?;
    let stage7_artifacts = jolt_prover::prove_stage7_with_trace_witness_inputs(
        programs.stage7,
        &stage7_openings,
        params.stage6_witness_params(),
        &cycle_inputs,
        &stage6_openings,
        &mut transcript,
    )
    .map_err(JoltProveError::Stage7)?;

    let evaluation = jolt_prover::prove_jolt_evaluation_proof(
        programs.stage8,
        &mut commitment_inputs,
        &pcs_setup,
        &commitment_artifacts,
        &stage6_artifacts,
        &stage7_artifacts,
        &stage7_openings,
        &mut transcript,
    )
    .map_err(JoltProveError::Evaluation)?;

    let stage5_proof = jolt_prover::stage5_proof(&stage5_artifacts);
    let stage6_proof = jolt_prover::stage6_proof(&stage6_artifacts);
    let stage7_proof = jolt_prover::stage7_proof(&stage7_artifacts);
    let mut proof = jolt_prover::jolt_proof_through_stage7(
        &commitment_artifacts.commitments,
        &stage1_artifacts,
        &stage2_artifacts,
        &stage3_artifacts,
        &stage4_artifacts,
        &stage5_proof,
        &stage6_proof,
        &stage7_proof,
    );
    proof.evaluation = Some(evaluation);

    let artifacts = JoltProverArtifacts {
        commitment: commitment_artifacts,
        stage1_outer: stage1_artifacts,
        stage2: stage2_artifacts,
        stage3: stage3_artifacts,
        stage4: stage4_artifacts,
        stage5: stage5_artifacts,
        stage6: stage6_artifacts,
        stage7: stage7_artifacts,
    };

    Ok(ProveStageOutput {
        proof,
        artifacts,
        bytecode_entries: stage6_bytecode_entries_vec,
        entry_bytecode_index,
        lookup_table_count,
        initial_ram_state,
        final_ram_state,
        lowest_addr,
        pcs_setup,
    })
}

pub fn verify_proof(output: &ProofBundle, program: &mut Program) -> Result<(), VerifyProgramError> {
    if output.proof.evaluation.is_none() {
        return Err(VerifyProgramError::MissingEvaluation);
    }

    let (bytecode_raw, _init_mem, _program_size, decoded_entry_address) = program.decode();
    let bytecode = BytecodePreprocessing::preprocess_with_min_size(
        bytecode_raw,
        decoded_entry_address,
        1usize << output.params.log_k_bytecode,
    )?;
    let log_k_bytecode = bytecode.code_size.trailing_zeros() as usize;
    if log_k_bytecode != output.params.log_k_bytecode
        || decoded_entry_address != output.entry_address
    {
        return Err(VerifyProgramError::UnsupportedShape {
            log_t: output.params.log_t,
            log_k_bytecode,
            log_k_ram: output.params.log_k_ram,
        });
    }

    let programs = default_verifier_programs();
    let prover_programs = default_prover_programs();

    let stage2_kernel_openings = jolt_prover::stage2_opening_inputs_from_artifacts(
        prover_programs.stage2,
        &output.artifacts.stage1_outer,
    )?;
    let stage3_kernel_openings = jolt_prover::stage3_opening_inputs_from_artifacts(
        prover_programs.stage3,
        &output.artifacts.stage1_outer,
        &output.artifacts.stage2,
    )?;
    let stage4_kernel_openings = jolt_prover::stage4_opening_inputs_from_artifacts(
        prover_programs.stage4,
        &output.initial_ram_state,
        &output.artifacts.stage2,
        &output.artifacts.stage3,
    )?;
    let stage5_kernel_openings = jolt_prover::stage5_opening_inputs_from_artifacts(
        prover_programs.stage5,
        &output.artifacts.stage2,
        &output.artifacts.stage4,
    )?;
    let stage6_kernel_openings = jolt_prover::stage6_opening_inputs_from_artifacts(
        prover_programs.stage6,
        &output.artifacts.stage1_outer,
        &output.artifacts.stage2,
        &output.artifacts.stage3,
        &output.artifacts.stage4,
        &output.artifacts.stage5,
    )?;
    let stage7_kernel_openings =
        jolt_prover::stage7_opening_inputs_from_stage6_artifacts_with_program(
            prover_programs.stage7,
            &output.artifacts.stage6,
        )?;

    let stage2_openings = jolt_prover::verifier_opening_inputs_from_kernel(&stage2_kernel_openings);
    let stage3_openings = jolt_prover::verifier_opening_inputs_from_kernel(&stage3_kernel_openings);
    let stage4_openings = jolt_prover::verifier_opening_inputs_from_kernel(&stage4_kernel_openings);
    let stage5_openings = jolt_prover::verifier_opening_inputs_from_kernel(&stage5_kernel_openings);
    let stage6_openings = jolt_prover::verifier_opening_inputs_from_kernel(&stage6_kernel_openings);
    let stage7_openings = jolt_prover::verifier_opening_inputs_from_kernel(&stage7_kernel_openings);

    let memory_layout = output.io_device.memory_layout.clone();
    let ram_output_layout = Stage2RamOutputLayout {
        io_start: ((memory_layout.input_start - output.lowest_addr) / 8) as usize,
        io_end: ((RAM_START_ADDRESS - output.lowest_addr) / 8) as usize,
    };
    let kernel_ram_data = Stage2RamData {
        log_k: output.params.log_k_ram,
        start_address: output.lowest_addr,
        initial_ram: &output.initial_ram_state,
        final_ram: &output.final_ram_state,
        accesses: &[],
        output_layout: Some(ram_output_layout),
    };
    let verifier_ram_storage = jolt_prover::stage2_verifier_ram_data(&kernel_ram_data);
    let verifier_ram = verifier_ram_storage.as_input();

    let stage6_data = jolt_prover::stage6_verifier_data_from_witness_entries(
        &output.bytecode_entries,
        output.entry_bytecode_index,
        output.lookup_table_count,
    );

    let evaluation_setup = DoryScheme::verifier_setup(&output.pcs_setup);

    let inputs = JoltVerifierInputs {
        stage2_openings: &stage2_openings,
        stage2_ram: Some(&verifier_ram),
        stage3_openings: &stage3_openings,
        stage4_openings: &stage4_openings,
        stage5_openings: &stage5_openings,
        stage6_openings: &stage6_openings,
        stage6_data: Some(&stage6_data),
        stage7_openings: &stage7_openings,
        evaluation_setup: Some(&evaluation_setup),
    };

    let mut transcript = Blake2bTranscript::<Fr>::new(TRANSCRIPT_LABEL);
    append_bolt_preamble(
        &mut transcript,
        &PreambleData {
            io: &output.io_device,
            params: &output.params,
            entry_address: output.entry_address,
        },
    );

    let _ = verify_jolt_with_programs(&output.proof, inputs, programs, &mut transcript)?;
    Ok(())
}

struct PreambleData<'a> {
    io: &'a JoltDevice,
    params: &'a ModularJoltParams,
    entry_address: u64,
}

fn append_bolt_preamble<T>(transcript: &mut T, data: &PreambleData<'_>)
where
    T: Transcript<Challenge = Fr>,
{
    let preprocessing_digest = [0u8; 32];
    append_bytes(transcript, b"preprocessing_digest", &preprocessing_digest);
    let layout = &data.io.memory_layout;
    append_u64(transcript, b"max_input_size", layout.max_input_size);
    append_u64(transcript, b"max_output_size", layout.max_output_size);
    append_u64(transcript, b"heap_size", layout.heap_size);
    append_bytes(transcript, b"inputs", &data.io.inputs);
    append_bytes(transcript, b"outputs", &data.io.outputs);
    append_u64(transcript, b"panic", data.io.panic as u64);
    append_u64(transcript, b"ram_K", data.params.ram_k as u64);
    append_u64(transcript, b"trace_length", data.params.trace_length as u64);
    append_u64(transcript, b"entry_address", data.entry_address);
    append_u64(
        transcript,
        b"ram_rw_phase1_num_rounds",
        data.params.log_t as u64,
    );
    append_u64(
        transcript,
        b"ram_rw_phase2_num_rounds",
        data.params.log_k_ram as u64,
    );
    append_u64(
        transcript,
        b"registers_rw_phase1_num_rounds",
        data.params.log_t as u64,
    );
    append_u64(
        transcript,
        b"registers_rw_phase2_num_rounds",
        data.params.register_log_k as u64,
    );
    append_u64(transcript, b"log_k_chunk", data.params.log_k_chunk as u64);
    append_u64(
        transcript,
        b"lookups_ra_virtual_log_k_chunk",
        data.params.lookups_ra_virtual_log_k_chunk as u64,
    );
    // dory_layout: 0 = CycleMajor, 1 = AddressMajor. Fixture uses CycleMajor.
    append_u64(transcript, b"dory_layout", 0);
}

fn append_u64<T>(transcript: &mut T, label: &'static [u8], value: u64)
where
    T: Transcript<Challenge = Fr>,
{
    transcript.append(&Label(label));
    transcript.append(&U64Word(value));
}

fn append_bytes<T>(transcript: &mut T, label: &'static [u8], bytes: &[u8])
where
    T: Transcript<Challenge = Fr>,
{
    transcript.append(&LabelWithCount(label, bytes.len() as u64));
    transcript.append_bytes(bytes);
}

fn compute_min_ram_k(
    init_mem: &[(u64, u8)],
    trace: &[impl CycleRow],
    memory_layout: &MemoryLayout,
) -> usize {
    let lowest_addr = memory_layout.get_lowest_address();
    let min_bc_addr = init_mem
        .iter()
        .map(|(a, _)| *a)
        .min()
        .unwrap_or(lowest_addr);
    let max_bc_addr = init_mem
        .iter()
        .map(|(a, _)| *a)
        .max()
        .unwrap_or(lowest_addr)
        + (BYTES_PER_INSTRUCTION as u64 - 1);
    let num_bc_words = max_bc_addr.div_ceil(8) - min_bc_addr / 8 + 1;
    let bytecode_start_remapped = if min_bc_addr >= lowest_addr && min_bc_addr != 0 {
        (min_bc_addr - lowest_addr) / 8
    } else {
        0
    };
    let trace_max_remapped: u64 = trace
        .iter()
        .filter_map(|cycle| {
            let addr = cycle.ram_access_address()?;
            if addr == 0 || addr < lowest_addr {
                None
            } else {
                Some((addr - lowest_addr) / 8)
            }
        })
        .max()
        .unwrap_or(0);
    let io_end_remapped = if RAM_START_ADDRESS >= lowest_addr {
        (RAM_START_ADDRESS - lowest_addr) / 8
    } else {
        0
    };
    let ram_k_min = trace_max_remapped
        .max(bytecode_start_remapped + num_bc_words + 1)
        .max(io_end_remapped);
    (ram_k_min as usize).next_power_of_two()
}
