use jolt_lookup_tables::{LookupMaterializer, LookupTableKind};
use jolt_prover_legacy::zkvm::lookup_table::LookupTables;
use std::io::Write as _;
use strum::IntoEnumIterator as _;

use crate::{
    lookup_graph::LookupGraph,
    materializer_ast::{MaterializerAst, MaterializerGraph},
    modules::{AsModule, Module},
    DefaultMleAst,
};

const GENERATED_HEADER: &[u8] =
    b"/- This file is generated by zklean-extractor. Do not edit it directly. -/\n\n";

fn lookup_module(name: String, imports: Vec<String>, mut body: Vec<u8>) -> Module {
    while body.ends_with(b"\n\n") {
        body.pop();
    }
    let mut contents = GENERATED_HEADER.to_vec();
    contents.extend(b"namespace Jolt.LookupTables\n\n");
    contents.extend(body);
    contents.extend(b"\n\nend Jolt.LookupTables\n");
    Module {
        name,
        imports,
        contents,
    }
}

fn write_summary_tree(
    f: &mut impl std::io::Write,
    summaries: &[(u128, bool)],
    start: usize,
    indent: &str,
) -> std::io::Result<()> {
    if let [summary] = summaries {
        return writeln!(f, "{indent}⟨{}, {}⟩", summary.0, summary.1);
    }

    let left_len = summaries.len() / 2;
    let (left, right) = summaries.split_at(left_len);
    let split = start + left_len;
    writeln!(f, "{indent}if index < {split} then")?;
    write_summary_tree(f, left, start, &format!("{indent}  "))?;
    writeln!(f, "{indent}else")?;
    write_summary_tree(f, right, split, &format!("{indent}  "))
}

/// A modular lookup table together with its generated-name compatibility adapter.
// TODO: Can we tie the XLEN to the JoltParameterSet somehow? Seem hard w/o const generic
// exprs...
#[derive(Debug, Clone)]
pub struct ZkLeanLookupTable<const XLEN: usize> {
    pub lookup_table: LookupTableKind<XLEN>,
}

impl<const XLEN: usize> From<LookupTableKind<XLEN>> for ZkLeanLookupTable<XLEN> {
    fn from(value: LookupTableKind<XLEN>) -> Self {
        Self {
            lookup_table: value,
        }
    }
}

impl<const XLEN: usize> From<LookupTables<XLEN>> for ZkLeanLookupTable<XLEN> {
    fn from(value: LookupTables<XLEN>) -> Self {
        let index = LookupTables::enum_index(&value);
        Self::from(
            LookupTableKind::iter()
                .nth(index)
                .expect("legacy and modular lookup table catalogs must have matching ordinals"),
        )
    }
}

impl<const XLEN: usize> ZkLeanLookupTable<XLEN> {
    pub fn name(&self) -> String {
        let legacy_table = LookupTables::<XLEN>::iter()
            .nth(self.lookup_table.index())
            .expect("legacy and modular lookup table catalogs must have matching ordinals");
        let name = <&'static str>::from(&legacy_table);
        let word_size = XLEN;

        format!("{name}_{word_size}_lookup_table")
    }

    /// The stable public Lean name of this generated lookup evaluator.
    pub fn qualified_name(&self) -> String {
        format!("Jolt.LookupTables.{}", self.name())
    }

    pub fn evaluate_mle(&self) -> Result<DefaultMleAst, String> {
        let inputs = (0..2 * XLEN)
            .map(|index| {
                u16::try_from(index)
                    .map(DefaultMleAst::from_var)
                    .map_err(|_| format!("lookup input index {index} does not fit in MleAst"))
            })
            .collect::<Result<Vec<_>, _>>()?;

        Ok(self
            .lookup_table
            .evaluate_mle::<DefaultMleAst, DefaultMleAst>(&inputs))
    }

    pub fn iter() -> impl Iterator<Item = Self> {
        LookupTableKind::<XLEN>::iter().map(Self::from)
    }

    fn materializer(&self) -> Option<MaterializerGraph> {
        let mut backend = MaterializerAst::new(2 * XLEN);
        let root = match self.lookup_table {
            LookupTableKind::And(table) => Some(table.materialize(&mut backend)),
            LookupTableKind::VirtualROTR(table) => Some(table.materialize(&mut backend)),
            _ => None,
        }?;
        Some(backend.finish(root))
    }
}

/// One canonical extracted record for a modular lookup table.
struct ExtractedLookup {
    table_name: String,
    graph: LookupGraph,
    materializer: Option<MaterializerGraph>,
}

impl ExtractedLookup {
    fn extract<const XLEN: usize>(table: ZkLeanLookupTable<XLEN>) -> Result<Self, String> {
        let table_name = table.name();
        let num_inputs = 2 * XLEN;
        let graph = LookupGraph::from_mle_ast(&table.evaluate_mle()?, num_inputs)
            .map_err(|error| format!("failed to build {table_name}: {error}"))?;

        Ok(Self {
            table_name,
            graph,
            materializer: table.materializer(),
        })
    }

    /// Emit one graph-backed Lean lookup evaluator and its optional certificate data.
    fn zklean_pretty_print_base<const XLEN: usize>(
        &self,
        f: &mut impl std::io::Write,
    ) -> std::io::Result<()> {
        let table_name = &self.table_name;
        let graph_name = format!("{table_name}_graph");
        let num_inputs = 2 * XLEN;
        let graph_data = self
            .graph
            .format_for_lean()
            .map_err(std::io::Error::other)?;

        writeln!(
            f,
            "/-- Shared algebraic graph extracted from the Rust lookup evaluator. -/"
        )?;
        writeln!(
            f,
            "def {graph_name} : Jolt.LookupGraph.Graph {num_inputs} :="
        )?;
        writeln!(f, "  {graph_data}")?;
        writeln!(f)?;
        writeln!(
            f,
            "/-- Lean checks that every graph reference points backward and every input is in range. -/"
        )?;
        writeln!(
            f,
            "theorem {graph_name}_wellFormed : {graph_name}.WellFormed := by"
        )?;
        writeln!(f, "  set_option maxRecDepth 4096 in decide")?;
        writeln!(f)?;

        if let Some(materializer) = &self.materializer {
            self.zklean_pretty_print_certificate_base::<XLEN>(f, materializer)?;
        } else {
            writeln!(
                f,
                "def {table_name} [Field f] (point : Vector f {num_inputs}) : f :="
            )?;
            writeln!(f, "  {graph_name}.evalVector {graph_name}_wellFormed point")?;
            writeln!(f)?;
        }
        Ok(())
    }

    fn zklean_pretty_print_certificate_base<const XLEN: usize>(
        &self,
        f: &mut impl std::io::Write,
        materializer: &MaterializerGraph,
    ) -> std::io::Result<()> {
        let table_name = &self.table_name;
        let graph_name = format!("{table_name}_graph");
        let materializer_name = format!("{table_name}_materializer");
        let materializer_well_formed_name = format!("{materializer_name}_wellFormed");
        let correspondence_name = format!("{table_name}_correspondence");
        let program_name = format!("{table_name}_program");
        let num_inputs = 2 * XLEN;
        let materializer = materializer
            .format_for_lean()
            .map_err(std::io::Error::other)?;

        writeln!(
            f,
            "/-- Boolean materializer extracted from the same Rust lookup table. -/"
        )?;
        writeln!(
            f,
            "def {materializer_name} : Jolt.LookupExpression.MaterializerGraph {num_inputs} :="
        )?;
        writeln!(f, "  {materializer}")?;
        writeln!(f)?;

        writeln!(
            f,
            "/-- Lean checks that every materializer input is in range. -/"
        )?;
        writeln!(
            f,
            "theorem {materializer_well_formed_name} : {materializer_name}.WellFormed := by"
        )?;
        writeln!(f, "  set_option maxRecDepth 4096 in decide")?;
        writeln!(f)?;

        writeln!(
            f,
            "/-- The field evaluator and materializer extracted from shared Rust semantics. -/"
        )?;
        writeln!(
            f,
            "def {program_name} : Jolt.LookupExpression.LookupProgram {num_inputs} :="
        )?;
        writeln!(f, "  {{ mle := {graph_name}")?;
        writeln!(f, "    mleWellFormed := {graph_name}_wellFormed")?;
        writeln!(f, "    materializer := {materializer_name}")?;
        writeln!(
            f,
            "    materializerWellFormed := {materializer_well_formed_name}"
        )?;
        writeln!(f, "  }}")?;
        writeln!(f)?;

        writeln!(
            f,
            "/-- Lean checks that the extracted graph and materializer denote the same free polynomial. -/"
        )?;
        writeln!(
            f,
            "theorem {correspondence_name} : {program_name}.Corresponds := by"
        )?;
        writeln!(f, "  native_decide")?;
        writeln!(f)?;

        writeln!(
            f,
            "/-- Evaluate the extracted lookup polynomial on a field vector. -/"
        )?;
        writeln!(
            f,
            "def {table_name} [Field f] (point : Vector f {num_inputs}) : f :="
        )?;
        writeln!(f, "  {program_name}.evalVector point")?;
        writeln!(f)?;

        Ok(())
    }

    fn certificate_module_stem(&self) -> String {
        format!("LookupCertificate{}", self.table_name)
    }

    fn zklean_pretty_print_multilinearity_final<const XLEN: usize>(
        &self,
        f: &mut impl std::io::Write,
        oracle_name: &str,
        validation_names: &[String],
    ) -> std::io::Result<()> {
        let table_name = &self.table_name;
        let graph_name = format!("{table_name}_graph");
        let theorem_name = format!("{graph_name}_multilinear");
        let program_name = format!("{table_name}_program");
        let correspondence_name = format!("{table_name}_correspondence");
        let valid_name = format!("{oracle_name}_valid");
        let num_inputs = 2 * XLEN;

        writeln!(f, "set_option maxRecDepth 100000")?;
        writeln!(f)?;
        writeln!(
            f,
            "/-- Every graph node has the compact support summary claimed by the oracle. -/"
        )?;
        writeln!(
            f,
            "theorem {valid_name} : {graph_name}.ValidSummary {oracle_name} := by"
        )?;
        writeln!(f, "  unfold Jolt.LookupGraph.Graph.ValidSummary")?;
        writeln!(f, "  constructor")?;
        writeln!(f, "  · unfold {graph_name}")?;
        writeln!(f, "    simp only [Jolt.LookupGraph.ChunksValid]")?;
        writeln!(f, "    exact ⟨{}, trivial⟩", validation_names.join(", "))?;
        writeln!(f, "  · decide")?;
        writeln!(f)?;

        writeln!(
            f,
            "/-- The emitted graph is syntactically multilinear, checked one chunk at a time. -/"
        )?;
        writeln!(
            f,
            "theorem {theorem_name} : {graph_name}.checkMultilinear = true := by"
        )?;
        writeln!(
            f,
            "  rw [{graph_name}.checkMultilinear_eq_of_validSummary {oracle_name} {valid_name}]"
        )?;
        writeln!(f, "  rfl")?;
        writeln!(f)?;

        writeln!(
            f,
            "/-- The extracted evaluator is the multilinear extension of its materializer. -/"
        )?;
        writeln!(f, "theorem {table_name}_isLookupTableMLE [Field f] :")?;
        writeln!(f, "    Jolt.LookupExpression.IsLookupTableMLE")?;
        writeln!(
            f,
            "      (fun point : Fin {num_inputs} → f => {table_name} (Vector.ofFn point))"
        )?;
        writeln!(f, "      {program_name}.materializer.eval :=")?;
        writeln!(f, "  {program_name}.isLookupTableMLE (by")?;
        writeln!(f, "    change {graph_name}.checkMultilinear = true")?;
        writeln!(f, "    exact {theorem_name}) {correspondence_name}")?;

        Ok(())
    }

    fn certificate_modules<const XLEN: usize>(&self) -> std::io::Result<Vec<Module>> {
        if self.materializer.is_none() {
            return Ok(Vec::new());
        }

        let arity = 2 * XLEN;
        let graph_name = format!("{}_graph", self.table_name);
        let oracle_name = format!("{graph_name}_summary");
        let stem = self.certificate_module_stem();
        let base_name = format!("{stem}Base");
        let summaries = self
            .graph
            .multilinearity_summaries(arity)
            .map_err(std::io::Error::other)?;
        let chunks = self
            .graph
            .chunks_for_lean()
            .map_err(std::io::Error::other)?;
        if chunks.is_empty()
            || chunks.iter().map(|(length, _)| length).sum::<usize>() != summaries.len()
        {
            return Err(std::io::Error::other(
                "multilinearity summaries must match nonempty graph chunks",
            ));
        }
        if !summaries
            .get(self.graph.root_index())
            .is_some_and(|summary| summary.1)
        {
            return Err(std::io::Error::other(format!(
                "{} is not syntactically multilinear",
                self.table_name
            )));
        }

        let mut base_body = Vec::new();
        self.zklean_pretty_print_base::<XLEN>(&mut base_body)?;
        writeln!(base_body)?;
        writeln!(
            base_body,
            "/-- Compact support summary claimed for each graph node. -/"
        )?;
        writeln!(
            base_body,
            "def {oracle_name} (index : Nat) : Jolt.LookupGraph.ExprSummary {arity} :="
        )?;
        writeln!(base_body, "  if index < {} then", summaries.len())?;
        write_summary_tree(&mut base_body, &summaries, 0, "    ")?;
        writeln!(base_body, "  else")?;
        writeln!(base_body, "    ⟨0, false⟩")?;
        let mut modules = vec![lookup_module(
            base_name.clone(),
            vec![
                String::from("Jolt.LookupProgram"),
                String::from("Jolt.LookupGraphCertificate"),
                String::from("Mathlib.Algebra.Field.Defs"),
            ],
            base_body,
        )];

        let mut position = 0;
        let mut validation_names = Vec::with_capacity(chunks.len());
        let mut previous_module = base_name;
        for (index, (chunk_length, chunk)) in chunks.into_iter().enumerate() {
            let validation_name = format!("{oracle_name}_chunk_{index}_valid");
            let module_name = format!("{stem}Chunk{index}");
            let mut body = Vec::new();

            writeln!(body, "set_option maxHeartbeats 0")?;
            writeln!(body, "set_option maxRecDepth 4096")?;
            writeln!(
                body,
                "/-- Proof-producing summary validation for graph chunk {index}. -/"
            )?;
            writeln!(body, "theorem {validation_name} :")?;
            writeln!(
                body,
                "    Jolt.LookupGraph.NodesValid {oracle_name} {position} {chunk} := by"
            )?;
            writeln!(body, "  simp [Jolt.LookupGraph.NodesValid,")?;
            writeln!(body, "    Jolt.LookupGraph.Node.ValidSummaryAt,")?;
            writeln!(body, "    Jolt.LookupGraph.Node.wellFormedAt,")?;
            writeln!(body, "    Jolt.LookupGraph.Node.summaryFrom,")?;
            writeln!(body, "    {oracle_name}]")?;

            modules.push(lookup_module(
                module_name.clone(),
                vec![format!("Jolt.{previous_module}")],
                body,
            ));
            validation_names.push(validation_name);
            previous_module = module_name;
            position += chunk_length;
        }

        let final_name = stem;
        let mut final_body = Vec::new();
        self.zklean_pretty_print_multilinearity_final::<XLEN>(
            &mut final_body,
            &oracle_name,
            &validation_names,
        )?;
        modules.push(lookup_module(
            final_name,
            vec![format!("Jolt.{previous_module}")],
            final_body,
        ));

        Ok(modules)
    }
}

pub struct ZkLeanLookupTables<const XLEN: usize> {
    tables: Vec<ExtractedLookup>,
}

impl<const XLEN: usize> ZkLeanLookupTables<XLEN> {
    pub fn extract() -> Result<Self, String> {
        let tables = ZkLeanLookupTable::<XLEN>::iter()
            .map(ExtractedLookup::extract)
            .collect::<Result<_, _>>()?;
        Ok(Self { tables })
    }

    pub fn zklean_imports(&self) -> Vec<String> {
        vec![
            String::from("Jolt.LookupProgram"),
            String::from("Mathlib.Algebra.Field.Defs"),
        ]
    }

    pub fn as_modules(&self) -> std::io::Result<Vec<Module>> {
        let mut modules = Vec::new();
        let mut main_imports = self.zklean_imports();
        let mut main_body = Vec::new();

        for table in &self.tables {
            if table.materializer.is_some() {
                let certificate_modules = table.certificate_modules::<XLEN>()?;
                let final_module = certificate_modules
                    .last()
                    .ok_or_else(|| std::io::Error::other("missing lookup certificate module"))?;
                main_imports.push(format!("Jolt.{}", final_module.name));
                modules.extend(certificate_modules);
            } else {
                table.zklean_pretty_print_base::<XLEN>(&mut main_body)?;
            }
        }

        modules.push(lookup_module(
            String::from("LookupTables"),
            main_imports,
            main_body,
        ));
        Ok(modules)
    }
}

impl<const XLEN: usize> AsModule for ZkLeanLookupTables<XLEN> {
    fn as_module(&self) -> std::io::Result<Module> {
        self.as_modules()?
            .into_iter()
            .find(|module| module.name == "LookupTables")
            .ok_or_else(|| std::io::Error::other("missing canonical lookup module"))
    }
}

#[cfg(test)]
mod test {
    use std::collections::HashMap;

    use super::*;
    use crate::util::{arb_field_elem, Environment, ZkLeanReprField};

    use jolt_prover_legacy::field::JoltField;

    use proptest::{collection::vec, prelude::*};

    type RefField = ark_bn254::Fr;
    const XLEN: usize = 64;

    #[derive(Clone)]
    struct TestableLookupTable<const XLEN: usize> {
        reference: LookupTables<XLEN>,
        test: ZkLeanLookupTable<XLEN>,
    }

    impl<const XLEN: usize> std::fmt::Debug for TestableLookupTable<XLEN> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.write_fmt(format_args!("{}", self.test.name()))
        }
    }

    impl<const XLEN: usize> TestableLookupTable<XLEN> {
        fn iter() -> impl Iterator<Item = Self> {
            ZkLeanLookupTable::iter().map(|instr| Self {
                reference: LookupTables::<XLEN>::iter()
                    .nth(instr.lookup_table.index())
                    .expect("legacy and modular lookup table catalogs must have matching ordinals"),
                test: instr,
            })
        }

        fn evaluate_reference_mle<R: JoltField>(&self, inputs: &[R]) -> R {
            assert_eq!(inputs.len(), 2 * XLEN);

            self.reference.evaluate_mle(inputs)
        }

        fn evaluate_test_mle<R: JoltField>(&self, inputs: &[R]) -> (R, R) {
            assert_eq!(inputs.len(), 2 * XLEN);

            let ast = self.test.evaluate_mle().unwrap();
            let ast_value = ast.evaluate(&Environment {
                let_bindings: &HashMap::new(),
                vars: inputs,
            });
            let graph = LookupGraph::from_mle_ast(&ast, 2 * XLEN).unwrap();

            (ast_value, graph.evaluate(inputs))
        }
    }

    fn arb_instruction<const XLEN: usize>() -> impl Strategy<Value = TestableLookupTable<XLEN>> {
        let num_instrs = TestableLookupTable::<XLEN>::iter().count();

        (0..num_instrs).prop_map(|n| TestableLookupTable::iter().nth(n).unwrap())
    }

    fn arb_instruction_and_input<R: JoltField, const XLEN: usize>(
    ) -> impl Strategy<Value = (TestableLookupTable<XLEN>, Vec<R>)> {
        arb_instruction().prop_flat_map(|instr| {
            let input_len = 2 * XLEN;
            let inputs = vec(arb_field_elem::<R>(), input_len);

            (Just(instr), inputs)
        })
    }

    proptest! {
        #[test]
        fn evaluate_mle(
            (instr, inputs) in arb_instruction_and_input::<RefField, XLEN>(),
        ) {
            let reference = instr.evaluate_reference_mle(&inputs);
            let (ast, graph) = instr.evaluate_test_mle(&inputs);
            prop_assert_eq!(
                ast,
                reference,
            );
            prop_assert_eq!(graph, reference);
        }
    }

    #[test]
    fn extracted_graphs_preserve_lookup_sharing() {
        let mut total_nodes = 0;
        let mut largest = (String::new(), 0);

        for table in ZkLeanLookupTable::<XLEN>::iter() {
            let ast = table.evaluate_mle().unwrap();
            let graph = LookupGraph::from_mle_ast(&ast, 2 * XLEN).unwrap();
            total_nodes += graph.len();
            if graph.len() > largest.1 {
                largest = (table.name(), graph.len());
            }
        }

        eprintln!("lookup graph nodes: total={total_nodes}, largest={largest:?}");
        assert!(total_nodes < 20_000);
        assert!(largest.1 < 1_000);
    }

    #[test]
    fn shared_materializers_match_evaluator_graphs_structurally() {
        for table in [
            ZkLeanLookupTable::from(LookupTableKind::<XLEN>::And(Default::default())),
            ZkLeanLookupTable::from(LookupTableKind::<XLEN>::VirtualROTR(Default::default())),
        ] {
            let evaluator =
                LookupGraph::from_mle_ast(&table.evaluate_mle().unwrap(), 2 * XLEN).unwrap();
            let materializer_ast = table.materializer().unwrap().to_mle_ast();
            let materializer = LookupGraph::from_mle_ast(&materializer_ast, 2 * XLEN).unwrap();

            assert!(
                evaluator.structurally_equivalent(&materializer),
                "{}",
                table.name()
            );
        }
    }

    #[test]
    fn emits_all_lookups_through_one_canonical_module() {
        let lookups = ZkLeanLookupTables::<XLEN>::extract().unwrap();
        let modules = lookups.as_modules().unwrap();
        let module = modules
            .iter()
            .find(|module| module.name == "LookupTables")
            .unwrap();
        let lean = modules
            .iter()
            .map(|module| String::from_utf8(module.contents.clone()).unwrap())
            .collect::<String>();

        assert_eq!(module.name, "LookupTables");
        assert!(String::from_utf8(module.contents.clone()).unwrap().starts_with(
            "/- This file is generated by zklean-extractor. Do not edit it directly. -/\n\nnamespace Jolt.LookupTables\n\n"
        ));
        assert!(String::from_utf8(module.contents.clone())
            .unwrap()
            .ends_with("\nend Jolt.LookupTables\n"));
        assert!(lean.contains("And_64_lookup_table_program"));
        assert!(lean.contains("And_64_lookup_table_graph"));
        assert!(lean.contains("mle := And_64_lookup_table_graph"));
        assert!(lean.contains("And_64_lookup_table_materializer"));
        assert!(lean.contains("And_64_lookup_table_correspondence"));
        assert!(lean.contains("VirtualROTR_64_lookup_table_program"));
        assert!(lean.contains("VirtualROTR_64_lookup_table_materializer"));
        assert!(lean.contains("VirtualROTR_64_lookup_table_correspondence"));
        assert!(lean.contains(".Corresponds := by"));
        assert_eq!(lean.matches("native_decide").count(), 2);
        assert!(lean.contains("And_64_lookup_table_graph_summary_chunk_0_valid"));
        assert!(lean.contains("VirtualROTR_64_lookup_table_graph_multilinear"));
        assert!(!lean.contains(".isLookupTableMLE (by native_decide)"));
        assert!(lean.contains("Xor_64_lookup_table_graph"));
        assert!(!module.contents.ends_with(b"\n\n"));
    }
}
