//! The prover-owned generated stage driver.
//!
//! [`StageProver`] is the driver trait, implemented for each stage batch
//! struct by `impl_stage_prover!`, expanded from the batch's
//! derive-emitted member-list callback macro (`jolt-verifier`'s
//! `<snake_case_struct>_members!`), so no stage's member list, order, or
//! presence is ever restated on the prove side. One recorder-generic
//! [`prove`](StageProver::prove) runs the whole body: `begin_batch` (the
//! generated shared head) → per-member kernel `prepare` in declaration order
//! (through the per-member [`PrepareKernel`] bounds on the kernel source) →
//! the engine round loop → derived opening points → per-member
//! `validate_derived_tables` → typed extraction into the stage's
//! `OutputClaims` aggregate → per-member `park_residue` (cross-batch residues
//! into the session; consumes the kernels, so it follows the borrowing
//! extraction) → [`curate_opening_values`](StageAggregates::curate_opening_values)
//! (default: the derive-generated canonical absorb order; curated stages
//! override at the invocation site) → shape validation → the
//! `expected_final_claim` hard self-check → `recorder.finish`. The recorder
//! is the clear/ZK seam, exactly as in `begin_batch`: no `prove_clear`/
//! `prove_zk` split exists to drift.
//!
//! See `specs/prover-stage-drivers.md`.

#[cfg(feature = "allocative")]
use allocative::FlameGraphBuilder;
use jolt_claims::SymbolicSumcheck;
use jolt_field::JoltField;
use jolt_kernels::{
    PrepareKernel, ProofSession, ProverInputs, SumcheckKernel, SumcheckKernelError, WitnessPlane,
};
use jolt_poly::UnivariatePoly;
use jolt_sumcheck::{
    ProveRounds, RecordedSumcheck, RoundScheduler, SumcheckError, SumcheckRecorder,
};
use jolt_transcript::Transcript;
use jolt_verifier::stages::relations::{
    ConcreteSumcheck, ConcreteSumcheckChallenges, SumcheckInputClaims, SumcheckInputPoints,
    SumcheckOutputClaims, SumcheckOutputPoints,
};
use jolt_verifier::VerifierError;

use crate::ProverError;

/// The typed aggregates and witness plane of a stage batch, generated by
/// [`impl_stage_prover!`]. `Kernels` contains one boxed kernel per member,
/// `Option`-wrapped for conditional members, in declaration order.
pub trait StageAggregates<F: JoltField>: Sized {
    type Plane: WitnessPlane<F>;
    type InputClaims;
    type InputPoints;
    type Challenges;
    type OutputClaims;
    type OutputPoints;
    type Kernels;

    /// Opening scalars in the stage's absorb order. The generated default
    /// uses canonical order; curated stages supply an invocation-site override.
    fn curate_opening_values(
        &self,
        claims: &Self::OutputClaims,
        points: &Self::OutputPoints,
    ) -> Result<Vec<F>, ProverError<F>>;
}

/// The generated driver for a stage and a kernel source implementing
/// [`PrepareKernel`] for every member with the stage's witness plane.
pub trait StageProver<F: JoltField, B: ?Sized>: StageAggregates<F> {
    /// Prove on `transcript`; the recorder type selects clear or committed
    /// recording. The returned final claim is checked against the member outputs.
    #[expect(
        clippy::too_many_arguments,
        reason = "the driver's fixed protocol signature: upstream carriers in, recorded proof out"
    )]
    fn prove<Rec, T>(
        &self,
        kernels: &B,
        session: &mut ProofSession,
        scheduler: &mut dyn RoundScheduler<F>,
        witness: <Self::Plane as WitnessPlane<F>>::Ref<'_>,
        inputs: &Self::InputClaims,
        input_points: &Self::InputPoints,
        challenges: &Self::Challenges,
        recorder: Rec,
        transcript: &mut T,
    ) -> Result<Proved<F, Self, Rec::Commitment>, ProverError<F>>
    where
        Rec: SumcheckRecorder<F>,
        T: Transcript<Challenge = F>;
}

/// A proved stage batch, as assembled by the generated
/// [`prove`](StageProver::prove): the recorded wire proof (plus retained
/// witness for a committed recorder), the typed output claims and derived
/// opening points, and the batch's final running claim (already hard-checked
/// against the generated `expected_final_claim`).
pub struct Proved<F: JoltField, S: StageAggregates<F>, C> {
    pub recorded: RecordedSumcheck<F, C>,
    pub output_claims: S::OutputClaims,
    pub output_points: S::OutputPoints,
    pub final_claim: F,
}

/// Instrumentation-only [`ProveRounds`] shim: the generated driver wraps
/// each member's kernel so every `prove_round` call runs inside a fresh
/// tracing span named `<Relation>::prove_round` and the terminal
/// `finish_rounds` call inside `<Relation>::finish_rounds`, attributing the
/// engine's batched round-loop time per member in a Perfetto timeline
/// (`finish_rounds` nests directly under `prove_batch` rather than a
/// `sumcheck_round`, so the distinct label keeps the per-label buckets
/// self-describing). The delegation is transparent — zero behavior change;
/// the driver reaches the kernel itself through [`inner`](Self::inner) for
/// extraction and parking.
pub struct SpannedRounds<K, SR, SF> {
    pub inner: K,
    pub round_span: SR,
    pub finish_span: SF,
}

impl<F, K, SR, SF> ProveRounds<F> for SpannedRounds<Box<K>, SR, SF>
where
    F: JoltField,
    K: ProveRounds<F> + ?Sized,
    SR: Fn() -> tracing::Span,
    SF: Fn() -> tracing::Span,
{
    fn num_rounds(&self) -> usize {
        self.inner.num_rounds()
    }

    fn prove_round(
        &mut self,
        bind: Option<F>,
        round: usize,
        previous_claim: F,
    ) -> Result<UnivariatePoly<F>, SumcheckError<F>> {
        let _guard = (self.round_span)().entered();
        self.inner.prove_round(bind, round, previous_claim)
    }

    fn finish_rounds(&mut self, bind: F) -> Result<(), SumcheckError<F>> {
        let _guard = (self.finish_span)().entered();
        self.inner.finish_rounds(bind)
    }
}

/// One heap snapshot per driver batch, taken right after member preparation
/// — every member kernel alive with its tables materialized, the stage's
/// retained-memory peak (end-of-stage snapshots see only what survives the
/// batch) — written to `{prefix}{label}.folded`. Inert unless the profile
/// harness opted in via `jolt_profiling::set_flamegraph_prefix`. The proof
/// session rides along so mid-stage carries are attributed too.
#[cfg(feature = "allocative")]
pub fn mid_stage_flamegraph(
    label: &str,
    session: &ProofSession,
    visit_members: impl FnOnce(&mut FlameGraphBuilder),
) {
    jolt_profiling::capture_heap_snapshot(label, |snapshot| {
        snapshot.visit_root(session);
        visit_members(snapshot);
    });
}

/// Mint one required member's kernel through the source's [`PrepareKernel`]
/// slot.
pub fn prepare_required<F, R, P, B>(
    kernels: &B,
    relation: &R,
    session: &mut ProofSession,
    witness: P::Ref<'_>,
    claims: &SumcheckInputClaims<F, R>,
    points: &SumcheckInputPoints<F, R>,
    challenges: &ConcreteSumcheckChallenges<F, R>,
) -> Result<Box<dyn SumcheckKernel<F, Relation = R>>, ProverError<F>>
where
    F: JoltField,
    R: ConcreteSumcheck<F>,
    P: WitnessPlane<F>,
    B: PrepareKernel<F, R, P> + ?Sized,
{
    Ok(kernels.prepare(
        session,
        witness,
        ProverInputs {
            relation,
            claims,
            points,
            challenges,
        },
    )?)
}

/// Mint one `Option` member's kernel when present. Presence must agree across
/// the relation and every cell: a present instance missing an input, point,
/// or challenge cell — or an absent instance with any cell populated — is a
/// wiring bug, attributed to the member's relation id; silently dropping
/// either side would desynchronize the batch.
#[expect(
    clippy::type_complexity,
    reason = "the conditional member's Option-wrapped cell and boxed-kernel types, spelled in full"
)]
pub fn prepare_optional<F, R, P, B>(
    kernels: &B,
    relation: Option<&R>,
    session: &mut ProofSession,
    witness: P::Ref<'_>,
    claims: Option<&SumcheckInputClaims<F, R>>,
    points: Option<&SumcheckInputPoints<F, R>>,
    challenges: Option<&ConcreteSumcheckChallenges<F, R>>,
) -> Result<Option<Box<dyn SumcheckKernel<F, Relation = R>>>, ProverError<F>>
where
    F: JoltField,
    R: ConcreteSumcheck<F>,
    P: WitnessPlane<F>,
    B: PrepareKernel<F, R, P> + ?Sized,
{
    match (relation, claims, points, challenges) {
        (Some(relation), Some(claims), Some(points), Some(challenges)) => {
            Ok(Some(prepare_required::<F, R, P, B>(
                kernels, relation, session, witness, claims, points, challenges,
            )?))
        }
        (None, None, None, None) => Ok(None),
        (Some(relation), _, _, _) => Err(VerifierError::StageClaimSumcheckFailed {
            stage: format!("{:?}", relation.id()),
            reason: "present instance is missing an input, point, or challenge cell for prepare"
                .to_string(),
        }
        .into()),
        (None, _, _, _) => Err(VerifierError::StageClaimSumcheckFailed {
            stage: format!("{:?}", R::Symbolic::id()),
            reason: "absent instance has a populated input, point, or challenge cell for prepare"
                .to_string(),
        }
        .into()),
    }
}

/// Cross-check one `Option` member's hand-materialized derived tables when
/// every cell is present (the presence invariants were enforced at prepare).
pub fn validate_optional_tables<F, R>(
    kernel: Option<&dyn SumcheckKernel<F, Relation = R>>,
    relation: Option<&R>,
    input_points: Option<&SumcheckInputPoints<F, R>>,
    output_points: Option<&SumcheckOutputPoints<F, R>>,
    challenges: Option<&ConcreteSumcheckChallenges<F, R>>,
) -> Result<(), SumcheckKernelError<F>>
where
    F: JoltField,
    R: ConcreteSumcheck<F>,
{
    if let (
        Some(kernel),
        Some(relation),
        Some(input_points),
        Some(output_points),
        Some(challenges),
    ) = (kernel, relation, input_points, output_points, challenges)
    {
        kernel.validate_derived_tables(relation, input_points, output_points, challenges)?;
    }
    Ok(())
}

/// Extract one `Option` member's typed output claims when present. The
/// member's consumed claims ride along for the kernel's dual-role resolution;
/// presence agreement between kernel and cells was enforced at prepare, so a
/// present kernel with an absent input cell is a driver bug.
pub fn extract_optional<F, R>(
    kernel: Option<&mut (dyn SumcheckKernel<F, Relation = R> + '_)>,
    inputs: Option<&SumcheckInputClaims<F, R>>,
) -> Result<Option<SumcheckOutputClaims<F, R>>, SumcheckKernelError<F>>
where
    F: JoltField,
    R: ConcreteSumcheck<F>,
{
    match (kernel, inputs) {
        (Some(kernel), Some(inputs)) => kernel.output_claims(inputs).map(Some),
        (None, _) => Ok(None),
        (Some(_), None) => Err(SumcheckKernelError::InvariantViolation {
            reason: "present kernel has no input-claims cell at extraction",
        }),
    }
}

/// One member slot of the generated driver body, dispatched on the member's
/// presence: the kernel-bundle tuple element type, the prepare expression,
/// the round-loop push, the derived-table cross-check, and the typed
/// extraction. Internal to [`impl_stage_prover!`]; every local it touches is
/// passed in by name (macro hygiene).
#[doc(hidden)]
#[macro_export]
macro_rules! __stage_member {
    (kernel_ty required $relation:ident) => {
        ::std::boxed::Box<dyn ::jolt_kernels::SumcheckKernel<F, Relation = $relation<F>>>
    };
    (kernel_ty optional $relation:ident) => {
        ::core::option::Option<
            ::std::boxed::Box<dyn ::jolt_kernels::SumcheckKernel<F, Relation = $relation<F>>>,
        >
    };
    (prepare required $member:ident, $relation:ident, $plane:ty, $source:expr, $batch:expr, $session:expr, $witness:expr, $inputs:expr, $points:expr, $challenges:expr) => {
        ::tracing::info_span!(concat!(stringify!($relation), "::prepare")).in_scope(|| {
            $crate::driver::prepare_required::<F, $relation<F>, $plane, _>(
                $source,
                &$batch.$member,
                $session,
                $witness,
                &$inputs.$member,
                &$points.$member,
                &$challenges.$member,
            )
        })?
    };
    (prepare optional $member:ident, $relation:ident, $plane:ty, $source:expr, $batch:expr, $session:expr, $witness:expr, $inputs:expr, $points:expr, $challenges:expr) => {
        ::tracing::info_span!(concat!(stringify!($relation), "::prepare")).in_scope(|| {
            $crate::driver::prepare_optional::<F, $relation<F>, $plane, _>(
                $source,
                $batch.$member.as_ref(),
                $session,
                $witness,
                $inputs.$member.as_ref(),
                $points.$member.as_ref(),
                $challenges.$member.as_ref(),
            )
        })?
    };
    // Rebind the member's kernel inside the instrumentation-only
    // [`SpannedRounds`](crate::driver::SpannedRounds) shim; later arms reach
    // the kernel through `.inner`.
    (spanned required $member:ident, $relation:ident) => {
        let mut $member = $crate::driver::SpannedRounds {
            inner: $member,
            round_span: || ::tracing::info_span!(concat!(stringify!($relation), "::prove_round")),
            finish_span: || {
                ::tracing::info_span!(concat!(stringify!($relation), "::finish_rounds"))
            },
        };
    };
    (spanned optional $member:ident, $relation:ident) => {
        let mut $member = $member.map(|__kernel| $crate::driver::SpannedRounds {
            inner: __kernel,
            round_span: || ::tracing::info_span!(concat!(stringify!($relation), "::prove_round")),
            finish_span: || {
                ::tracing::info_span!(concat!(stringify!($relation), "::finish_rounds"))
            },
        });
    };
    (round_slot required $member:ident) => {
        ::core::option::Option::Some(&mut $member as &mut dyn ::jolt_sumcheck::ProveRounds<F>)
    };
    (round_slot optional $member:ident) => {
        $member
            .as_mut()
            .map(|__kernel| __kernel as &mut dyn ::jolt_sumcheck::ProveRounds<F>)
    };
    (validate required $member:ident, $self:expr, $input_points:expr, $output_points:expr, $challenges:expr) => {
        $member.inner.validate_derived_tables(
            &$self.$member,
            &$input_points.$member,
            &$output_points.$member,
            &$challenges.$member,
        )?;
    };
    (validate optional $member:ident, $self:expr, $input_points:expr, $output_points:expr, $challenges:expr) => {
        $crate::driver::validate_optional_tables(
            $member.as_ref().map(|__kernel| &*__kernel.inner),
            $self.$member.as_ref(),
            $input_points.$member.as_ref(),
            $output_points.$member.as_ref(),
            $challenges.$member.as_ref(),
        )?;
    };
    (extract required $member:ident, $inputs:expr) => {
        $member.inner.output_claims(&$inputs.$member)?
    };
    (extract optional $member:ident, $inputs:expr) => {
        $crate::driver::extract_optional(
            $member.as_mut().map(|__kernel| &mut *__kernel.inner),
            $inputs.$member.as_ref(),
        )?
    };
    (park required $member:ident, $session:expr) => {
        ::jolt_kernels::SumcheckKernel::park_residue($member.inner, $session);
    };
    (park optional $member:ident, $session:expr) => {
        if let ::core::option::Option::Some(__kernel) = $member {
            ::jolt_kernels::SumcheckKernel::park_residue(__kernel.inner, $session);
        }
    };
}

/// Heap instrumentation uses the defining crate's feature selection.
#[cfg(feature = "allocative")]
#[doc(hidden)]
#[macro_export]
macro_rules! __stage_flame {
    ($label:expr, $session:expr, [$($presence:ident $member:ident),+]) => {
        $crate::driver::mid_stage_flamegraph($label, $session, |__fg| {
            $($crate::__stage_flame!(flame $presence $member, __fg);)+
        });
    };
    (flame required $member:ident, $fg:ident) => {
        $fg.visit_root(&*$member.inner);
    };
    (flame optional $member:ident, $fg:ident) => {
        if let ::core::option::Option::Some(__kernel) = $member.as_ref() {
            $fg.visit_root(&*__kernel.inner);
        }
    };
}

#[cfg(not(feature = "allocative"))]
#[doc(hidden)]
#[macro_export]
macro_rules! __stage_flame {
    ($($tokens:tt)*) => {};
}

/// The output-shape leg of the generated driver, keyed by the derive-emitted
/// flag: `checked` runs the generated `validate_output_claims`; `unchecked`
/// (a `no_output_shape` stage, whose wire shape is runtime-curated) has no
/// validator to run.
#[doc(hidden)]
#[macro_export]
macro_rules! __stage_shape_check {
    (checked, $self:expr, $claims:expr) => {
        $self.validate_output_claims(&$claims)?;
    };
    (unchecked, $self:expr, $claims:expr) => {};
}

/// Expand a stage's [`StageAggregates`] and [`StageProver`] implementations
/// from its derive-emitted member-list callback. `plane = Type,` precedes
/// `curate = |batch, claims, points| { .. },`; both are optional. The defaults
/// are [`jolt_kernels::JoltPlane`] and canonical opening order.
///
/// The expanding crate needs direct dependencies under their own names on
/// `jolt-prover`, `jolt-field`, `jolt-kernels`, `jolt-sumcheck`, `jolt-transcript`,
/// `jolt-verifier`, and `tracing`. The batch, aggregate and relation names must
/// be in scope by bare name. The batch and relations are generic in exactly
/// one parameter `F: JoltField`, and the plane implements `WitnessPlane<F>`
/// for every `F: JoltField`.
///
/// Declaring a family also needs `jolt-claims` for the claim derives and
/// `serde` for `SumcheckBatch`'s output aggregate. Tables for
/// `NaiveSumcheckProver` need `jolt-poly`. If that crate declares an `allocative`
/// feature, it needs `allocative` and `Allocative` on its member claim structs:
/// the batch derive selects that feature at its expansion site. Stage-driver
/// heap instrumentation instead uses `jolt-prover`'s feature selection.
///
/// ```ignore
/// toy_sumchecks_members!(impl_stage_prover plane = ToyPlane,);
/// ```
#[macro_export]
macro_rules! impl_stage_prover {
    (batch = $($rest:tt)*) => {
        $crate::impl_stage_prover! { plane = ::jolt_kernels::JoltPlane, batch = $($rest)* }
    };
    (curate = $($rest:tt)*) => {
        $crate::impl_stage_prover! { plane = ::jolt_kernels::JoltPlane, curate = $($rest)* }
    };
    (plane = $plane:ty, batch = $($rest:tt)*) => {
        $crate::impl_stage_prover! {
            plane = $plane,
            curate = |__batch, __claims, __points| {
                ::core::result::Result::Ok(__batch.opening_values(__claims))
            },
            batch = $($rest)*
        }
    };
    (
        plane = $plane:ty,
        curate = |$curate_batch:ident, $curate_claims:ident, $curate_points:ident| $curate_body:block,
        batch = $batch:ident,
        label = $label:literal,
        aggregates = {
            input_claims = $input_claims:ident,
            input_points = $input_points:ident,
            output_claims = $output_claims:ident,
            output_points = $output_points:ident,
            challenges = $challenges_ty:ident,
        },
        shape = $shape:ident,
        members = [
            $({ name: $member:ident, relation: $relation:ident, presence: $presence:ident },)+
        ]
    ) => {
        impl<F: ::jolt_field::JoltField> $crate::driver::StageAggregates<F> for $batch<F> {
            type Plane = $plane;
            type InputClaims = $input_claims<F>;
            type InputPoints = $input_points<F>;
            type Challenges = $challenges_ty<F>;
            type OutputClaims = $output_claims<F>;
            type OutputPoints = $output_points<F>;
            type Kernels = ( $($crate::__stage_member!(kernel_ty $presence $relation),)+ );

            fn curate_opening_values(
                &self,
                $curate_claims: &Self::OutputClaims,
                $curate_points: &Self::OutputPoints,
            ) -> ::core::result::Result<::std::vec::Vec<F>, $crate::ProverError<F>> {
                let $curate_batch = self;
                let _ = ($curate_batch, $curate_points);
                $curate_body
            }
        }

        impl<F: ::jolt_field::JoltField, B> $crate::driver::StageProver<F, B> for $batch<F>
        where
            B: ?Sized $(+ ::jolt_kernels::PrepareKernel<F, $relation<F>, $plane>)+,
        {
            fn prove<Rec, T>(
                &self,
                kernels: &B,
                session: &mut ::jolt_kernels::ProofSession,
                scheduler: &mut dyn ::jolt_sumcheck::RoundScheduler<F>,
                witness: <$plane as ::jolt_kernels::WitnessPlane<F>>::Ref<'_>,
                inputs: &Self::InputClaims,
                input_points: &Self::InputPoints,
                challenges: &Self::Challenges,
                mut recorder: Rec,
                transcript: &mut T,
            ) -> ::core::result::Result<
                $crate::driver::Proved<F, Self, Rec::Commitment>,
                $crate::ProverError<F>,
            >
            where
                Rec: ::jolt_sumcheck::SumcheckRecorder<F>,
                T: ::jolt_transcript::Transcript<Challenge = F>,
            {
                let __stage_span =
                    ::tracing::info_span!(concat!($label, "::prove")).entered();
                let (__batch, __coefficients) =
                    self.begin_batch(inputs, challenges, &mut recorder, transcript)?;

                let ($($member,)+) = ($(
                    $crate::__stage_member!(
                        prepare $presence $member, $relation, $plane, kernels, self, session, witness,
                        inputs, input_points, challenges
                    ),
                )+);
                $($crate::__stage_member!(spanned $presence $member, $relation);)+

                $crate::__stage_flame!(
                    concat!($label, "_prepared"), session, [$($presence $member),+]
                );

                let mut __rounds: ::std::vec::Vec<&mut dyn ::jolt_sumcheck::ProveRounds<F>> =
                    [$($crate::__stage_member!(round_slot $presence $member),)+]
                        .into_iter()
                        .flatten()
                        .collect();
                let __proved = ::jolt_sumcheck::prove_batch(
                    &__batch,
                    &mut __rounds,
                    scheduler,
                    &mut recorder,
                    transcript,
                )?;

                let __output_points =
                    self.derive_opening_points(&__proved.challenges, input_points)?;
                $($crate::__stage_member!(
                    validate $presence $member, self, input_points, __output_points, challenges
                );)+

                let __output_claims = $output_claims {
                    $($member: $crate::__stage_member!(extract $presence $member, inputs),)+
                };
                $($crate::__stage_member!(park $presence $member, session);)+

                let __opening_values =
                    $crate::driver::StageAggregates::curate_opening_values(
                        self, &__output_claims, &__output_points
                    )?;
                $crate::__stage_shape_check!($shape, self, __output_claims);

                let __expected = self.expected_final_claim(
                    &__batch,
                    &__proved.challenges,
                    &__coefficients,
                    input_points,
                    &__output_claims,
                    &__output_points,
                    challenges,
                )?;
                if __expected != __proved.final_claim {
                    return ::core::result::Result::Err(
                        ::jolt_verifier::VerifierError::StageClaimSumcheckFailed {
                            stage: $label.to_string(),
                            reason: ::std::format!(
                                "prover final claim {:?} disagrees with the expected output fold {:?}",
                                __proved.final_claim,
                                __expected,
                            ),
                        }
                        .into(),
                    );
                }

                let __recorded = recorder.finish(&__opening_values, transcript)?;
                ::core::result::Result::Ok($crate::driver::Proved {
                    recorded: __recorded,
                    output_claims: __output_claims,
                    output_points: __output_points,
                    final_claim: __proved.final_claim,
                })
            }
        }
    };
}

pub use crate::impl_stage_prover;

#[cfg(test)]
#[expect(clippy::unwrap_used)]
mod tests {
    #[test]
    fn stage_macro_bodies_have_no_expansion_site_feature_gates() {
        let source = include_str!("driver.rs");
        for (name, definitions) in [
            ("impl_stage_prover", 1),
            ("__stage_member", 1),
            ("__stage_shape_check", 1),
            ("__stage_flame", 2),
        ] {
            let marker = format!("macro_rules! {name} {{");
            let mut found = 0;
            for (start, _) in source.match_indices(&marker) {
                let body_start = start + marker.len();
                let mut depth = 1;
                let end = source[body_start..]
                    .char_indices()
                    .find_map(|(offset, ch)| {
                        match ch {
                            '{' => depth += 1,
                            '}' => depth -= 1,
                            _ => {}
                        }
                        (depth == 0).then_some(body_start + offset)
                    })
                    .unwrap();
                let body = &source[body_start..end];
                assert!(!body.contains("cfg("), "feature gate in {name}");
                assert!(!body.contains("cfg_attr("), "feature attribute in {name}");
                found += 1;
            }
            assert_eq!(found, definitions, "missing macro definition for {name}");
        }
    }
}
