// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;
// Generated by test/compile-modules.mjs from reviewed deployed module bytecode.
library SpartanModulePolicy {
    bytes32 internal constant DECODE=hex"c595d60f68f322a4bab542c96a5982df80a464a029516e53fb33e4df180ee294";
    bytes32 internal constant PREFIX=hex"6122b6029906dfbb0f4d023561cdcce899549321e6320eb2dbd1aeaa20f716d6";
    bytes32 internal constant SPARSE=hex"5009f5f9acd52faa5f3bd950e9639404190787ba18de339fe82ff4f71ec8d7d3";
    bytes32 internal constant LEAF=hex"5c15c80de25ff4806ab2027fefdc1dd525e001ce9d85255d2a3a874012368684";
}
