// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;
// Generated by test/compile-modules.mjs from reviewed deployed module bytecode.
library SpartanModulePolicy {
    bytes32 internal constant DECODE=hex"3a78cfce520ea0d26df63b5bd54c40e0e1c838e92745457acc2adeab255aec40";
    bytes32 internal constant PREFIX=hex"acfbd7b1b5d57d9959a5fcdc4746d39064c7ff05220ce52fcfafda40c80a57cd";
    bytes32 internal constant SPARSE=hex"145ca2c5e6393da3fd20f260be5954b337430fa8e12142920d6196fa9667554a";
    bytes32 internal constant LEAF=hex"5378fd2a74499f9fc910872ccbc4d071e022bfe3d9c825c40d455d901a4e63d5";
}
