//! Exit functionality for Jolt guests
//!
//! Provides clean program termination that the Jolt emulator can detect,
//! and panic/abort handling for ZeroOS integration.

cfg_if::cfg_if! {
    if #[cfg(any(target_os = "linux", target_os = "none"))] {
        extern "C" {
            /// Set the panic bit in the I/O region.
            /// This function is generated by the `#[jolt::provable]` macro.
            fn jolt_panic();
        }

        /// Exit the program.
        ///
        /// Enters an infinite loop (`j .`) which the Jolt emulator detects via PC stall
        /// (prev_pc == pc) and treats as clean termination.
        #[no_mangle]
        pub extern "C" fn __platform_exit(_code: i32) -> ! {
            unsafe {
                core::arch::asm!("j .", options(noreturn));
            }
        }

        /// Platform-specific abort handler for signal-based panic detection.
        ///
        /// Called by ZeroOS signal handler when a fatal signal is received (e.g., SIGABRT
        /// from musl's abort()), or by zeroos-runtime-nostd's panic handler.
        /// Sets the panic bit and terminates with Linux-standard exit code (128 + sig).
        ///
        /// # Arguments
        /// * `sig` - The signal number that caused the abort (e.g., SIGABRT=6)
        #[no_mangle]
        pub extern "C" fn __platform_abort(sig: i32) -> ! {
            unsafe {
                // Set panic bit so jolt-core knows a panic occurred
                jolt_panic();
                // Terminate with Linux signal exit code convention: 128 + signal_number
                __platform_exit(128 + sig);
            }
        }
    }
}
