//! Jolt's RISC-V instruction kinds and the flag types that describe them.
//!
//! Each unit struct in [`instructions`] represents one instruction kind (real
//! RV64I/M opcode or virtual sequence helper). [`Flags`] exposes its static
//! R1CS circuit flags ([`CircuitFlagSet`]) and witness-generation flags
//! ([`InstructionFlagSet`]); per-instruction impls are generated by the
//! `Flags` derive macro in `jolt-riscv-derive`.

mod flags;
pub mod instructions;
mod jolt_instruction;

pub use flags::{
    CircuitFlagSet, CircuitFlags, Flags, InstructionFlagSet, InstructionFlags,
    InterleavedBitsMarker, NUM_CIRCUIT_FLAGS, NUM_INSTRUCTION_FLAGS,
};
pub use instructions::JoltInstructions;
pub use jolt_instruction::JoltInstruction;

/// Declares a Jolt RISC-V instruction kind and (optionally) its `Flags` impl.
///
/// Two forms:
///
/// ```ignore
/// // With circuit + instruction flag config — emits a `Flags` impl:
/// jolt_instruction!(
///     /// RV64I ADD: `rd = rs1 + rs2` (wrapping).
///     Add,
///     circuit flags: [AddOperands, WriteLookupOutputToRD],
///     instruction flags: [LeftOperandIsRs1Value, RightOperandIsRs2Value]
/// );
///
/// // No flag config — struct only, no `Flags` impl:
/// jolt_instruction!(
///     /// RV32I (Zicsr) CSRRS: atomic CSR read+set bits.
///     Csrrs
/// );
/// ```
#[macro_export]
macro_rules! jolt_instruction {
    (
        $(#[$attr:meta])*
        $name:ident,
        circuit flags: [$($circuit:ident),* $(,)?],
        instruction flags: [$($instruction:ident),* $(,)?] $(,)?
    ) => {
        $crate::jolt_instruction!(@struct $(#[$attr])* $name);

        impl<T: $crate::JoltInstruction> $crate::Flags for $name<T> {
            #[inline]
            fn circuit_flags(&self) -> $crate::CircuitFlagSet {
                let mut flags = $crate::CircuitFlagSet::default()
                    $(.set($crate::CircuitFlags::$circuit))*;
                let virtual_sequence_remaining = self.0.virtual_sequence_remaining();
                if virtual_sequence_remaining.is_some() {
                    flags = flags.set($crate::CircuitFlags::VirtualInstruction);
                    $crate::jolt_instruction!(@set_is_last_in_sequence flags, $name, virtual_sequence_remaining);
                }
                if virtual_sequence_remaining.unwrap_or(0) != 0 {
                    flags = flags.set($crate::CircuitFlags::DoNotUpdateUnexpandedPC);
                }
                if self.0.is_compressed() {
                    flags = flags.set($crate::CircuitFlags::IsCompressed);
                }
                if self.0.is_first_in_sequence() {
                    flags = flags.set($crate::CircuitFlags::IsFirstInSequence);
                }
                flags
            }

            #[inline]
            fn instruction_flags(&self) -> $crate::InstructionFlagSet {
                $crate::InstructionFlagSet::default()
                    $(.set($crate::InstructionFlags::$instruction))*
            }
        }

        $crate::jolt_instruction!(@jolt_instruction_impl $name);
    };

    (
        $(#[$attr:meta])*
        $name:ident $(,)?
    ) => {
        $crate::jolt_instruction!(@struct $(#[$attr])* $name);

        impl<T: $crate::JoltInstruction> $crate::Flags for $name<T> {
            #[inline]
            fn circuit_flags(&self) -> $crate::CircuitFlagSet {
                let mut flags = $crate::CircuitFlagSet::default();
                let virtual_sequence_remaining = self.0.virtual_sequence_remaining();
                if virtual_sequence_remaining.is_some() {
                    flags = flags.set($crate::CircuitFlags::VirtualInstruction);
                    $crate::jolt_instruction!(@set_is_last_in_sequence flags, $name, virtual_sequence_remaining);
                }
                if virtual_sequence_remaining.unwrap_or(0) != 0 {
                    flags = flags.set($crate::CircuitFlags::DoNotUpdateUnexpandedPC);
                }
                if self.0.is_compressed() {
                    flags = flags.set($crate::CircuitFlags::IsCompressed);
                }
                if self.0.is_first_in_sequence() {
                    flags = flags.set($crate::CircuitFlags::IsFirstInSequence);
                }
                flags
            }

            #[inline]
            fn instruction_flags(&self) -> $crate::InstructionFlagSet {
                $crate::InstructionFlagSet::default()
            }
        }

        $crate::jolt_instruction!(@jolt_instruction_impl $name);
    };

    // Internal: emit the struct definition.
    (@struct $(#[$attr:meta])* $name:ident) => {
        $(#[$attr])*
        #[derive(
            Clone,
            Copy,
            Debug,
            Default,
            PartialEq,
            Eq,
            Hash,
            ::serde::Serialize,
            ::serde::Deserialize,
        )]
        pub struct $name<T = ()>(pub T);
    };

    (@set_is_last_in_sequence $flags:ident, Jalr, $virtual_sequence_remaining:expr) => {
        if $virtual_sequence_remaining == Some(0) {
            $flags = $flags.set($crate::CircuitFlags::IsLastInSequence);
        }
    };

    (@set_is_last_in_sequence $flags:ident, $name:ident, $virtual_sequence_remaining:expr) => {};

    // Internal: emit `JoltInstruction` for `$name<T>` whenever `T` is itself a
    // `RISCVInstruction`. Lets call sites treat the wrapper newtype as a Jolt
    // instruction directly without unwrapping `self.0`.
    (@jolt_instruction_impl $name:ident) => {
        impl<T: ::tracer::instruction::RISCVInstruction> $crate::JoltInstruction for $name<T> {
            #[inline]
            fn is_noop(&self) -> bool {
                $crate::JoltInstruction::is_noop(&self.0)
            }

            #[inline]
            fn address(&self) -> u64 {
                $crate::JoltInstruction::address(&self.0)
            }

            #[inline]
            fn imm(&self) -> i128 {
                $crate::JoltInstruction::imm(&self.0)
            }

            #[inline]
            fn rs1(&self) -> Option<u8> {
                $crate::JoltInstruction::rs1(&self.0)
            }

            #[inline]
            fn rs2(&self) -> Option<u8> {
                $crate::JoltInstruction::rs2(&self.0)
            }

            #[inline]
            fn rd(&self) -> Option<u8> {
                $crate::JoltInstruction::rd(&self.0)
            }

            #[inline]
            fn virtual_sequence_remaining(&self) -> Option<u16> {
                $crate::JoltInstruction::virtual_sequence_remaining(&self.0)
            }

            #[inline]
            fn is_first_in_sequence(&self) -> bool {
                $crate::JoltInstruction::is_first_in_sequence(&self.0)
            }

            #[inline]
            fn is_virtual(&self) -> bool {
                $crate::JoltInstruction::is_virtual(&self.0)
            }

            #[inline]
            fn is_compressed(&self) -> bool {
                $crate::JoltInstruction::is_compressed(&self.0)
            }
        }
    };
}
