//! Jolt-owned generated schedule catalogs for the [`crate::configs`] configs.
//!
//! Tables are emitted offline by the `gen_jolt_schedules` binary (this
//! crate) through `akita_planner::emit` — the same emitter and DP that
//! produce akita's own shipped tables — over the prefix-packed `OneHotTrace`
//! arities reachable from Jolt in each K regime. Checked-in tables are source;
//! regenerate with:
//!
//! ```text
//! cargo run --release -p jolt-akita --bin gen_jolt_schedules -- crates/jolt-akita/src/schedules
//! ```
//!
//! The batched prove/verify protocol accepts only cataloged rows (the public
//! selection names a row digest the verifier resolves in the catalog), so
//! every provable shape must be an approved row here; setup-capacity queries
//! may still fall back to the planner DP. Catalog identity is validated
//! against the config policy on every lookup.

pub(crate) use akita_schedules::generated::{
    GeneratedBlockGeometry, GeneratedCommittedGroup, GeneratedFoldScheduleEntry,
    GeneratedInnerCommitMatrix, GeneratedOpenCommitMatrix, GeneratedOuterCommitMatrix,
    GeneratedRecursiveFold, GeneratedRootFinalGroup, GeneratedRootFold,
    GeneratedRootPrecommittedGroup, GeneratedSetupPrefixInput, GeneratedTerminalFold,
    GeneratedWitnessPartition, PlannerCostModelId, SelectionPolicyId, SelectiveL2ResponseModelId,
};
pub(crate) use akita_schedules::RingDimensionScheduleMode;
pub(crate) use akita_schedules::{GeneratedScheduleCatalogIdentity, GeneratedScheduleTable};
pub(crate) use akita_types::{
    ChunkedWitnessCfg, CommitmentPayloadMode, CommitmentRingDims, CommittedGroupProfile,
    DecompositionParams, InnerCommitMatrixParams, OuterCommitMatrixParams, PolynomialGroupLayout,
    SisL2TableDigest, SisModulusProfileId, SisSecurityPolicyId, SisTableDigest,
};

#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_dense_bounded;
#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_onehot_k16;
#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_onehot_k256;

/// The K=16 `OneHotTrace` catalog.
pub fn jolt_fp128_onehot_k16_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_onehot_k16::JOLT_FP128_ONEHOT_K16_SCHEDULES,
        identity: jolt_fp128_onehot_k16::CATALOG_IDENTITY,
    })
}

/// The K=256 large-trace `OneHotTrace` catalog.
pub fn jolt_fp128_onehot_k256_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_onehot_k256::JOLT_FP128_ONEHOT_K256_SCHEDULES,
        identity: jolt_fp128_onehot_k256::CATALOG_IDENTITY,
    })
}

/// The `u64`-bounded dense advice/program byte-object catalog.
pub fn jolt_fp128_dense_bounded_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_dense_bounded::JOLT_FP128_DENSE_BOUNDED_SCHEDULES,
        identity: jolt_fp128_dense_bounded::CATALOG_IDENTITY,
    })
}

/// Emit-spec construction shared by the `gen_jolt_schedules` binary and the
/// drift test: one family per config, scalar single-group keys over the
/// reachable `OneHotTrace` grid.
pub mod emit {
    use akita_config::{honest_fold_policy_of, policy_of, CommitmentConfig};
    use akita_pcs::AkitaError;
    use akita_planner::emit::GroupedGenerationRequest;
    use akita_planner::{find_schedule, EmitSpec};
    use akita_types::sis::HonestFoldPolicySpec;
    use akita_types::{
        AkitaScheduleLookupKey, FoldSchedule, OpeningClaimsLayout, PolynomialGroupLayout,
    };

    use crate::configs::{JoltDenseBounded, JoltOneHotK16, JoltOneHotK256};

    /// Prefix packing produces one physical polynomial; small two-poly rows
    /// are kept for the adapter/tamper test shapes (the verifier only accepts
    /// cataloged rows, so test shapes must be approved rows too).
    pub const ONE_HOT_TRACE_NUM_POLYS: &[usize] = &[1, 2];
    /// K=16 adds six selector variables to column arity `4 + log_T`; the low
    /// end covers the adapter test shapes.
    pub const K16_NUM_VARS: (usize, usize) = (12, 34);

    /// K=256 adds five selector variables to column arity `8 + log_T`; the
    /// low end covers the adapter test shapes.
    pub const K256_NUM_VARS: (usize, usize) = (12, 43);

    /// Bounded-dense advice/program byte objects: word-byte arity over the
    /// supported trace range. The low end is the folded-only planner floor for
    /// the dense fp128 shape; smaller objects pad up to it.
    pub const DENSE_NUM_VARS: (usize, usize) = (14, 34);

    /// Pure DP regeneration for `Cfg` — never consults the shipped table.
    pub(crate) fn regen<Cfg: CommitmentConfig>(
        key: PolynomialGroupLayout,
    ) -> Result<FoldSchedule, AkitaError> {
        plan::<Cfg>(&AkitaScheduleLookupKey::single(key), &[])
    }

    fn plan<Cfg: CommitmentConfig>(
        key: &AkitaScheduleLookupKey,
        precommitted_honest_fold_policies: &[HonestFoldPolicySpec],
    ) -> Result<FoldSchedule, AkitaError> {
        let planned = find_schedule(
            key,
            honest_fold_policy_of::<Cfg>(),
            precommitted_honest_fold_policies,
            &policy_of::<Cfg>(),
            Cfg::ring_challenge_config,
        )?;
        planned.schedule.validate_structure()?;
        Ok(planned.schedule)
    }

    /// No Jolt family emits grouped rows (see [`family_specs`]), so the emitter
    /// never reaches this. A grouped row must be planned against its
    /// precommitted producers' own fold policies, and `GroupedGenerationRequest`
    /// keeps those private to akita-planner's generator — so refuse rather than
    /// plan one against a substituted policy.
    fn reject_grouped(request: GroupedGenerationRequest) -> Result<FoldSchedule, AkitaError> {
        Err(AkitaError::InvalidSetup(format!(
            "jolt families emit no grouped rows; refusing to plan {:?}",
            request.key()
        )))
    }

    /// The reachable scalar keys of one family grid.
    pub fn keys(
        num_polys: &[usize],
        (min_vars, max_vars): (usize, usize),
    ) -> Vec<PolynomialGroupLayout> {
        let mut keys = Vec::new();
        for &polys in num_polys {
            for num_vars in min_vars..=max_vars {
                let layout = OpeningClaimsLayout::new(num_vars, polys)
                    .and_then(|layout| layout.root_final_group_layout());
                if let Ok(key) = layout {
                    keys.push(key);
                }
            }
        }
        keys
    }

    fn spec<Cfg: CommitmentConfig>(
        module_name: &'static str,
        const_name: &'static str,
        family_name: &'static str,
        num_polys: &[usize],
        num_vars: (usize, usize),
        output_dir: std::path::PathBuf,
    ) -> Result<EmitSpec, AkitaError> {
        Ok(EmitSpec {
            module_name,
            const_name,
            family_name,
            schedule_feature: "",
            policy: policy_of::<Cfg>(),
            source_contract: Cfg::committed_source_contract()?,
            keys: keys(num_polys, num_vars),
            grouped_requests: Vec::new(),
            preplanned_scalar: Vec::new(),
            output_dir,
            regen: regen::<Cfg>,
            regen_group_batch: reject_grouped,
            ring_challenge_config: Cfg::ring_challenge_config,
            generator_command:
                "cargo run --release -p jolt-akita --bin gen_jolt_schedules -- crates/jolt-akita/src/schedules",
        })
    }

    /// All family specs, in emission order.
    ///
    /// No family emits grouped advice rows. A grouped row is keyed on the frozen
    /// precommit profiles, which follow the program's
    /// `max_{un,}trusted_advice_size`; shipping rows for a handful of guessed
    /// capacities covered only those and implied the rest were unsupported.
    /// Preprocessing plans every grouped advice row instead
    /// (`schedule_registry::provision_advice_for_k`), so there is exactly one
    /// path — resolution checks the registry first and falls through to a catalog
    /// that carries no grouped rows to find.
    /// Fallible because each spec carries its config's declared producer
    /// contract, and constructing one validates the declaration.
    pub fn family_specs(output_dir: std::path::PathBuf) -> Result<[EmitSpec; 3], AkitaError> {
        Ok([
            spec::<JoltOneHotK16>(
                "jolt_fp128_onehot_k16",
                "JOLT_FP128_ONEHOT_K16_SCHEDULES",
                "jolt-fp128-onehot-k16",
                ONE_HOT_TRACE_NUM_POLYS,
                K16_NUM_VARS,
                output_dir.clone(),
            )?,
            spec::<JoltOneHotK256>(
                "jolt_fp128_onehot_k256",
                "JOLT_FP128_ONEHOT_K256_SCHEDULES",
                "jolt-fp128-onehot-k256",
                ONE_HOT_TRACE_NUM_POLYS,
                K256_NUM_VARS,
                output_dir.clone(),
            )?,
            spec::<JoltDenseBounded>(
                "jolt_fp128_dense_bounded",
                "JOLT_FP128_DENSE_BOUNDED_SCHEDULES",
                "jolt-fp128-dense-bounded",
                ONE_HOT_TRACE_NUM_POLYS,
                DENSE_NUM_VARS,
                output_dir,
            )?,
        ])
    }
}
