//! Jolt-owned generated schedule catalogs for the [`crate::configs`] configs.
//!
//! Tables are emitted offline by the `gen_jolt_schedules` binary (this
//! crate) through `akita_planner::emit` — the same emitter and DP that
//! produce akita's own shipped tables — over the shapes reachable from Jolt:
//! every native `OneHotTrace` group width produced by the RA layout and
//! unsigned-increment chunking across each K regime, plus the dense-flavor
//! grid (advice byte columns, sparse-unit and dense groups). Checked-in
//! tables are source; regenerate with:
//!
//! ```text
//! cargo run --release -p jolt-akita --bin gen_jolt_schedules -- crates/jolt-akita/src/schedules
//! ```
//!
//! Post-cutover Akita resolves runtime schedules from generated catalogs
//! only (the planner DP is offline-only); a lookup miss is a hard error, so
//! each catalog must cover its config's full reachable grid. Catalog
//! identity is validated against the config policy on every lookup.

pub(crate) use akita_planner::{GeneratedScheduleCatalogIdentity, GeneratedScheduleTable};
pub(crate) use akita_schedules::generated::{
    GeneratedBlockGeometry, GeneratedCommittedGroup, GeneratedFoldScheduleEntry,
    GeneratedInnerCommitMatrix, GeneratedOpenCommitMatrix, GeneratedOuterCommitMatrix,
    GeneratedRecursiveFold, GeneratedRootFinalChallenge, GeneratedRootFinalGroup,
    GeneratedRootFold, GeneratedRootPrecommittedGroup, GeneratedRootSource,
    GeneratedSetupPrefixInput, GeneratedTerminalFold, GeneratedWitnessPartition,
};
pub(crate) use akita_schedules::{PlannerCostModelId, SelectionPolicyId};
pub(crate) use akita_types::{
    ChunkedWitnessCfg, CommitmentRingDims, DecompositionParams, PolynomialGroupLayout,
    PrecommittedGroupDescriptor, SisModulusProfileId, SisSecurityPolicyId, SisTableDigest,
    TensorChallengeShape,
};

#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_d64_dense;
#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_d64_onehot_k16;
#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_d64_onehot_k256;

/// The dense-flavor catalog (advice byte columns, sparse-unit and dense
/// commitment groups).
pub fn jolt_fp128_d64_dense_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_d64_dense::JOLT_FP128_D64_DENSE_SCHEDULES,
        identity: jolt_fp128_d64_dense::CATALOG_IDENTITY,
    })
}

/// The K=16 `OneHotTrace` catalog.
pub fn jolt_fp128_d64_onehot_k16_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_d64_onehot_k16::JOLT_FP128_D64_ONEHOT_K16_SCHEDULES,
        identity: jolt_fp128_d64_onehot_k16::CATALOG_IDENTITY,
    })
}

/// The K=256 large-trace `OneHotTrace` catalog.
pub fn jolt_fp128_d64_onehot_k256_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_d64_onehot_k256::JOLT_FP128_D64_ONEHOT_K256_SCHEDULES,
        identity: jolt_fp128_d64_onehot_k256::CATALOG_IDENTITY,
    })
}

/// Emit-spec construction shared by the `gen_jolt_schedules` binary and the
/// drift test: one family per config, scalar single-group keys over the
/// reachable `OneHotTrace` grid.
pub mod emit {
    use akita_config::{policy_of, CommitmentConfig};
    use akita_error::AkitaError;
    use akita_planner::{find_schedule, EmitSpec};
    use akita_types::{
        AkitaScheduleLookupKey, FoldSchedule, OpeningClaimsLayout, PolynomialGroupLayout,
    };

    use crate::configs::{JoltD64Dense, JoltD64OneHotK16, JoltD64OneHotK256};

    /// `OneHotTrace` widths at K=16: 49 fixed columns (32 instruction-address
    /// chunks, 16 unsigned-increment chunks, and the increment MSB), plus up
    /// to 16 bytecode and 16 RAM chunks. Width one covers singleton one-hot
    /// objects.
    pub const K16_NUM_POLYS: &[usize] = &[
        1, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
    ];
    /// Column arity is `4 + log_T`. The packed pipeline pads every trace to
    /// `T >= 2^12` (`AkitaPackedScheme::MIN_PADDED_TRACE_LENGTH` — the
    /// folded-only planner cannot schedule wide K=16 groups below 16
    /// variables), and `log_T < 25` in the K=16 regime.
    pub const K16_NUM_VARS: (usize, usize) = (16, 28);

    /// Dense-flavor group widths: the packed prover's dense and sparse-unit
    /// objects (advice byte columns, the precommitted program) always commit
    /// singleton groups; {2, 4} mirror the upstream dense family's audited
    /// grid for small batched-dense tests.
    pub const DENSE_NUM_POLYS: &[usize] = &[1, 2, 4];
    /// Dense keys span the full range the upstream `fp128-d64-dense` family
    /// covered (`num_vars` 1..=50); dense objects range from tiny test
    /// advice shapes to trace-scale byte columns.
    pub const DENSE_NUM_VARS: (usize, usize) = (1, 50);

    /// `OneHotTrace` widths at K=256: 25 fixed columns (16 instruction
    /// chunks, eight unsigned-increment chunks, and the MSB), plus up to eight
    /// bytecode and eight RAM chunks.
    pub const K256_NUM_POLYS: &[usize] = &[
        1, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
    ];
    /// Column arity is `8 + log_T`; the K=256 regime starts at `log_T = 25`.
    pub const K256_NUM_VARS: (usize, usize) = (33, 38);

    /// Pure DP regeneration for `Cfg` — never consults the shipped table.
    fn regen<Cfg: CommitmentConfig>(
        key: PolynomialGroupLayout,
    ) -> Result<FoldSchedule, AkitaError> {
        regen_group_batch::<Cfg>(AkitaScheduleLookupKey::single(key))
    }

    fn regen_group_batch<Cfg: CommitmentConfig>(
        key: AkitaScheduleLookupKey,
    ) -> Result<FoldSchedule, AkitaError> {
        let planned = find_schedule(
            &key,
            &policy_of::<Cfg>(),
            Cfg::ring_challenge_config,
            Cfg::fold_challenge_shape_at_level,
        )?;
        planned.schedule.validate_structure()?;
        Ok(planned.schedule)
    }

    /// The reachable scalar keys of one family grid.
    pub fn keys(
        num_polys: &[usize],
        (min_vars, max_vars): (usize, usize),
    ) -> Vec<PolynomialGroupLayout> {
        let mut keys = Vec::new();
        for &polys in num_polys {
            for num_vars in min_vars..=max_vars {
                let layout = OpeningClaimsLayout::new(num_vars, polys)
                    .and_then(|layout| layout.root_final_group_layout());
                if let Ok(key) = layout {
                    keys.push(key);
                }
            }
        }
        keys
    }

    /// Small shapes exercised by jolt-akita's own test harnesses (shape-guard
    /// forgeries, pathology fixtures). Upstream ships analogous test-scale
    /// rows in its local catalogs, but those are gitignored bootstrap
    /// artifacts a Git-dependency checkout does not contain, so the
    /// Jolt-owned catalogs carry the test grid too. Layout-invalid
    /// combinations are dropped by [`keys`]; production grids are unaffected.
    pub const TEST_SUPPORT_NUM_POLYS: &[usize] = &[1, 2, 3, 4];
    pub const TEST_SUPPORT_NUM_VARS: (usize, usize) = (12, 16);

    fn spec<Cfg: CommitmentConfig>(
        module_name: &'static str,
        const_name: &'static str,
        family_name: &'static str,
        num_polys: &[usize],
        num_vars: (usize, usize),
        output_dir: std::path::PathBuf,
    ) -> EmitSpec {
        let mut grid = keys(num_polys, num_vars);
        for key in keys(TEST_SUPPORT_NUM_POLYS, TEST_SUPPORT_NUM_VARS) {
            if !grid.contains(&key) {
                grid.push(key);
            }
        }
        EmitSpec {
            module_name,
            const_name,
            family_name,
            schedule_feature: "",
            policy: policy_of::<Cfg>(),
            keys: grid,
            group_batch_keys: Vec::new(),
            emit_group_batch: false,
            output_dir,
            regen: regen::<Cfg>,
            regen_group_batch: regen_group_batch::<Cfg>,
            ring_challenge_config: Cfg::ring_challenge_config,
            fold_challenge_shape_at_level: Cfg::fold_challenge_shape_at_level,
            generator_command:
                "cargo run --release -p jolt-akita --bin gen_jolt_schedules -- crates/jolt-akita/src/schedules",
        }
    }

    /// All family specs, in emission order.
    pub fn family_specs(output_dir: std::path::PathBuf) -> [EmitSpec; 3] {
        [
            spec::<JoltD64Dense>(
                "jolt_fp128_d64_dense",
                "JOLT_FP128_D64_DENSE_SCHEDULES",
                "jolt-fp128-d64-dense",
                DENSE_NUM_POLYS,
                DENSE_NUM_VARS,
                output_dir.clone(),
            ),
            spec::<JoltD64OneHotK16>(
                "jolt_fp128_d64_onehot_k16",
                "JOLT_FP128_D64_ONEHOT_K16_SCHEDULES",
                "jolt-fp128-d64-onehot-k16",
                K16_NUM_POLYS,
                K16_NUM_VARS,
                output_dir.clone(),
            ),
            {
                // The forced-K256 e2e (jolt-prover-legacy packed tests) runs
                // the K=256 regime at the minimum muldiv trace (20 vars),
                // below the production window; its setup sizing needs
                // catalog rows there.
                let mut k256 = spec::<JoltD64OneHotK256>(
                    "jolt_fp128_d64_onehot_k256",
                    "JOLT_FP128_D64_ONEHOT_K256_SCHEDULES",
                    "jolt-fp128-d64-onehot-k256",
                    K256_NUM_POLYS,
                    K256_NUM_VARS,
                    output_dir,
                );
                for key in keys(K256_NUM_POLYS, (20, 20)) {
                    if !k256.keys.contains(&key) {
                        k256.keys.push(key);
                    }
                }
                k256
            },
        ]
    }
}
