//! Jolt-owned generated schedule catalogs for the [`crate::configs`] configs.
//!
//! Tables are emitted offline by the `gen_jolt_schedules` binary (this
//! crate) through `akita_planner::emit` — the same emitter and DP that
//! produce akita's own shipped tables — over the prefix-packed `OneHotTrace`
//! arities reachable from Jolt in each K regime. Checked-in tables are source;
//! regenerate with:
//!
//! ```text
//! cargo run --release -p jolt-akita --bin gen_jolt_schedules -- crates/jolt-akita/src/schedules
//! ```
//!
//! The batched prove/verify protocol accepts only cataloged rows (the public
//! selection names a row digest the verifier resolves in the catalog), so
//! every provable shape must be an approved row here; setup-capacity queries
//! may still fall back to the planner DP. Catalog identity is validated
//! against the config policy on every lookup.

pub(crate) use akita_planner::{GeneratedScheduleCatalogIdentity, GeneratedScheduleTable};
pub(crate) use akita_schedules::generated::{
    GeneratedBlockGeometry, GeneratedCommittedGroup, GeneratedFoldScheduleEntry,
    GeneratedInnerCommitMatrix, GeneratedOpenCommitMatrix, GeneratedOuterCommitMatrix,
    GeneratedRecursiveFold, GeneratedRootFinalGroup, GeneratedRootFold,
    GeneratedRootPrecommittedGroup, GeneratedSetupPrefixInput, GeneratedTerminalFold,
    GeneratedWitnessPartition, PlannerCostModelId, SelectionPolicyId,
};
pub(crate) use akita_schedules::RingDimensionScheduleMode;
pub(crate) use akita_types::{
    ChunkedWitnessCfg, CommitmentPayloadMode, CommitmentRingDims, CommittedGroupProfile,
    DecompositionParams, InnerCommitMatrixParams, OuterCommitMatrixParams, PolynomialGroupLayout,
    SisModulusProfileId, SisSecurityPolicyId, SisTableDigest,
};

#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_d128_onehot_k256;
#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_d64_dense;
#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_d64_onehot_k16;
#[expect(
    clippy::allow_attributes,
    clippy::unreadable_literal,
    reason = "generated by akita's table emitter"
)]
mod jolt_fp128_d64_onehot_k256;

/// The K=16 `OneHotTrace` catalog.
pub fn jolt_fp128_d64_onehot_k16_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_d64_onehot_k16::JOLT_FP128_D64_ONEHOT_K16_SCHEDULES,
        precommitted_profiles: &[],
        identity: jolt_fp128_d64_onehot_k16::CATALOG_IDENTITY,
    })
}

/// The K=256 large-trace `OneHotTrace` catalog.
pub fn jolt_fp128_d64_onehot_k256_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_d64_onehot_k256::JOLT_FP128_D64_ONEHOT_K256_SCHEDULES,
        precommitted_profiles: &[],
        identity: jolt_fp128_d64_onehot_k256::CATALOG_IDENTITY,
    })
}

/// The D128, K=256 largest-trace `OneHotTrace` catalog.
pub fn jolt_fp128_d128_onehot_k256_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_d128_onehot_k256::JOLT_FP128_D128_ONEHOT_K256_SCHEDULES,
        precommitted_profiles: &[],
        identity: jolt_fp128_d128_onehot_k256::CATALOG_IDENTITY,
    })
}

/// The dense advice/program byte-object catalog.
pub fn jolt_fp128_d64_dense_table() -> Option<GeneratedScheduleTable> {
    Some(GeneratedScheduleTable {
        entries: jolt_fp128_d64_dense::JOLT_FP128_D64_DENSE_SCHEDULES,
        precommitted_profiles: &[],
        identity: jolt_fp128_d64_dense::CATALOG_IDENTITY,
    })
}

/// Emit-spec construction shared by the `gen_jolt_schedules` binary and the
/// drift test: one family per config, scalar single-group keys over the
/// reachable `OneHotTrace` grid.
pub mod emit {
    use akita_config::{policy_of, CommitmentConfig};
    use akita_pcs::AkitaError;
    use akita_planner::{find_schedule, EmitSpec};
    use akita_types::sis::HonestFoldPolicySpec;
    use akita_types::{
        AkitaScheduleLookupKey, FoldSchedule, OpeningClaimsLayout, PolynomialGroupLayout,
    };

    use crate::configs::{JoltD128OneHotK256, JoltD64Dense, JoltD64OneHotK16, JoltD64OneHotK256};

    /// Prefix packing produces one physical polynomial; small two-poly rows
    /// are kept for the adapter/tamper test shapes (the verifier only accepts
    /// cataloged rows, so test shapes must be approved rows too).
    pub const ONE_HOT_TRACE_NUM_POLYS: &[usize] = &[1, 2];
    /// K=16 adds six selector variables to column arity `4 + log_T`; the low
    /// end covers the adapter test shapes.
    pub const K16_NUM_VARS: (usize, usize) = (12, 34);

    /// K=256 adds five selector variables to column arity `8 + log_T`; the
    /// low end covers the adapter test shapes.
    pub const K256_NUM_VARS: (usize, usize) = (12, 43);

    /// Dense advice/program byte objects: word-byte arity over the supported
    /// trace range. The low end is the folded-only planner floor for the
    /// dense fp128 D64 shape; smaller objects pad up to it.
    pub const DENSE_NUM_VARS: (usize, usize) = (14, 34);

    /// Pure DP regeneration for `Cfg` — never consults the shipped table.
    fn regen<Cfg: CommitmentConfig>(
        key: PolynomialGroupLayout,
    ) -> Result<FoldSchedule, AkitaError> {
        regen_group_batch::<Cfg>(AkitaScheduleLookupKey::single(key), Vec::new())
    }

    fn regen_group_batch<Cfg: CommitmentConfig>(
        key: AkitaScheduleLookupKey,
        precommitted_honest_fold_policies: Vec<HonestFoldPolicySpec>,
    ) -> Result<FoldSchedule, AkitaError> {
        let planned = find_schedule(
            &key,
            Cfg::root_honest_fold_policy(),
            &precommitted_honest_fold_policies,
            &policy_of::<Cfg>(),
            Cfg::ring_challenge_config,
        )?;
        planned.schedule.validate_structure()?;
        Ok(planned.schedule)
    }

    /// The reachable scalar keys of one family grid.
    pub fn keys(
        num_polys: &[usize],
        (min_vars, max_vars): (usize, usize),
    ) -> Vec<PolynomialGroupLayout> {
        let mut keys = Vec::new();
        for &polys in num_polys {
            for num_vars in min_vars..=max_vars {
                let layout = OpeningClaimsLayout::new(num_vars, polys)
                    .and_then(|layout| layout.root_final_group_layout());
                if let Ok(key) = layout {
                    keys.push(key);
                }
            }
        }
        keys
    }

    fn spec<Cfg: CommitmentConfig>(
        module_name: &'static str,
        const_name: &'static str,
        family_name: &'static str,
        num_polys: &[usize],
        num_vars: (usize, usize),
        output_dir: std::path::PathBuf,
    ) -> EmitSpec {
        EmitSpec {
            module_name,
            const_name,
            family_name,
            schedule_feature: "",
            policy: policy_of::<Cfg>(),
            keys: keys(num_polys, num_vars),
            group_batch_keys: Vec::new(),
            emit_group_batch: false,
            output_dir,
            regen: regen::<Cfg>,
            regen_group_batch: regen_group_batch::<Cfg>,
            ring_challenge_config: Cfg::ring_challenge_config,
            precommitted_profiles: Vec::new(),
            generator_command:
                "cargo run --release -p jolt-akita --bin gen_jolt_schedules -- crates/jolt-akita/src/schedules",
        }
    }

    /// All family specs, in emission order.
    pub fn family_specs(output_dir: std::path::PathBuf) -> [EmitSpec; 4] {
        [
            spec::<JoltD64OneHotK16>(
                "jolt_fp128_d64_onehot_k16",
                "JOLT_FP128_D64_ONEHOT_K16_SCHEDULES",
                "jolt-fp128-d64-onehot-k16",
                ONE_HOT_TRACE_NUM_POLYS,
                K16_NUM_VARS,
                output_dir.clone(),
            ),
            spec::<JoltD64OneHotK256>(
                "jolt_fp128_d64_onehot_k256",
                "JOLT_FP128_D64_ONEHOT_K256_SCHEDULES",
                "jolt-fp128-d64-onehot-k256",
                ONE_HOT_TRACE_NUM_POLYS,
                K256_NUM_VARS,
                output_dir.clone(),
            ),
            spec::<JoltD128OneHotK256>(
                "jolt_fp128_d128_onehot_k256",
                "JOLT_FP128_D128_ONEHOT_K256_SCHEDULES",
                "jolt-fp128-d128-onehot-k256",
                ONE_HOT_TRACE_NUM_POLYS,
                K256_NUM_VARS,
                output_dir.clone(),
            ),
            spec::<JoltD64Dense>(
                "jolt_fp128_d64_dense",
                "JOLT_FP128_D64_DENSE_SCHEDULES",
                "jolt-fp128-d64-dense",
                ONE_HOT_TRACE_NUM_POLYS,
                DENSE_NUM_VARS,
                output_dir,
            ),
        ]
    }
}
