[package]
name = "verifier-on-jolt-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = ["guest-std"] }
jolt-verifier = { path = "../../../jolt-verifier" }
ark-bn254 = "0.5.0"

[patch.crates-io]
#getrandom = { path = "../../../../getrandom",  version = "0.3.3" }
getrandom = { path = "../../../../getrandom-2" }