[package]
name = "jolt-verifier"
version = "0.1.0"
edition = "2024"

[dependencies]
jolt-core = { path = "../jolt-core", default-features = false, features = ["parallel"] }
getrandom = "0.2.16"
rand = "0.8.5"
common = { path = "../common" }