//! The stage 5 `RamRaClaimReduction` sumcheck instance.
//!
//! A single self-contained relation object, driven identically by the prover
//! (while producing the stage 5 batch proof) and the verifier (after checking
//! it). It owns the RAM-RA reduction's point splice, public-value computation,
//! and address-agreement check, so the input/output claim math lives here once
//! instead of being hand-coded separately on each side. The consumed/produced
//! claim structs and their `InputClaims`/`OutputClaims` impls are defined in this
//! module (generated by the cell-aware derives).

use jolt_claims::protocols::jolt::relations;
pub use jolt_claims::protocols::jolt::relations::ram::{
    RamRaClaimReductionChallenges, RamRaClaimReductionInputClaims, RamRaClaimReductionOutputClaims,
};
use jolt_claims::protocols::jolt::{
    geometry::dimensions::TraceDimensions, JoltDerivedId, JoltRelationId, RamRaClaimReductionPublic,
};
use jolt_claims::SymbolicSumcheck;
use jolt_field::Field;
use jolt_poly::try_eq_mle;

use crate::stages::relations::ConcreteSumcheck;
use crate::stages::stage2::{Stage2BatchOutputClaims, Stage2BatchOutputPoints};
use crate::stages::stage4::{Stage4OutputClaims, Stage4OutputPoints};
use crate::VerifierError;

/// Wire this relation's consumed opening *values* from the upstream outputs: the
/// RAF-evaluation and read-write openings (stage 2) and the val-check opening
/// (stage 4). Takes the ZK-agnostic output-claims aggregates.
pub fn ram_ra_claim_reduction_input_values_from_upstream<F: Field>(
    stage2: &Stage2BatchOutputClaims<F>,
    stage4: &Stage4OutputClaims<F>,
) -> RamRaClaimReductionInputClaims<F> {
    RamRaClaimReductionInputClaims {
        raf: stage2.ram_raf_evaluation.ram_ra,
        read_write: stage2.ram_read_write.ra,
        val_check: stage4.ram_val_check.ram_ra,
    }
}

/// Wire this relation's consumed opening *points* from the upstream output-points
/// aggregates.
pub fn ram_ra_claim_reduction_input_points_from_upstream<F: Field>(
    stage2: &Stage2BatchOutputPoints<F>,
    stage4: &Stage4OutputPoints<F>,
) -> RamRaClaimReductionInputClaims<Vec<F>> {
    RamRaClaimReductionInputClaims {
        raf: stage2.ram_raf_evaluation_point().to_vec(),
        read_write: stage2.ram_read_write_point().to_vec(),
        val_check: stage4.ram_val_check_point().to_vec(),
    }
}

pub struct RamRaClaimReduction<F: Field> {
    symbolic: relations::ram::RaClaimReduction,
    trace_dimensions: TraceDimensions,
    ram_log_k: usize,
    _field: core::marker::PhantomData<F>,
}

impl<F: Field> RamRaClaimReduction<F> {
    pub fn new(trace_dimensions: TraceDimensions, ram_log_k: usize) -> Self {
        Self {
            symbolic: relations::ram::RaClaimReduction::new(trace_dimensions),
            trace_dimensions,
            ram_log_k,
            _field: core::marker::PhantomData,
        }
    }
}

fn public_input_failed(reason: impl ToString) -> VerifierError {
    VerifierError::StageClaimPublicInputFailed {
        stage: JoltRelationId::RamRaClaimReduction,
        reason: reason.to_string(),
    }
}

impl<F: Field> ConcreteSumcheck<F> for RamRaClaimReduction<F> {
    type Symbolic = relations::ram::RaClaimReduction;

    fn symbolic(&self) -> &Self::Symbolic {
        &self.symbolic
    }

    fn derive_opening_points(
        &self,
        sumcheck_point: &[F],
        input_points: &RamRaClaimReductionInputClaims<Vec<F>>,
    ) -> Result<RamRaClaimReductionOutputClaims<Vec<F>>, VerifierError> {
        let log_t = self.trace_dimensions.log_t();
        let expected_len = self.ram_log_k + log_t;
        for (label, point) in [
            ("RAF", input_points.raf()),
            ("read-write", input_points.read_write()),
            ("val-check", input_points.val_check()),
        ] {
            if point.len() != expected_len {
                return Err(public_input_failed(format!(
                    "RAM {label} opening point has {} variables, expected {expected_len}",
                    point.len()
                )));
            }
        }
        let address = &input_points.read_write()[..self.ram_log_k];
        if &input_points.raf()[..self.ram_log_k] != address
            || &input_points.val_check()[..self.ram_log_k] != address
        {
            return Err(public_input_failed(
                "RAM input openings disagree on the address prefix",
            ));
        }
        let cycle = self
            .trace_dimensions
            .cycle_opening_point(sumcheck_point)
            .map_err(public_input_failed)?;
        let opening_point = [address, cycle.as_slice()].concat();
        Ok(RamRaClaimReductionOutputClaims {
            ram_ra: opening_point,
        })
    }

    fn derive_output_term(
        &self,
        id: &JoltDerivedId,
        input_points: &RamRaClaimReductionInputClaims<Vec<F>>,
        output_points: &RamRaClaimReductionOutputClaims<Vec<F>>,
        _challenges: &RamRaClaimReductionChallenges<F>,
    ) -> Result<F, VerifierError> {
        let JoltDerivedId::RamRaClaimReduction(public_id) = id else {
            return Err(VerifierError::MissingStageClaimDerived { id: *id });
        };
        let output_cycle = &output_points.ram_ra()[self.ram_log_k..];
        let fixed_cycle = match public_id {
            RamRaClaimReductionPublic::EqCycleRaf => &input_points.raf()[self.ram_log_k..],
            RamRaClaimReductionPublic::EqCycleReadWrite => {
                &input_points.read_write()[self.ram_log_k..]
            }
            RamRaClaimReductionPublic::EqCycleValCheck => {
                &input_points.val_check()[self.ram_log_k..]
            }
        };
        try_eq_mle(fixed_cycle, output_cycle).map_err(public_input_failed)
    }
}
