//! The stage 5 `RamRaClaimReduction` sumcheck instance.
//!
//! A single self-contained relation object, driven identically by the prover
//! (while producing the stage 5 batch proof) and the verifier (after checking
//! it). It owns the RAM-RA reduction's point splice, public-value computation,
//! and address-agreement check, so the input/output claim math lives here once
//! instead of being hand-coded separately on each side. The consumed/produced
//! claim structs and their `InputClaims`/`OutputClaims` impls are defined in this
//! module (generated by the cell-aware derives).

use jolt_claims::protocols::jolt::relations;
pub use jolt_claims::protocols::jolt::relations::ram::{
    RamRaClaimReductionChallenges, RamRaClaimReductionInputClaims, RamRaClaimReductionOutputClaims,
};
use jolt_claims::protocols::jolt::{
    geometry::dimensions::TraceDimensions, JoltDerivedId, JoltRelationId, RamRaClaimReductionPublic,
};
use jolt_claims::SymbolicSumcheck;
use jolt_field::Field;
use jolt_poly::try_eq_mle;

use crate::stages::relations::{ConcreteSumcheck, GetPoint, OpeningClaim};
use crate::stages::stage2::Stage2ClearOutput;
use crate::stages::stage4::Stage4ClearOutput;
use crate::VerifierError;

/// Wire this relation's consumed openings from the upstream clear outputs:
/// the RAF-evaluation and read-write openings (stage 2) and the val-check
/// opening (stage 4), each as an `OpeningClaim` (point + value). (Verifier-side
/// constructor for the moved [`RamRaClaimReductionInputClaims`].)
pub fn ram_ra_claim_reduction_inputs_from_upstream<F: Field>(
    stage2: &Stage2ClearOutput<F>,
    stage4: &Stage4ClearOutput<F>,
) -> RamRaClaimReductionInputClaims<OpeningClaim<F>> {
    RamRaClaimReductionInputClaims {
        raf: OpeningClaim {
            point: stage2.output_claims.ram_raf_evaluation_point().to_vec(),
            value: stage2.output_claims.ram_raf_evaluation.ram_ra.value,
        },
        read_write: OpeningClaim {
            point: stage2.output_claims.ram_read_write_point().to_vec(),
            value: stage2.output_claims.ram_read_write.ra.value,
        },
        val_check: stage4.output_claims.ram_val_check.ram_ra.clone(),
    }
}

pub struct RamRaClaimReduction<F: Field> {
    symbolic: relations::ram::RaClaimReduction,
    trace_dimensions: TraceDimensions,
    ram_log_k: usize,
    _field: core::marker::PhantomData<F>,
}

impl<F: Field> RamRaClaimReduction<F> {
    pub fn new(trace_dimensions: TraceDimensions, ram_log_k: usize) -> Self {
        Self {
            symbolic: relations::ram::RaClaimReduction::new(trace_dimensions),
            trace_dimensions,
            ram_log_k,
            _field: core::marker::PhantomData,
        }
    }
}

fn public_input_failed(reason: impl ToString) -> VerifierError {
    VerifierError::StageClaimPublicInputFailed {
        stage: JoltRelationId::RamRaClaimReduction,
        reason: reason.to_string(),
    }
}

impl<F: Field> ConcreteSumcheck<F> for RamRaClaimReduction<F> {
    type Symbolic = relations::ram::RaClaimReduction;
    type Inputs<C> = RamRaClaimReductionInputClaims<C>;
    type Outputs<C> = RamRaClaimReductionOutputClaims<C>;

    fn symbolic(&self) -> &Self::Symbolic {
        &self.symbolic
    }

    fn derive_opening_points<C: GetPoint<F>>(
        &self,
        sumcheck_point: &[F],
        inputs: &RamRaClaimReductionInputClaims<C>,
    ) -> Result<RamRaClaimReductionOutputClaims<Vec<F>>, VerifierError> {
        let log_t = self.trace_dimensions.log_t();
        let expected_len = self.ram_log_k + log_t;
        for (label, point) in [
            ("RAF", inputs.raf.point()),
            ("read-write", inputs.read_write.point()),
            ("val-check", inputs.val_check.point()),
        ] {
            if point.len() != expected_len {
                return Err(public_input_failed(format!(
                    "RAM {label} opening point has {} variables, expected {expected_len}",
                    point.len()
                )));
            }
        }
        let address = &inputs.read_write.point()[..self.ram_log_k];
        if &inputs.raf.point()[..self.ram_log_k] != address
            || &inputs.val_check.point()[..self.ram_log_k] != address
        {
            return Err(public_input_failed(
                "RAM input openings disagree on the address prefix",
            ));
        }
        let cycle = self
            .trace_dimensions
            .cycle_opening_point(sumcheck_point)
            .map_err(public_input_failed)?;
        let opening_point = [address, cycle.as_slice()].concat();
        Ok(RamRaClaimReductionOutputClaims {
            ram_ra: opening_point,
        })
    }

    fn resolve_public<C: GetPoint<F>>(
        &self,
        id: &JoltDerivedId,
        inputs: &RamRaClaimReductionInputClaims<C>,
        outputs: Option<&RamRaClaimReductionOutputClaims<OpeningClaim<F>>>,
        _challenges: &RamRaClaimReductionChallenges<F>,
    ) -> Result<F, VerifierError> {
        let outputs = outputs.ok_or(VerifierError::MissingStageClaimDerived { id: *id })?;
        let JoltDerivedId::RamRaClaimReduction(public_id) = id else {
            return Err(VerifierError::MissingStageClaimDerived { id: *id });
        };
        let output_cycle = &outputs.ram_ra.point()[self.ram_log_k..];
        let fixed_cycle = match public_id {
            RamRaClaimReductionPublic::EqCycleRaf => &inputs.raf.point()[self.ram_log_k..],
            RamRaClaimReductionPublic::EqCycleReadWrite => {
                &inputs.read_write.point()[self.ram_log_k..]
            }
            RamRaClaimReductionPublic::EqCycleValCheck => {
                &inputs.val_check.point()[self.ram_log_k..]
            }
        };
        try_eq_mle(fixed_cycle, output_cycle).map_err(public_input_failed)
    }
}
