//! The stage 5 `RamRaClaimReduction` sumcheck instance.
//!
//! A single self-contained relation object, driven identically by the prover
//! (while producing the stage 5 batch proof) and the verifier (after checking
//! it). It owns the RAM-RA reduction's point splice, public-value computation,
//! and address-agreement check, so the input/output claim math lives here once
//! instead of being hand-coded separately on each side. The consumed/produced
//! claim structs and their `InputClaims`/`OutputClaims` impls live in
//! `super::inputs` (generated by the cell-aware derives).

use jolt_claims::protocols::jolt::{
    formulas::{dimensions::TraceDimensions, ram},
    JoltChallengeId, JoltPublicId, JoltRelationClaims, JoltRelationId,
    RamRaClaimReductionChallenge, RamRaClaimReductionPublic,
};
use jolt_field::Field;
use jolt_poly::try_eq_mle;

use crate::stages::relations::{GetPoint, OpeningClaim, SumcheckInstance};
use crate::stages::stage5::inputs::{
    RamRaClaimReductionInputs, RamRaClaimReductionOutputOpeningClaims,
};
use crate::VerifierError;

pub struct RamRaClaimReductionRelation<F: Field> {
    claims: JoltRelationClaims<F>,
    trace_dimensions: TraceDimensions,
    ram_log_k: usize,
    gamma: F,
}

impl<F: Field> RamRaClaimReductionRelation<F> {
    pub fn new(trace_dimensions: TraceDimensions, ram_log_k: usize, gamma: F) -> Self {
        Self {
            claims: ram::ra_claim_reduction(trace_dimensions),
            trace_dimensions,
            ram_log_k,
            gamma,
        }
    }
}

fn public_input_failed(reason: impl ToString) -> VerifierError {
    VerifierError::StageClaimPublicInputFailed {
        stage: JoltRelationId::RamRaClaimReduction,
        reason: reason.to_string(),
    }
}

impl<F: Field> SumcheckInstance<F> for RamRaClaimReductionRelation<F> {
    type Inputs<C> = RamRaClaimReductionInputs<C>;
    type Outputs<C> = RamRaClaimReductionOutputOpeningClaims<C>;

    fn sumcheck_relation(&self) -> &JoltRelationClaims<F> {
        &self.claims
    }

    fn derive_output_points<C: GetPoint<F>>(
        &self,
        sumcheck_point: &[F],
        inputs: &RamRaClaimReductionInputs<C>,
    ) -> Result<RamRaClaimReductionOutputOpeningClaims<Vec<F>>, VerifierError> {
        let log_t = self.trace_dimensions.log_t();
        let expected_len = self.ram_log_k + log_t;
        for (label, point) in [
            ("RAF", inputs.raf.point()),
            ("read-write", inputs.read_write.point()),
            ("val-check", inputs.val_check.point()),
        ] {
            if point.len() != expected_len {
                return Err(public_input_failed(format!(
                    "RAM {label} opening point has {} variables, expected {expected_len}",
                    point.len()
                )));
            }
        }
        let address = &inputs.read_write.point()[..self.ram_log_k];
        if &inputs.raf.point()[..self.ram_log_k] != address
            || &inputs.val_check.point()[..self.ram_log_k] != address
        {
            return Err(public_input_failed(
                "RAM input openings disagree on the address prefix",
            ));
        }
        let cycle = self
            .trace_dimensions
            .cycle_opening_point(sumcheck_point)
            .map_err(public_input_failed)?;
        let opening_point = [address, cycle.as_slice()].concat();
        Ok(RamRaClaimReductionOutputOpeningClaims {
            ram_ra: opening_point,
        })
    }

    fn resolve_challenge(&self, id: &JoltChallengeId) -> Result<F, VerifierError> {
        match id {
            JoltChallengeId::RamRaClaimReduction(RamRaClaimReductionChallenge::Gamma) => {
                Ok(self.gamma)
            }
            _ => Err(VerifierError::MissingStageClaimChallenge { id: *id }),
        }
    }

    fn resolve_public<C: GetPoint<F>>(
        &self,
        id: &JoltPublicId,
        inputs: &RamRaClaimReductionInputs<C>,
        outputs: &RamRaClaimReductionOutputOpeningClaims<OpeningClaim<F>>,
    ) -> Result<F, VerifierError> {
        let JoltPublicId::RamRaClaimReduction(public_id) = id else {
            return Err(VerifierError::MissingStageClaimPublic { id: *id });
        };
        let output_cycle = &outputs.ram_ra.point()[self.ram_log_k..];
        let fixed_cycle = match public_id {
            RamRaClaimReductionPublic::EqCycleRaf => &inputs.raf.point()[self.ram_log_k..],
            RamRaClaimReductionPublic::EqCycleReadWrite => {
                &inputs.read_write.point()[self.ram_log_k..]
            }
            RamRaClaimReductionPublic::EqCycleValCheck => {
                &inputs.val_check.point()[self.ram_log_k..]
            }
        };
        try_eq_mle(fixed_cycle, output_cycle).map_err(public_input_failed)
    }
}
