[package]
name = "ntt-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []
field-inline = ["jolt/field-inline"]

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk" }
jolt-inlines-ntt.workspace = true
serde = { workspace = true, features = ["alloc"] }

[lib]
test = false
doctest = false
bench = false

[[bin]]
name = "ntt-guest"
path = "src/main.rs"
test = false
bench = false
