pub use tracer::instruction::inline::INLINE;
pub use tracer::utils::inline_test_harness::{InlineMemoryLayout, InlineTestHarness};

/// Formal specification of an inline's behavior.
/// Connects the mathematical reference implementation to the test harness.
pub trait InlineSpec {
    type Input;
    type Output: PartialEq + core::fmt::Debug;

    /// Pure reference implementation — the formal verification target.
    fn reference(input: &Self::Input) -> Self::Output;

    fn create_harness() -> InlineTestHarness;

    fn instruction() -> INLINE;

    /// Load typed input into harness memory and set up registers.
    fn load(harness: &mut InlineTestHarness, input: &Self::Input);

    /// Read typed output from harness memory after execution.
    fn read(harness: &mut InlineTestHarness) -> Self::Output;
}

/// Verify sequence builder matches reference for a given input.
pub fn verify<S: InlineSpec>(input: &S::Input) {
    let mut harness = S::create_harness();
    S::load(&mut harness, input);
    harness.execute_inline(S::instruction());
    let actual = S::read(&mut harness);
    let expected = S::reference(input);
    assert_eq!(actual, expected);
}

/// Run verify over many inputs generated by `gen`.
pub fn proptest<S: InlineSpec>(count: usize, gen: impl Fn(usize) -> S::Input) {
    for i in 0..count {
        verify::<S>(&gen(i));
    }
}
