#![cfg(not(feature = "field-inline"))]

use jolt_core::zkvm::lookup_table::LookupTables as CoreLookupTables;
use jolt_lookup_tables::tables::LookupTableKind;
use strum::EnumCount;

const XLEN: usize = 64;

fn core_index(table: CoreLookupTables<XLEN>) -> usize {
    CoreLookupTables::enum_index(&table)
}

#[test]
fn modular_lookup_table_indices_match_core_abi() {
    let cases = [
        (
            LookupTableKind::<XLEN>::RangeCheck(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::RangeCheck(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::RangeCheckAligned(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::RangeCheckAligned(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::And(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::And(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Andn(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::Andn(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Or(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::Or(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Xor(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::Xor(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Equal(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::Equal(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::SignedGreaterThanEqual(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::SignedGreaterThanEqual(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::UnsignedGreaterThanEqual(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::UnsignedGreaterThanEqual(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::NotEqual(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::NotEqual(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::SignedLessThan(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::SignedLessThan(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::UnsignedLessThan(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::UnsignedLessThan(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::SignMask(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::Movsign(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::UpperWord(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::UpperWord(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::UnsignedLessThanEqual(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::LessThanEqual(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::ValidUnsignedRemainder(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::ValidUnsignedRemainder(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::ValidDiv0(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::ValidDiv0(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::HalfwordAlignment(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::HalfwordAlignment(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::WordAlignment(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::WordAlignment(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::LowerHalfWord(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::LowerHalfWord(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::SignExtendHalfWord(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::SignExtendHalfWord(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::Pow2(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::Pow2(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Pow2W(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::Pow2W(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::ShiftRightBitmask(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::ShiftRightBitmask(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualRev8W(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualRev8W(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualSRL(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualSRL(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualSRA(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualSRA(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualROTR(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualROTR(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualROTRW(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualROTRW(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualChangeDivisor(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualChangeDivisor(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualChangeDivisorW(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualChangeDivisorW(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::MulUNoOverflow(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::MulUNoOverflow(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT32(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROT32(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT24(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROT24(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT16(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROT16(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT63(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROT63(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW16(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROTW16(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW12(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROTW12(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW8(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROTW8(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW7(Default::default()).index(),
            core_index(CoreLookupTables::<XLEN>::VirtualXORROTW7(Default::default())),
        ),
    ];

    assert_eq!(CoreLookupTables::<XLEN>::COUNT, cases.len());
    for (modular_index, core_index) in cases {
        assert_eq!(modular_index, core_index);
    }
    assert_eq!(
        LookupTableKind::<XLEN>::COUNT,
        CoreLookupTables::<XLEN>::COUNT
    );
}
