#![cfg(not(feature = "field-inline"))]

use jolt_lookup_tables::tables::LookupTableKind;
use jolt_prover_legacy::zkvm::lookup_table::LookupTables as ProverLookupTables;
use strum::EnumCount;

const XLEN: usize = 64;

fn prover_index(table: ProverLookupTables<XLEN>) -> usize {
    ProverLookupTables::enum_index(&table)
}

#[test]
fn modular_lookup_table_indices_match_prover_abi() {
    let cases = [
        (
            LookupTableKind::<XLEN>::RangeCheck(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::RangeCheck(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::RangeCheckAligned(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::RangeCheckAligned(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::And(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::And(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Andn(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::Andn(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Or(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::Or(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Xor(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::Xor(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Equal(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::Equal(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::SignedGreaterThanEqual(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::SignedGreaterThanEqual(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::UnsignedGreaterThanEqual(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::UnsignedGreaterThanEqual(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::NotEqual(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::NotEqual(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::SignedLessThan(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::SignedLessThan(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::UnsignedLessThan(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::UnsignedLessThan(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::SignMask(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::Movsign(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::UpperWord(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::UpperWord(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::UnsignedLessThanEqual(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::LessThanEqual(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::ValidUnsignedRemainder(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::ValidUnsignedRemainder(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::ValidDiv0(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::ValidDiv0(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::HalfwordAlignment(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::HalfwordAlignment(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::WordAlignment(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::WordAlignment(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::LowerHalfWord(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::LowerHalfWord(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::SignExtendHalfWord(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::SignExtendHalfWord(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::Pow2(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::Pow2(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::Pow2W(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::Pow2W(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::ShiftRightBitmask(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::ShiftRightBitmask(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualRev8W(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualRev8W(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualSRL(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualSRL(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualSRA(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualSRA(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualROTR(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualROTR(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualROTRW(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualROTRW(Default::default())),
        ),
        (
            LookupTableKind::<XLEN>::VirtualChangeDivisor(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualChangeDivisor(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualChangeDivisorW(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualChangeDivisorW(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::MulUNoOverflow(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::MulUNoOverflow(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT32(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROT32(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT24(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROT24(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT16(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROT16(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROT63(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROT63(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW16(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROTW16(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW12(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROTW12(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW8(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROTW8(
                Default::default(),
            )),
        ),
        (
            LookupTableKind::<XLEN>::VirtualXORROTW7(Default::default()).index(),
            prover_index(ProverLookupTables::<XLEN>::VirtualXORROTW7(
                Default::default(),
            )),
        ),
    ];

    assert_eq!(ProverLookupTables::<XLEN>::COUNT, cases.len());
    for (modular_index, prover_index) in cases {
        assert_eq!(modular_index, prover_index);
    }
    assert_eq!(
        LookupTableKind::<XLEN>::COUNT,
        ProverLookupTables::<XLEN>::COUNT
    );
}
