[package]
name = "dory"
version = "1.0.0"
edition = "2021"
authors = ["Markos Georghiades <mgeorghiades@a16z.com>", "Jay White <jay@spaceandtime.io>"]
license = "Apache-2.0"
description = "A generic implementation of the Dory polynomial commitment scheme."
repository = "https://github.com/spaceandtimelabs/sxt-dory"
exclude = [".github", "README.md"]

[dependencies]
ark-bn254 = "0.5.0"
ark-ec = { version = "0.5.0", features= ["parallel"] }
ark-ff = { version = "0.5.0", features= ["parallel"] }
ark-serialize = "0.5.0"
ark-std = "0.5.0"
bincode = "1.3.3"
blake2 = "0.10.6"
digest = "0.10.7"
rayon = "1.10.0"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[lints.rust]
missing_docs = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
allow_attributes = "warn"
doc_markdown = "allow"
missing_docs_in_private_items = "warn"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]
