//! Host driver for the device Miller-loop kernels (W6).
//!
//! Two kernel shapes over the `fq12.metal` tower:
//!
//! - [`miller_table_partials`] — the stage-0 tier-2 shape: G1 points against
//!   host-PREPARED G2 line coefficients ([`flatten_prepared_coeffs`] lays
//!   them out step-major), several pairs per thread, one partial Miller
//!   value out per thread.
//! - [`miller_fly_partials`] — the stage-8 reduce-round shape: affine
//!   (G1, G2) pairs with the G2 preparation ladder run inline on the
//!   device, one pair per thread.
//! - [`miller_fly_indexed_partials`] — the stage-0 shape after W3: G1 points
//!   select affine G2 setup rows by index, avoiding the prepared table.
//!
//! Either way the batch Miller value is the exact Fq12 product of the
//! partials ([`product_of_partials`]): a multi-Miller loop over a pair set
//! equals the product of the loops over any partition (the shared squaring
//! ladder distributes — see `jolt_dory::tier2`), so ANY thread partition
//! reproduces `Bn254::multi_miller_loop` exactly, final exponentiation
//! staying on the CPU unchanged.
//!
//! The pairing constants the shaders need (ate digits, twist coefficients,
//! ½) are generated by [`pairing_preamble`] from arkworks' BN254
//! configuration at context construction — no limb value is hand-written,
//! and the structural facts the MSL specializes on (ξ = 9 + u, u² = −1,
//! positive x) are asserted before any pipeline is built.

use ark_bn254::{Bn254, Fq, Fq12, Fq2, Fq6, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ec::pairing::{MillerLoopOutput, Pairing};
use ark_ec::{AffineRepr, CurveGroup};
use ark_ff::{BigInt, Field, Fp6Config, One};
use dory::backends::arkworks::{ArkG1, ArkG2, ArkGT};

use super::error::MetalError;
use super::field::{FR_U32_LIMBS, G1_AFFINE_U32_STRIDE, G2_AFFINE_U32_STRIDE};
use super::runtime::{KernelId, MetalContext};

/// Arkworks' prepared G2 point (the line-coefficient vector).
pub type ArkG2Prepared = <Bn254 as Pairing>::G2Prepared;

/// u32 words per line coefficient (3 Fq2).
pub const ELL_COEFF_U32S: usize = 6 * FR_U32_LIMBS;

/// u32 words per Fq12 (device order = arkworks memory order).
pub const FQ12_U32S: usize = 12 * FR_U32_LIMBS;

/// Line coefficients per prepared pair: one per ate iteration, one more per
/// nonzero ate digit, two Frobenius addition steps.
pub fn ell_coeffs_per_pair() -> usize {
    let ate = <ark_bn254::Config as ark_ec::bn::BnConfig>::ATE_LOOP_COUNT;
    let nonzero = ate[..ate.len() - 1].iter().filter(|&&d| d != 0).count();
    (ate.len() - 1) + nonzero + 2
}

fn fq_mont_limbs(x: Fq) -> [u32; FR_U32_LIMBS] {
    let mut out = [0u32; FR_U32_LIMBS];
    for (i, w) in x.0 .0.iter().enumerate() {
        out[2 * i] = *w as u32;
        out[2 * i + 1] = (*w >> 32) as u32;
    }
    out
}

fn fq_from_mont_limbs(limbs: &[u32]) -> Fq {
    let mut words = [0u64; 4];
    for (i, w) in words.iter_mut().enumerate() {
        *w = u64::from(limbs[2 * i]) | (u64::from(limbs[2 * i + 1]) << 32);
    }
    Fq::new_unchecked(BigInt::new(words))
}

fn fq2_from_mont_limbs(limbs: &[u32]) -> Fq2 {
    Fq2::new(
        fq_from_mont_limbs(&limbs[..FR_U32_LIMBS]),
        fq_from_mont_limbs(&limbs[FR_U32_LIMBS..]),
    )
}

fn write_fq2(dst: &mut [u32], x: &Fq2) {
    dst[..FR_U32_LIMBS].copy_from_slice(&fq_mont_limbs(x.c0));
    dst[FR_U32_LIMBS..2 * FR_U32_LIMBS].copy_from_slice(&fq_mont_limbs(x.c1));
}

/// Rebuild one device Fq6 (6 Montgomery Fq limb runs, arkworks order).
pub fn fq6_from_device_limbs(limbs: &[u32]) -> Fq6 {
    debug_assert_eq!(limbs.len(), 6 * FR_U32_LIMBS);
    Fq6::new(
        fq2_from_mont_limbs(&limbs[..2 * FR_U32_LIMBS]),
        fq2_from_mont_limbs(&limbs[2 * FR_U32_LIMBS..4 * FR_U32_LIMBS]),
        fq2_from_mont_limbs(&limbs[4 * FR_U32_LIMBS..]),
    )
}

/// An Fq6's device words.
pub fn fq6_to_device_limbs(x: &Fq6) -> [u32; 6 * FR_U32_LIMBS] {
    let mut out = [0u32; 6 * FR_U32_LIMBS];
    for (i, c2) in [&x.c0, &x.c1, &x.c2].into_iter().enumerate() {
        write_fq2(
            &mut out[i * 2 * FR_U32_LIMBS..(i + 1) * 2 * FR_U32_LIMBS],
            c2,
        );
    }
    out
}

/// Rebuild one device Fq12 (12 Montgomery Fq limb runs, arkworks order).
pub fn fq12_from_device_limbs(limbs: &[u32]) -> Fq12 {
    debug_assert_eq!(limbs.len(), FQ12_U32S);
    Fq12::new(
        fq6_from_device_limbs(&limbs[..6 * FR_U32_LIMBS]),
        fq6_from_device_limbs(&limbs[6 * FR_U32_LIMBS..]),
    )
}

/// An Fq12's device words (test/bench input construction).
pub fn fq12_to_device_limbs(x: &Fq12) -> [u32; FQ12_U32S] {
    let mut out = [0u32; FQ12_U32S];
    for (i, c2) in [&x.c0.c0, &x.c0.c1, &x.c0.c2, &x.c1.c0, &x.c1.c1, &x.c1.c2]
        .into_iter()
        .enumerate()
    {
        write_fq2(
            &mut out[i * 2 * FR_U32_LIMBS..(i + 1) * 2 * FR_U32_LIMBS],
            c2,
        );
    }
    out
}

fn limb_array(limbs: &[u32]) -> String {
    let body: Vec<String> = limbs.iter().map(|l| format!("{l:#010x}u")).collect();
    format!("{{ {} }}", body.join(", "))
}

/// Pairing constants for the MSL preamble, read from arkworks' BN254
/// configuration. Asserts the structural facts the shaders bake in —
/// tower shape (ξ = 9 + u over u² = −1), positive x, and the coefficient
/// count against an actual arkworks preparation — so a config drift fails
/// at context construction, never as wrong arithmetic.
#[expect(
    clippy::expect_used,
    reason = "structural invariants of BN254 itself; violated only if the arkworks dep changes curves"
)]
pub(super) fn pairing_preamble() -> String {
    use std::fmt::Write as _;
    type Config = ark_bn254::Config;

    assert_eq!(
        <ark_bn254::Fq6Config as Fp6Config>::NONRESIDUE,
        Fq2::new(Fq::from(9u64), Fq::one()),
        "fq12.metal specializes ξ = 9 + u",
    );
    assert_eq!(
        <ark_bn254::Fq2Config as ark_ff::Fp2Config>::NONRESIDUE,
        -Fq::one(),
        "g2.metal's Fq2 arithmetic assumes u² = −1",
    );
    // The Miller kernels skip the negative-x conjugations.
    const _: () = assert!(!<ark_bn254::Config as ark_ec::bn::BnConfig>::X_IS_NEGATIVE);

    let ate = <Config as ark_ec::bn::BnConfig>::ATE_LOOP_COUNT;
    let coeffs = ell_coeffs_per_pair();
    let reference: ArkG2Prepared = G2Affine::generator().into();
    assert_eq!(
        reference.ell_coeffs.len(),
        coeffs,
        "emitted coefficient count must match arkworks' preparation",
    );

    let two_inv = Fq::from(2u64).inverse().expect("2 is invertible in Fq");
    let g2b = <ark_bn254::g2::Config as ark_ec::short_weierstrass::SWCurveConfig>::COEFF_B;
    let mqx = <Config as ark_ec::bn::BnConfig>::TWIST_MUL_BY_Q_X;
    let mqy = <Config as ark_ec::bn::BnConfig>::TWIST_MUL_BY_Q_Y;

    let mut out = String::with_capacity(2048);
    out.push_str("// Generated from arkworks BN254 config — never hand-edit.\n");
    let _ = writeln!(out, "#define JK_ATE_LEN {}u", ate.len() - 1);
    let digits: Vec<String> = ate[..ate.len() - 1]
        .iter()
        .map(|d| format!("{d}"))
        .collect();
    let _ = writeln!(
        out,
        "constant int JK_ATE[JK_ATE_LEN] = {{ {} }};",
        digits.join(", ")
    );
    let _ = writeln!(out, "#define JK_ELL_COEFFS {coeffs}u");
    let _ = writeln!(
        out,
        "constant uint FQ_TWO_INV[FR_LIMBS] = {};",
        limb_array(&fq_mont_limbs(two_inv))
    );
    for (name, value) in [
        ("JK_G2B_C0", g2b.c0),
        ("JK_G2B_C1", g2b.c1),
        ("JK_MQX_C0", mqx.c0),
        ("JK_MQX_C1", mqx.c1),
        ("JK_MQY_C0", mqy.c0),
        ("JK_MQY_C1", mqy.c1),
    ] {
        let _ = writeln!(
            out,
            "constant uint {name}[FR_LIMBS] = {};",
            limb_array(&fq_mont_limbs(value))
        );
    }
    out
}

/// Lay prepared line coefficients out step-major — coefficient `step` of
/// table row `row` at `(step·n_rows + row)·ELL_COEFF_U32S` — so
/// SIMD-adjacent threads (adjacent rows) stream contiguously. Every
/// prepared point must be non-infinity (infinity G2s carry no
/// coefficients; exclude them and their G1 partners before flattening).
pub fn flatten_prepared_coeffs(preps: &[&ArkG2Prepared], out: &mut Vec<u32>) {
    let n_rows = preps.len();
    let steps = ell_coeffs_per_pair();
    out.clear();
    out.resize(steps * n_rows * ELL_COEFF_U32S, 0);
    for (pair, prep) in preps.iter().enumerate() {
        assert!(!prep.infinity, "flatten: infinity G2 has no coefficients");
        assert_eq!(prep.ell_coeffs.len(), steps);
        for (step, coeff) in prep.ell_coeffs.iter().enumerate() {
            let at = (step * n_rows + pair) * ELL_COEFF_U32S;
            write_fq2(&mut out[at..at + 2 * FR_U32_LIMBS], &coeff.0);
            write_fq2(
                &mut out[at + 2 * FR_U32_LIMBS..at + 4 * FR_U32_LIMBS],
                &coeff.1,
            );
            write_fq2(
                &mut out[at + 4 * FR_U32_LIMBS..at + 6 * FR_U32_LIMBS],
                &coeff.2,
            );
        }
    }
}

/// View affine G1 points as the device `uint` stream (same contract as
/// [`super::g1::bases_as_u32s`]; identity's (0, 0) coordinates ARE the
/// device sentinel, so identities may be included).
pub(super) fn g1_points_as_u32s(points: &[G1Affine]) -> &[u32] {
    // SAFETY: layout pinned by the const asserts in `super::field`; every
    // bit pattern is a valid u32; same lifetime as `points`.
    unsafe {
        std::slice::from_raw_parts(
            points.as_ptr().cast::<u32>(),
            points.len() * G1_AFFINE_U32_STRIDE,
        )
    }
}

/// The multiplicative fold of the per-thread partial Miller values.
pub fn product_of_partials(partials: &[u32]) -> <Bn254 as Pairing>::TargetField {
    partials
        .chunks_exact(FQ12_U32S)
        .fold(Fq12::one(), |acc, limbs| {
            acc * fq12_from_device_limbs(limbs)
        })
}

/// Uniform `pairs_per_thread` segmentation — the test/bench convenience
/// for [`miller_table_partials`]' ragged segment interface.
pub fn uniform_seg_starts(n_pairs: usize, pairs_per_thread: usize) -> Vec<u32> {
    let n_threads = n_pairs.div_ceil(pairs_per_thread);
    (0..=n_threads)
        .map(|t| (t * pairs_per_thread).min(n_pairs) as u32)
        .collect()
}

/// The kernel's `[[buffer]]`/params contract, shared with the commit slot's
/// in-pipeline dispatch: pair `i` = `points[i]` against table row
/// `row_indices[i]`; thread `t` owns pairs
/// `seg_starts[t]..seg_starts[t + 1]` and writes one partial Miller value.
pub fn miller_table_params(n_threads: usize, n_rows: usize) -> Result<[u32; 2], MetalError> {
    Ok([
        u32::try_from(n_threads).map_err(|_| MetalError::Execution("thread count".into()))?,
        u32::try_from(n_rows).map_err(|_| MetalError::Execution("table rows".into()))?,
    ])
}

/// Dispatch the prepared-coefficient Miller kernel synchronously (the
/// test/bench path; the commit slot encodes the same dispatch inline to
/// overlap its CPU share). Returns the raw partial-f limb buffer (one Fq12
/// per thread).
pub fn miller_table_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    row_indices: &[u32],
    seg_starts: &[u32],
    coeffs: &[u32],
    n_rows: usize,
) -> Result<Vec<u32>, MetalError> {
    assert_eq!(points.len(), row_indices.len());
    assert_eq!(
        coeffs.len(),
        ell_coeffs_per_pair() * n_rows * ELL_COEFF_U32S
    );
    let n_threads = seg_starts.len() - 1;
    let ps_buf = ctx.wrap_slice(g1_points_as_u32s(points))?;
    let idx_buf = ctx.wrap_slice(row_indices)?;
    let seg_buf = ctx.wrap_slice(seg_starts)?;
    let coeffs_buf = ctx.wrap_slice(coeffs)?;
    let out_buf = ctx.alloc_u32s(n_threads * FQ12_U32S)?;
    ctx.run_once(
        KernelId::MillerTable,
        &miller_table_params(n_threads, n_rows)?,
        &[&ps_buf, &idx_buf, &seg_buf, &coeffs_buf, &out_buf],
        n_threads,
    )?;
    let mut partials = vec![0u32; n_threads * FQ12_U32S];
    out_buf.copy_to_u32s(&mut partials);
    Ok(partials)
}

/// View affine G2 points as the device `uint` stream (identities included —
/// the (0, 0) sentinel skips them on device, as arkworks' filter does).
pub(super) fn g2_points_as_u32s(points: &[G2Affine]) -> &[u32] {
    // SAFETY: layout pinned by the const asserts in `super::field`.
    unsafe {
        std::slice::from_raw_parts(
            points.as_ptr().cast::<u32>(),
            points.len() * G2_AFFINE_U32_STRIDE,
        )
    }
}

/// Dispatch the on-the-fly Miller kernel over affine pairs (one per
/// thread); returns the raw partial-f limb buffer.
pub fn miller_fly_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    qs: &[G2Affine],
) -> Result<Vec<u32>, MetalError> {
    assert_eq!(points.len(), qs.len());
    let n_pairs = points.len();
    let ps_buf = ctx.wrap_slice(g1_points_as_u32s(points))?;
    let qs_buf = ctx.wrap_slice(g2_points_as_u32s(qs))?;
    let out_buf = ctx.alloc_u32s(n_pairs * FQ12_U32S)?;
    let params = [u32::try_from(n_pairs).map_err(|_| MetalError::Execution("pair count".into()))?];
    ctx.run_once(
        KernelId::MillerFly,
        &params,
        &[&ps_buf, &qs_buf, &out_buf],
        n_pairs,
    )?;
    let mut partials = vec![0u32; n_pairs * FQ12_U32S];
    out_buf.copy_to_u32s(&mut partials);
    Ok(partials)
}

/// Stage-0 twin of [`miller_fly_partials`]: G2 setup rows remain shared,
/// while `row_indices` selects one for each G1 point. This avoids expanding
/// repeated setup rows or building the prepared-coefficient table.
pub fn miller_fly_indexed_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    row_indices: &[u32],
    qs: &[G2Affine],
) -> Result<Vec<u32>, MetalError> {
    assert_eq!(points.len(), row_indices.len());
    assert!(
        row_indices.iter().all(|&row| (row as usize) < qs.len()),
        "Miller row index exceeds the G2 table"
    );
    let n_pairs = points.len();
    let ps_buf = ctx.wrap_slice(g1_points_as_u32s(points))?;
    let row_indices_buf = ctx.wrap_slice(row_indices)?;
    let qs_buf = ctx.wrap_slice(g2_points_as_u32s(qs))?;
    let out_buf = ctx.alloc_u32s(n_pairs * FQ12_U32S)?;
    let params = [u32::try_from(n_pairs).map_err(|_| MetalError::Execution("pair count".into()))?];
    ctx.run_once(
        KernelId::MillerFlyIndexed,
        &params,
        &[&ps_buf, &row_indices_buf, &qs_buf, &out_buf],
        n_pairs,
    )?;
    let mut partials = vec![0u32; n_pairs * FQ12_U32S];
    out_buf.copy_to_u32s(&mut partials);
    Ok(partials)
}

/// Per-pair Fq-mul-equivalents fed to [`super::metal_gate`] so the shared
/// `JOLT_METAL_MIN_TERMS` scale keeps meaning "work items": the shift
/// calibrates the default threshold (2^16) to a 2048-pair floor. Below
/// it, per-thread ate-ladder latency dominates (the W5a
/// ladder-latency-floor lesson) while dory's internally parallel CPU
/// multi-pair shrinks linearly. In-pipeline sweep (sha2-chain @2^22,
/// stage-8 wall): hook off → 2.20/2.18 s, ≥4096 pairs → 2.12,
/// **≥2048 → 2.02/2.02**, ≥1024 → 2.11 (the third reduce round loses).
pub(super) const MILLER_FLY_WORK_PER_PAIR_LOG2: usize = 5;

/// The stage-8 device multi-pairing — dory's `multi_pair*` hook. Serves
/// the call with the exact GT the CPU path computes (device Miller
/// partials → Fq12 product → arkworks final exponentiation) or declines
/// (`None`) below the gate or on any device error, letting dory's CPU
/// path run. Both paths batch-normalize the same projective inputs, so
/// the device sees the same affine pairs (identities included — the
/// sentinel skip mirrors the CPU pair filter).
#[tracing::instrument(skip_all, name = "miller_fly_device", fields(pairs = ps.len()))]
pub fn multi_pair_device(ps: &[ArkG1], qs: &[ArkG2]) -> Option<ArkGT> {
    if !super::metal_gate("miller_fly", ps.len() << MILLER_FLY_WORK_PER_PAIR_LOG2) {
        return None;
    }
    let ctx = MetalContext::global().ok()?;
    let ps_affine = G1Projective::normalize_batch(&ps.iter().map(|p| p.0).collect::<Vec<_>>());
    let qs_affine = G2Projective::normalize_batch(&qs.iter().map(|q| q.0).collect::<Vec<_>>());
    let partials = match miller_fly_partials(ctx, &ps_affine, &qs_affine) {
        Ok(partials) => partials,
        Err(error) => {
            tracing::warn!(%error, "device multi-pair failed; falling back to the CPU path");
            return None;
        }
    };
    super::testing::note_miller_dispatch();
    let miller = product_of_partials(&partials);
    // A `None` final exponentiation (zero Miller product) cannot arise from
    // well-formed pairs; decline and let the CPU path handle it identically.
    let gt = Bn254::final_exponentiation(MillerLoopOutput(miller))?;
    Some(ArkGT(gt))
}

#[cfg(test)]
#[expect(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests: fail loudly"
)]
mod tests {
    use ark_ec::pairing::MillerLoopOutput;
    use ark_ec::CurveGroup;
    use ark_ff::{UniformRand, Zero};
    use rand_chacha::ChaCha20Rng;
    use rand_core::SeedableRng;

    use super::super::testing::gpu_lock;
    use super::*;

    fn rng() -> ChaCha20Rng {
        ChaCha20Rng::seed_from_u64(0x77_6f)
    }

    /// Arithmetic edge values lifted through the tower: 0, ±1, and a
    /// random element per slot position (each nonresidue path in
    /// isolation).
    fn edge_fq12s(rng: &mut ChaCha20Rng) -> Vec<Fq12> {
        let mut out = vec![Fq12::zero(), Fq12::one(), -Fq12::one()];
        for slot in 0..12 {
            let mut limbs = [Fq::zero(); 12];
            limbs[slot] = Fq::rand(rng);
            let fq2 = |i: usize| Fq2::new(limbs[2 * i], limbs[2 * i + 1]);
            out.push(Fq12::new(
                Fq6::new(fq2(0), fq2(1), fq2(2)),
                Fq6::new(fq2(3), fq2(4), fq2(5)),
            ));
        }
        out
    }

    #[test]
    fn fq6_mul_sqr_match_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let mut xs: Vec<Fq6> = edge_fq12s(&mut rng).iter().map(|f| f.c0).collect();
        xs.extend((0..256).map(|_| Fq6::rand(&mut rng)));
        let ys: Vec<Fq6> = xs.iter().rev().copied().collect();
        let words = 6 * FR_U32_LIMBS;

        let x_limbs: Vec<u32> = xs.iter().flat_map(fq6_to_device_limbs).collect();
        let y_limbs: Vec<u32> = ys.iter().flat_map(fq6_to_device_limbs).collect();
        let x_buf = ctx.wrap_slice(&x_limbs).unwrap();
        let y_buf = ctx.wrap_slice(&y_limbs).unwrap();
        let out_buf = ctx.alloc_u32s(xs.len() * words).unwrap();
        ctx.run_once(
            KernelId::Fq6Mul,
            &[xs.len() as u32, 1],
            &[&x_buf, &y_buf, &out_buf],
            xs.len(),
        )
        .unwrap();
        let mut out = vec![0u32; xs.len() * words];
        out_buf.copy_to_u32s(&mut out);
        for (i, (x, y)) in xs.iter().zip(&ys).enumerate() {
            let got = fq6_from_device_limbs(&out[i * words..(i + 1) * words]);
            assert_eq!(got, *x * y, "fq6 mul mismatch at {i}");
        }

        let sqr_buf = ctx.alloc_u32s(xs.len() * words).unwrap();
        ctx.run_once(
            KernelId::Fq6Sqr,
            &[xs.len() as u32, 1],
            &[&x_buf, &sqr_buf],
            xs.len(),
        )
        .unwrap();
        sqr_buf.copy_to_u32s(&mut out);
        for (i, x) in xs.iter().enumerate() {
            let got = fq6_from_device_limbs(&out[i * words..(i + 1) * words]);
            assert_eq!(got, x.square(), "fq6 sqr mismatch at {i}");
        }
    }

    #[test]
    fn fq12_mul_sqr_match_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let mut xs = edge_fq12s(&mut rng);
        xs.extend((0..256).map(|_| Fq12::rand(&mut rng)));
        let ys: Vec<Fq12> = xs.iter().rev().copied().collect();

        let x_limbs: Vec<u32> = xs.iter().flat_map(fq12_to_device_limbs).collect();
        let y_limbs: Vec<u32> = ys.iter().flat_map(fq12_to_device_limbs).collect();
        let x_buf = ctx.wrap_slice(&x_limbs).unwrap();
        let y_buf = ctx.wrap_slice(&y_limbs).unwrap();
        let out_buf = ctx.alloc_u32s(xs.len() * FQ12_U32S).unwrap();
        ctx.run_once(
            KernelId::Fq12Mul,
            &[xs.len() as u32, 1],
            &[&x_buf, &y_buf, &out_buf],
            xs.len(),
        )
        .unwrap();
        let mut out = vec![0u32; xs.len() * FQ12_U32S];
        out_buf.copy_to_u32s(&mut out);
        for (i, (x, y)) in xs.iter().zip(&ys).enumerate() {
            let got = fq12_from_device_limbs(&out[i * FQ12_U32S..(i + 1) * FQ12_U32S]);
            assert_eq!(got, *x * y, "fq12 mul mismatch at {i}");
        }

        let sqr_buf = ctx.alloc_u32s(xs.len() * FQ12_U32S).unwrap();
        ctx.run_once(
            KernelId::Fq12Sqr,
            &[xs.len() as u32, 1],
            &[&x_buf, &sqr_buf],
            xs.len(),
        )
        .unwrap();
        sqr_buf.copy_to_u32s(&mut out);
        for (i, x) in xs.iter().enumerate() {
            let got = fq12_from_device_limbs(&out[i * FQ12_U32S..(i + 1) * FQ12_U32S]);
            assert_eq!(got, x.square(), "fq12 sqr mismatch at {i}");
        }
    }

    #[test]
    fn fq12_mul034_matches_arkworks() {
        let _lock = gpu_lock();
        let mut rng = rng();
        let n = 256usize;
        let fs: Vec<Fq12> = (0..n).map(|_| Fq12::rand(&mut rng)).collect();
        let coeffs: Vec<(Fq2, Fq2, Fq2)> = (0..n)
            .map(|_| {
                (
                    Fq2::rand(&mut rng),
                    Fq2::rand(&mut rng),
                    Fq2::rand(&mut rng),
                )
            })
            .collect();
        let points: Vec<G1Affine> = (0..n)
            .map(|_| ark_bn254::G1Projective::rand(&mut rng).into_affine())
            .collect();

        let ctx = MetalContext::global().unwrap();
        let f_limbs: Vec<u32> = fs.iter().flat_map(fq12_to_device_limbs).collect();
        let mut c_limbs = vec![0u32; n * ELL_COEFF_U32S];
        for (i, c) in coeffs.iter().enumerate() {
            let at = i * ELL_COEFF_U32S;
            write_fq2(&mut c_limbs[at..at + 16], &c.0);
            write_fq2(&mut c_limbs[at + 16..at + 32], &c.1);
            write_fq2(&mut c_limbs[at + 32..at + 48], &c.2);
        }
        let f_buf = ctx.wrap_slice(&f_limbs).unwrap();
        let c_buf = ctx.wrap_slice(&c_limbs).unwrap();
        let p_buf = ctx.wrap_slice(g1_points_as_u32s(&points)).unwrap();
        let out_buf = ctx.alloc_u32s(n * FQ12_U32S).unwrap();
        ctx.run_once(
            KernelId::Fq12Mul034,
            &[n as u32, 1],
            &[&f_buf, &c_buf, &p_buf, &out_buf],
            n,
        )
        .unwrap();
        let mut out = vec![0u32; n * FQ12_U32S];
        out_buf.copy_to_u32s(&mut out);

        for i in 0..n {
            let mut expected = fs[i];
            let mut c0 = coeffs[i].0;
            let mut c1 = coeffs[i].1;
            c0.mul_assign_by_fp(&points[i].y);
            c1.mul_assign_by_fp(&points[i].x);
            expected.mul_by_034(&c0, &c1, &coeffs[i].2);
            let got = fq12_from_device_limbs(&out[i * FQ12_U32S..(i + 1) * FQ12_U32S]);
            assert_eq!(got, expected, "mul034 mismatch at {i}");
        }
    }

    fn reference_miller(ps: &[G1Affine], qs: &[G2Affine]) -> Fq12 {
        let MillerLoopOutput(f) = Bn254::multi_miller_loop(ps.iter().copied(), qs.iter().copied());
        f
    }

    fn random_pairs(rng: &mut ChaCha20Rng, n: usize) -> (Vec<G1Affine>, Vec<G2Affine>) {
        let ps = (0..n)
            .map(|_| ark_bn254::G1Projective::rand(rng).into_affine())
            .collect();
        let qs = (0..n)
            .map(|_| ark_bn254::G2Projective::rand(rng).into_affine())
            .collect();
        (ps, qs)
    }

    fn table_product(ps: &[G1Affine], qs: &[G2Affine], ppt: usize) -> Fq12 {
        let ctx = MetalContext::global().expect("metal context");
        let preps: Vec<ArkG2Prepared> = qs.iter().map(|q| (*q).into()).collect();
        let refs: Vec<&ArkG2Prepared> = preps.iter().collect();
        let mut coeffs = Vec::new();
        flatten_prepared_coeffs(&refs, &mut coeffs);
        let indices: Vec<u32> = (0..ps.len() as u32).collect();
        let segs = uniform_seg_starts(ps.len(), ppt);
        let partials = miller_table_partials(ctx, ps, &indices, &segs, &coeffs, qs.len()).unwrap();
        product_of_partials(&partials)
    }

    /// Table-kernel Miller product vs arkworks: random pairs at several
    /// pairs-per-thread geometries (including a non-dividing one), a
    /// single pair, negated points, and G1 identity sentinels.
    #[test]
    fn miller_table_matches_arkworks() {
        let _lock = gpu_lock();
        let mut rng = rng();

        let (ps, qs) = random_pairs(&mut rng, 37);
        let expected = reference_miller(&ps, &qs);
        for ppt in [1usize, 4, 8] {
            assert_eq!(table_product(&ps, &qs, ppt), expected, "ppt {ppt}");
        }

        let (p1, q1) = random_pairs(&mut rng, 1);
        assert_eq!(table_product(&p1, &q1, 4), reference_miller(&p1, &q1));

        let neg: Vec<G1Affine> = ps.iter().map(|p| -*p).collect();
        assert_eq!(table_product(&neg, &qs, 4), reference_miller(&neg, &qs));

        // Identity G1s interleaved: arkworks filters the pair, the device
        // skips it via the (0, 0) sentinel — same product.
        let mut with_id = ps.clone();
        with_id[0] = G1Affine::identity();
        with_id[19] = G1Affine::identity();
        assert_eq!(
            table_product(&with_id, &qs, 4),
            reference_miller(&with_id, &qs)
        );
    }

    /// Production-scale pin: a 2^15-pair batch (one stage-0 tier-2 column
    /// at 2^22) against one G2 prep shared arkworks↔device, sentinels
    /// included — the exact shape the commit slot dispatches.
    #[test]
    fn miller_table_matches_arkworks_at_scale() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let n = 1usize << 15;

        // Cheap distinct G1s: a small random set permuted, plus scattered
        // identity sentinels (Miller cost is data-oblivious; the reference
        // cost is what bounds this test).
        let seeds: Vec<G1Affine> = (0..64)
            .map(|_| ark_bn254::G1Projective::rand(&mut rng).into_affine())
            .collect();
        let mut ps: Vec<G1Affine> = (0..n).map(|i| seeds[(i * 31 + 7) % 64]).collect();
        for i in (0..n).step_by(1013) {
            ps[i] = G1Affine::identity();
        }
        let q_seeds: Vec<G2Affine> = (0..64)
            .map(|_| ark_bn254::G2Projective::rand(&mut rng).into_affine())
            .collect();
        let qs: Vec<G2Affine> = (0..n).map(|i| q_seeds[(i * 17 + 3) % 64]).collect();

        let preps: Vec<ArkG2Prepared> = qs.iter().map(|q| (*q).into()).collect();
        let refs: Vec<&ArkG2Prepared> = preps.iter().collect();
        let mut coeffs = Vec::new();
        flatten_prepared_coeffs(&refs, &mut coeffs);
        let indices: Vec<u32> = (0..n as u32).collect();
        let segs = uniform_seg_starts(n, 8);
        let partials = miller_table_partials(ctx, &ps, &indices, &segs, &coeffs, n).unwrap();
        let device = product_of_partials(&partials);

        let live: Vec<usize> = (0..n).filter(|i| !ps[*i].is_zero()).collect();
        let MillerLoopOutput(expected) = Bn254::multi_miller_loop(
            live.iter().map(|&i| ps[i]),
            live.iter().map(|&i| preps[i].clone()),
        );
        assert_eq!(device, expected);
    }

    /// The commit-slot shape: a SHARED coefficient table addressed through
    /// repeating row indices, ragged per-thread segments, and per-segment
    /// partial folds — each segment's product must equal arkworks over
    /// exactly its pair subset.
    #[test]
    fn miller_table_shared_rows_ragged_segments() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();

        let n_rows = 24usize;
        let qs: Vec<G2Affine> = (0..n_rows)
            .map(|_| ark_bn254::G2Projective::rand(&mut rng).into_affine())
            .collect();
        let preps: Vec<ArkG2Prepared> = qs.iter().map(|q| (*q).into()).collect();
        let refs: Vec<&ArkG2Prepared> = preps.iter().collect();
        let mut coeffs = Vec::new();
        flatten_prepared_coeffs(&refs, &mut coeffs);

        let n = 173usize;
        let ps: Vec<G1Affine> = (0..n)
            .map(|_| ark_bn254::G1Projective::rand(&mut rng).into_affine())
            .collect();
        let indices: Vec<u32> = (0..n).map(|i| ((i * 13 + 5) % n_rows) as u32).collect();

        // Ragged segments: lengths cycle 1..=5.
        let mut segs = vec![0u32];
        let mut at = 0usize;
        let mut len = 1usize;
        while at < n {
            at = (at + len).min(n);
            segs.push(at as u32);
            len = len % 5 + 1;
        }

        let partials = miller_table_partials(ctx, &ps, &indices, &segs, &coeffs, n_rows).unwrap();
        for (t, window) in segs.windows(2).enumerate() {
            let (start, end) = (window[0] as usize, window[1] as usize);
            let MillerLoopOutput(expected) = Bn254::multi_miller_loop(
                ps[start..end].iter().copied(),
                indices[start..end]
                    .iter()
                    .map(|&r| preps[r as usize].clone()),
            );
            let got = product_of_partials(&partials[t * FQ12_U32S..(t + 1) * FQ12_U32S]);
            assert_eq!(got, expected, "segment {t} ({start}..{end})");
        }
    }

    /// The dory hook: `multi_pair_device` must produce the exact GT of
    /// dory's CPU `multi_pair` (final exponentiation included) on
    /// projective inputs with identities mixed in.
    #[test]
    fn multi_pair_device_matches_dory_cpu() {
        let _lock = gpu_lock();
        // nextest gives each test its own process; force the gate open at
        // test sizes.
        std::env::set_var("JOLT_METAL_MIN_TERMS_MILLER_FLY", "1");
        let mut rng = rng();
        let n = 61usize;
        let mut ps: Vec<ArkG1> = (0..n)
            .map(|_| ArkG1(ark_bn254::G1Projective::rand(&mut rng)))
            .collect();
        let mut qs: Vec<ArkG2> = (0..n)
            .map(|_| ArkG2(ark_bn254::G2Projective::rand(&mut rng)))
            .collect();
        ps[7] = ArkG1(ark_bn254::G1Projective::zero());
        qs[23] = ArkG2(ark_bn254::G2Projective::zero());

        let before = super::super::testing::miller_dispatch_count();
        let device = multi_pair_device(&ps, &qs).expect("gate forced open");
        assert!(
            super::super::testing::miller_dispatch_count() > before,
            "the hook silently fell back"
        );
        let cpu = <dory::backends::arkworks::BN254 as
            dory::primitives::arithmetic::PairingCurve>::multi_pair(&ps, &qs);
        assert_eq!(device.0, cpu.0);
    }

    /// Fly-kernel Miller product vs arkworks: random pairs, single pair,
    /// negated G2s, and identity sentinels on both sides.
    #[test]
    fn miller_fly_matches_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();

        let fly = |ps: &[G1Affine], qs: &[G2Affine]| {
            product_of_partials(&miller_fly_partials(ctx, ps, qs).unwrap())
        };

        let (ps, qs) = random_pairs(&mut rng, 37);
        assert_eq!(fly(&ps, &qs), reference_miller(&ps, &qs));

        let (p1, q1) = random_pairs(&mut rng, 1);
        assert_eq!(fly(&p1, &q1), reference_miller(&p1, &q1));

        let neg_q: Vec<G2Affine> = qs.iter().map(|q| -*q).collect();
        assert_eq!(fly(&ps, &neg_q), reference_miller(&ps, &neg_q));

        let mut ps_id = ps.clone();
        ps_id[3] = G1Affine::identity();
        let mut qs_id = qs.clone();
        qs_id[11] = G2Affine::identity();
        assert_eq!(fly(&ps_id, &qs_id), reference_miller(&ps_id, &qs_id));
    }

    #[test]
    fn miller_fly_indexed_matches_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let (mut ps, qs) = random_pairs(&mut rng, 73);
        let mut table = qs[..17].to_vec();
        ps[19] = G1Affine::identity();
        table[5] = G2Affine::identity();
        let indices: Vec<u32> = (0..ps.len())
            .map(|i| ((i * 11 + 3) % table.len()) as u32)
            .collect();
        let selected: Vec<G2Affine> = indices.iter().map(|&row| table[row as usize]).collect();
        let got =
            product_of_partials(&miller_fly_indexed_partials(ctx, &ps, &indices, &table).unwrap());
        assert_eq!(got, reference_miller(&ps, &selected));
    }
}
