//! Host driver for the device Miller-loop kernels (W6).
//!
//! Two kernel shapes over the `fq12.metal` tower:
//!
//! - [`miller_table_partials`] — the stage-0 tier-2 shape: G1 points against
//!   host-PREPARED G2 line coefficients ([`flatten_prepared_coeffs`] lays
//!   them out step-major), several pairs per thread, one partial Miller
//!   value out per thread.
//! - [`miller_fly_partials`] — the stage-8 reduce-round shape: affine
//!   (G1, G2) pairs with the G2 preparation ladder run inline on the
//!   device, one pair per thread.
//! - [`miller_fly_indexed_partials`] — the stage-0 shape after W3: G1 points
//!   select affine G2 setup rows by index, avoiding the prepared table.
//!
//! Either way the batch Miller value is the exact Fq12 product of the
//! partials ([`product_of_partials`]): a multi-Miller loop over a pair set
//! equals the product of the loops over any partition (the shared squaring
//! ladder distributes — see `jolt_dory::tier2`), so ANY thread partition
//! reproduces `Bn254::multi_miller_loop` exactly, final exponentiation
//! staying on the CPU unchanged.
//!
//! The pairing constants the shaders need (ate digits, twist coefficients,
//! ½) are generated by [`pairing_preamble`] from arkworks' BN254
//! configuration at context construction — no limb value is hand-written,
//! and the structural facts the MSL specializes on (ξ = 9 + u, u² = −1,
//! positive x) are asserted before any pipeline is built.

use ark_bn254::{Bn254, Fq, Fq12, Fq2, Fq6, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ec::pairing::{MillerLoopOutput, Pairing};
use ark_ec::{AffineRepr, CurveGroup};
use ark_ff::{BigInt, Field, Fp6Config, One};
pub use dory::backends::arkworks::{ArkG1, ArkG2, ArkGT};

use super::error::MetalError;
use super::field::{FR_U32_LIMBS, G1_AFFINE_U32_STRIDE, G2_AFFINE_U32_STRIDE};
use super::runtime::{KernelId, MetalContext};

/// Arkworks' prepared G2 point (the line-coefficient vector).
pub type ArkG2Prepared = <Bn254 as Pairing>::G2Prepared;

/// u32 words per line coefficient (3 Fq2).
pub const ELL_COEFF_U32S: usize = 6 * FR_U32_LIMBS;

/// u32 words per Fq12 (device order = arkworks memory order).
pub const FQ12_U32S: usize = 12 * FR_U32_LIMBS;

/// Line coefficients per prepared pair: one per ate iteration, one more per
/// nonzero ate digit, two Frobenius addition steps.
pub fn ell_coeffs_per_pair() -> usize {
    let ate = <ark_bn254::Config as ark_ec::bn::BnConfig>::ATE_LOOP_COUNT;
    let nonzero = ate[..ate.len() - 1].iter().filter(|&&d| d != 0).count();
    (ate.len() - 1) + nonzero + 2
}

fn fq_mont_limbs(x: Fq) -> [u32; FR_U32_LIMBS] {
    let mut out = [0u32; FR_U32_LIMBS];
    for (i, w) in x.0 .0.iter().enumerate() {
        out[2 * i] = *w as u32;
        out[2 * i + 1] = (*w >> 32) as u32;
    }
    out
}

fn fq_from_mont_limbs(limbs: &[u32]) -> Fq {
    let mut words = [0u64; 4];
    for (i, w) in words.iter_mut().enumerate() {
        *w = u64::from(limbs[2 * i]) | (u64::from(limbs[2 * i + 1]) << 32);
    }
    Fq::new_unchecked(BigInt::new(words))
}

fn fq2_from_mont_limbs(limbs: &[u32]) -> Fq2 {
    Fq2::new(
        fq_from_mont_limbs(&limbs[..FR_U32_LIMBS]),
        fq_from_mont_limbs(&limbs[FR_U32_LIMBS..]),
    )
}

fn write_fq2(dst: &mut [u32], x: &Fq2) {
    dst[..FR_U32_LIMBS].copy_from_slice(&fq_mont_limbs(x.c0));
    dst[FR_U32_LIMBS..2 * FR_U32_LIMBS].copy_from_slice(&fq_mont_limbs(x.c1));
}

/// Rebuild one device Fq6 (6 Montgomery Fq limb runs, arkworks order).
pub fn fq6_from_device_limbs(limbs: &[u32]) -> Fq6 {
    debug_assert_eq!(limbs.len(), 6 * FR_U32_LIMBS);
    Fq6::new(
        fq2_from_mont_limbs(&limbs[..2 * FR_U32_LIMBS]),
        fq2_from_mont_limbs(&limbs[2 * FR_U32_LIMBS..4 * FR_U32_LIMBS]),
        fq2_from_mont_limbs(&limbs[4 * FR_U32_LIMBS..]),
    )
}

/// An Fq6's device words.
pub fn fq6_to_device_limbs(x: &Fq6) -> [u32; 6 * FR_U32_LIMBS] {
    let mut out = [0u32; 6 * FR_U32_LIMBS];
    for (i, c2) in [&x.c0, &x.c1, &x.c2].into_iter().enumerate() {
        write_fq2(
            &mut out[i * 2 * FR_U32_LIMBS..(i + 1) * 2 * FR_U32_LIMBS],
            c2,
        );
    }
    out
}

/// Rebuild one device Fq12 (12 Montgomery Fq limb runs, arkworks order).
pub fn fq12_from_device_limbs(limbs: &[u32]) -> Fq12 {
    debug_assert_eq!(limbs.len(), FQ12_U32S);
    Fq12::new(
        fq6_from_device_limbs(&limbs[..6 * FR_U32_LIMBS]),
        fq6_from_device_limbs(&limbs[6 * FR_U32_LIMBS..]),
    )
}

/// An Fq12's device words (test/bench input construction).
pub fn fq12_to_device_limbs(x: &Fq12) -> [u32; FQ12_U32S] {
    let mut out = [0u32; FQ12_U32S];
    for (i, c2) in [&x.c0.c0, &x.c0.c1, &x.c0.c2, &x.c1.c0, &x.c1.c1, &x.c1.c2]
        .into_iter()
        .enumerate()
    {
        write_fq2(
            &mut out[i * 2 * FR_U32_LIMBS..(i + 1) * 2 * FR_U32_LIMBS],
            c2,
        );
    }
    out
}

fn limb_array(limbs: &[u32]) -> String {
    let body: Vec<String> = limbs.iter().map(|l| format!("{l:#010x}u")).collect();
    format!("{{ {} }}", body.join(", "))
}

/// Pairing constants for the MSL preamble, read from arkworks' BN254
/// configuration. Asserts the structural facts the shaders bake in —
/// tower shape (ξ = 9 + u over u² = −1), positive x, and the coefficient
/// count against an actual arkworks preparation — so a config drift fails
/// at context construction, never as wrong arithmetic.
#[expect(
    clippy::expect_used,
    reason = "structural invariants of BN254 itself; violated only if the arkworks dep changes curves"
)]
pub(super) fn pairing_preamble() -> String {
    use std::fmt::Write as _;
    type Config = ark_bn254::Config;

    assert_eq!(
        <ark_bn254::Fq6Config as Fp6Config>::NONRESIDUE,
        Fq2::new(Fq::from(9u64), Fq::one()),
        "fq12.metal specializes ξ = 9 + u",
    );
    assert_eq!(
        <ark_bn254::Fq2Config as ark_ff::Fp2Config>::NONRESIDUE,
        -Fq::one(),
        "g2.metal's Fq2 arithmetic assumes u² = −1",
    );
    // The Miller kernels skip the negative-x conjugations.
    const _: () = assert!(!<ark_bn254::Config as ark_ec::bn::BnConfig>::X_IS_NEGATIVE);

    let ate = <Config as ark_ec::bn::BnConfig>::ATE_LOOP_COUNT;
    let coeffs = ell_coeffs_per_pair();
    let reference: ArkG2Prepared = G2Affine::generator().into();
    assert_eq!(
        reference.ell_coeffs.len(),
        coeffs,
        "emitted coefficient count must match arkworks' preparation",
    );

    let two_inv = Fq::from(2u64).inverse().expect("2 is invertible in Fq");
    let g2b = <ark_bn254::g2::Config as ark_ec::short_weierstrass::SWCurveConfig>::COEFF_B;
    let mqx = <Config as ark_ec::bn::BnConfig>::TWIST_MUL_BY_Q_X;
    let mqy = <Config as ark_ec::bn::BnConfig>::TWIST_MUL_BY_Q_Y;

    let mut out = String::with_capacity(2048);
    out.push_str("// Generated from arkworks BN254 config — never hand-edit.\n");
    let _ = writeln!(out, "#define JK_ATE_LEN {}u", ate.len() - 1);
    let digits: Vec<String> = ate[..ate.len() - 1]
        .iter()
        .map(|d| format!("{d}"))
        .collect();
    let _ = writeln!(
        out,
        "constant int JK_ATE[JK_ATE_LEN] = {{ {} }};",
        digits.join(", ")
    );
    let _ = writeln!(out, "#define JK_ELL_COEFFS {coeffs}u");
    let _ = writeln!(
        out,
        "constant uint FQ_TWO_INV[FR_LIMBS] = {};",
        limb_array(&fq_mont_limbs(two_inv))
    );
    for (name, value) in [
        ("JK_G2B_C0", g2b.c0),
        ("JK_G2B_C1", g2b.c1),
        ("JK_MQX_C0", mqx.c0),
        ("JK_MQX_C1", mqx.c1),
        ("JK_MQY_C0", mqy.c0),
        ("JK_MQY_C1", mqy.c1),
    ] {
        let _ = writeln!(
            out,
            "constant uint {name}[FR_LIMBS] = {};",
            limb_array(&fq_mont_limbs(value))
        );
    }
    out
}

/// Lay prepared line coefficients out step-major — coefficient `step` of
/// table row `row` at `(step·n_rows + row)·ELL_COEFF_U32S` — so
/// SIMD-adjacent threads (adjacent rows) stream contiguously. Every
/// prepared point must be non-infinity (infinity G2s carry no
/// coefficients; exclude them and their G1 partners before flattening).
pub fn flatten_prepared_coeffs(preps: &[&ArkG2Prepared], out: &mut Vec<u32>) {
    let n_rows = preps.len();
    let steps = ell_coeffs_per_pair();
    for prep in preps {
        assert!(!prep.infinity, "flatten: infinity G2 has no coefficients");
        assert_eq!(prep.ell_coeffs.len(), steps);
    }
    out.clear();
    out.resize(steps * n_rows * ELL_COEFF_U32S, 0);
    if n_rows == 0 {
        return;
    }
    // Each step's rows form one contiguous slice — parallelize over steps
    // (a 2.2 GiB layout write at the 2^27 row count).
    let write_step = |(step, chunk): (usize, &mut [u32])| {
        for (pair, prep) in preps.iter().enumerate() {
            let at = pair * ELL_COEFF_U32S;
            let coeff = &prep.ell_coeffs[step];
            write_fq2(&mut chunk[at..at + 2 * FR_U32_LIMBS], &coeff.0);
            write_fq2(
                &mut chunk[at + 2 * FR_U32_LIMBS..at + 4 * FR_U32_LIMBS],
                &coeff.1,
            );
            write_fq2(
                &mut chunk[at + 4 * FR_U32_LIMBS..at + 6 * FR_U32_LIMBS],
                &coeff.2,
            );
        }
    };
    #[cfg(feature = "parallel")]
    {
        use rayon::prelude::*;
        out.par_chunks_mut(n_rows * ELL_COEFF_U32S)
            .enumerate()
            .for_each(write_step);
    }
    #[cfg(not(feature = "parallel"))]
    out.chunks_mut(n_rows * ELL_COEFF_U32S)
        .enumerate()
        .for_each(write_step);
}

/// One bounded-residency Miller dispatch's coefficient tile (W15): the
/// batch's referenced table rows gathered into a compact step-major table
/// of width `unique.len()`, plus each pair's tile-local row. Identical
/// coefficient values reach the kernel at identical pair positions, so the
/// per-thread partials are bit-equal to a full-table dispatch — only the
/// bytes the device can touch shrink from O(table rows) to O(batch).
/// Buffers recycle across dispatches (the backing must stay address-stable
/// while wrapped — `Vec` heap storage is).
#[derive(Default)]
pub struct MillerTile {
    pub coeffs: Vec<u32>,
    pub local_rows: Vec<u32>,
    unique: Vec<u32>,
}

impl MillerTile {
    /// Gather `row_indices`' rows of `preps` into this tile: sorted-unique
    /// rows, per-pair local remap, and the coefficient gather in
    /// [`flatten_prepared_coeffs`]'s layout at width [`Self::n_rows`].
    pub fn build(&mut self, preps: &[ArkG2Prepared], row_indices: &[u32]) {
        let span = tracing::info_span!("MetalCommit::miller_tile", rows = 0u64);
        let _entered = span.enter();
        self.unique.clear();
        self.unique.extend_from_slice(row_indices);
        self.unique.sort_unstable();
        self.unique.dedup();
        let _ = span.record("rows", self.unique.len() as u64);
        self.local_rows.clear();
        self.local_rows.extend(
            row_indices
                .iter()
                .map(|row| self.unique.partition_point(|&at| at < *row) as u32),
        );
        let steps = ell_coeffs_per_pair();
        for &row in &self.unique {
            let prep = &preps[row as usize];
            assert!(!prep.infinity, "tile: infinity G2 has no coefficients");
            assert_eq!(prep.ell_coeffs.len(), steps);
        }
        self.coeffs.clear();
        self.coeffs
            .resize(steps * self.unique.len() * ELL_COEFF_U32S, 0);
        if self.unique.is_empty() {
            return;
        }
        let write_step = |(step, chunk): (usize, &mut [u32])| {
            for (tile_row, &row) in self.unique.iter().enumerate() {
                let at = tile_row * ELL_COEFF_U32S;
                let coeff = &preps[row as usize].ell_coeffs[step];
                write_fq2(&mut chunk[at..at + 2 * FR_U32_LIMBS], &coeff.0);
                write_fq2(
                    &mut chunk[at + 2 * FR_U32_LIMBS..at + 4 * FR_U32_LIMBS],
                    &coeff.1,
                );
                write_fq2(
                    &mut chunk[at + 4 * FR_U32_LIMBS..at + 6 * FR_U32_LIMBS],
                    &coeff.2,
                );
            }
        };
        let row_u32s = self.unique.len() * ELL_COEFF_U32S;
        #[cfg(feature = "parallel")]
        {
            use rayon::prelude::*;
            self.coeffs
                .par_chunks_mut(row_u32s)
                .enumerate()
                .for_each(write_step);
        }
        #[cfg(not(feature = "parallel"))]
        self.coeffs
            .chunks_mut(row_u32s)
            .enumerate()
            .for_each(write_step);
    }

    /// The tile's table width (unique referenced rows).
    pub fn n_rows(&self) -> usize {
        self.unique.len()
    }
}

/// View affine G1 points as the device `uint` stream (same contract as
/// [`super::g1::bases_as_u32s`]; identity's (0, 0) coordinates ARE the
/// device sentinel, so identities may be included).
pub(super) fn g1_points_as_u32s(points: &[G1Affine]) -> &[u32] {
    // SAFETY: layout pinned by the const asserts in `super::field`; every
    // bit pattern is a valid u32; same lifetime as `points`.
    unsafe {
        std::slice::from_raw_parts(
            points.as_ptr().cast::<u32>(),
            points.len() * G1_AFFINE_U32_STRIDE,
        )
    }
}

/// The multiplicative fold of the per-thread partial Miller values.
pub fn product_of_partials(partials: &[u32]) -> <Bn254 as Pairing>::TargetField {
    partials
        .chunks_exact(FQ12_U32S)
        .fold(Fq12::one(), |acc, limbs| {
            acc * fq12_from_device_limbs(limbs)
        })
}

/// Deterministic projective pairing inputs for the stage-8 multi-pair
/// benches: generator multiples of a splitmix64 scalar stream (the
/// [`super::testing::seeded_frs`] generator), rayon-parallel under
/// `parallel`. Miller cost is data-oblivious, so generator multiples time
/// identically to uniform points.
pub fn seeded_pairing_inputs(seed: u64, n: usize) -> (Vec<ArkG1>, Vec<ArkG2>) {
    use ark_ff::PrimeField;
    let mut state = seed;
    let mut next_u64 = move || {
        state = state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    };
    let scalars: Vec<(ark_bn254::Fr, ark_bn254::Fr)> = (0..n)
        .map(|_| {
            let mut fr = || {
                let mut bytes = [0u8; 64];
                for chunk in bytes.chunks_exact_mut(8) {
                    chunk.copy_from_slice(&next_u64().to_le_bytes());
                }
                ark_bn254::Fr::from_le_bytes_mod_order(&bytes)
            };
            (fr(), fr())
        })
        .collect();
    let point_pair = |(s1, s2): &(ark_bn254::Fr, ark_bn254::Fr)| {
        (
            ArkG1(G1Affine::generator() * s1),
            ArkG2(G2Affine::generator() * s2),
        )
    };
    #[cfg(feature = "parallel")]
    {
        use rayon::prelude::*;
        scalars.par_iter().map(point_pair).unzip()
    }
    #[cfg(not(feature = "parallel"))]
    scalars.iter().map(point_pair).unzip()
}

/// Uniform `pairs_per_thread` segmentation — the test/bench convenience
/// for [`miller_table_partials`]' ragged segment interface.
pub fn uniform_seg_starts(n_pairs: usize, pairs_per_thread: usize) -> Vec<u32> {
    let n_threads = n_pairs.div_ceil(pairs_per_thread);
    (0..=n_threads)
        .map(|t| (t * pairs_per_thread).min(n_pairs) as u32)
        .collect()
}

/// The kernel's `[[buffer]]`/params contract, shared with the commit slot's
/// in-pipeline dispatch: pair `i` = `points[i]` against table row
/// `row_indices[i]`; thread `t` owns pairs
/// `seg_starts[t]..seg_starts[t + 1]` and writes one partial Miller value.
pub fn miller_table_params(n_threads: usize, n_rows: usize) -> Result<[u32; 2], MetalError> {
    Ok([
        u32::try_from(n_threads).map_err(|_| MetalError::Execution("thread count".into()))?,
        u32::try_from(n_rows).map_err(|_| MetalError::Execution("table rows".into()))?,
    ])
}

/// Dispatch the prepared-coefficient Miller kernel synchronously (the
/// test/bench path; the commit slot encodes the same dispatch inline to
/// overlap its CPU share). Returns the raw partial-f limb buffer (one Fq12
/// per thread).
pub fn miller_table_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    row_indices: &[u32],
    seg_starts: &[u32],
    coeffs: &[u32],
    n_rows: usize,
) -> Result<Vec<u32>, MetalError> {
    assert_eq!(points.len(), row_indices.len());
    assert_eq!(
        coeffs.len(),
        ell_coeffs_per_pair() * n_rows * ELL_COEFF_U32S
    );
    let n_threads = seg_starts.len() - 1;
    let ps_buf = ctx.wrap_slice(g1_points_as_u32s(points))?;
    let idx_buf = ctx.wrap_slice(row_indices)?;
    let seg_buf = ctx.wrap_slice(seg_starts)?;
    let coeffs_buf = ctx.wrap_slice(coeffs)?;
    let out_buf = ctx.alloc_u32s(n_threads * FQ12_U32S)?;
    ctx.run_once(
        KernelId::MillerTable,
        &miller_table_params(n_threads, n_rows)?,
        &[&ps_buf, &idx_buf, &seg_buf, &coeffs_buf, &out_buf],
        n_threads,
    )?;
    let mut partials = vec![0u32; n_threads * FQ12_U32S];
    out_buf.copy_to_u32s(&mut partials);
    Ok(partials)
}

/// View affine G2 points as the device `uint` stream (identities included —
/// the (0, 0) sentinel skips them on device, as arkworks' filter does).
pub(super) fn g2_points_as_u32s(points: &[G2Affine]) -> &[u32] {
    // SAFETY: layout pinned by the const asserts in `super::field`.
    unsafe {
        std::slice::from_raw_parts(
            points.as_ptr().cast::<u32>(),
            points.len() * G2_AFFINE_U32_STRIDE,
        )
    }
}

/// Dispatch the on-the-fly Miller kernel over affine pairs (one per
/// thread); returns the raw partial-f limb buffer.
pub fn miller_fly_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    qs: &[G2Affine],
) -> Result<Vec<u32>, MetalError> {
    assert_eq!(points.len(), qs.len());
    let n_pairs = points.len();
    let ps_buf = ctx.wrap_slice(g1_points_as_u32s(points))?;
    let qs_buf = ctx.wrap_slice(g2_points_as_u32s(qs))?;
    let out_buf = ctx.alloc_u32s(n_pairs * FQ12_U32S)?;
    let params = [u32::try_from(n_pairs).map_err(|_| MetalError::Execution("pair count".into()))?];
    ctx.run_once(
        KernelId::MillerFly,
        &params,
        &[&ps_buf, &qs_buf, &out_buf],
        n_pairs,
    )?;
    let mut partials = vec![0u32; n_pairs * FQ12_U32S];
    out_buf.copy_to_u32s(&mut partials);
    Ok(partials)
}

/// Split-ladder toggle for the stage-8 fly path (`JOLT_MILLER_FLY_SPLIT=1`
/// opts in; **default off — measured NO-GO on the M5 Max, W4-fly**). The
/// premise was that `jk_miller_fly`'s ~430 live u32 words (f + G2Hom + q +
/// line + mul temporaries) pay compiler spill traffic on every f touch, so
/// two passes with disjoint state ([`miller_fly_split_partials`]) should
/// win. Measured at 8192 pairs: lines 0.77 + fold 2.79 µs/pair — the
/// isolated passes SUM to the fused wall (3.47), and the two-phase
/// dispatch pays +12.7% on top (+20.5% under the register cap). The fused
/// kernel already overlaps ladder ALU with the f-walk's spill stalls;
/// isolating the passes forfeits that overlap and buys no per-pass rate,
/// because the spill boundary sits far below even a lone Fq12 accumulator
/// (see the T1 fq6-chain rates). Kept for experiments; read per call —
/// the benches A/B it in-process.
pub const ENV_MILLER_FLY_SPLIT: &str = "JOLT_MILLER_FLY_SPLIT";

fn miller_fly_split_enabled() -> bool {
    std::env::var(ENV_MILLER_FLY_SPLIT).is_ok_and(|value| value.trim() == "1")
}

/// log2 of the split scratch block (`JOLT_MILLER_FLY_BLOCK_LOG2`, default
/// 2^15 pairs ≈ 547 MB of line records): bounds transient footprint at
/// production sizes while keeping each pass wide enough to fill the device.
pub const ENV_MILLER_FLY_BLOCK_LOG2: &str = "JOLT_MILLER_FLY_BLOCK_LOG2";
const DEFAULT_MILLER_FLY_BLOCK_LOG2: u32 = 15;

fn miller_fly_block_pairs() -> usize {
    let log2 = std::env::var(ENV_MILLER_FLY_BLOCK_LOG2)
        .ok()
        .and_then(|value| value.trim().parse::<u32>().ok())
        .unwrap_or(DEFAULT_MILLER_FLY_BLOCK_LOG2)
        .min(24);
    1usize << log2
}

/// [`miller_fly_partials`] as the two-pass split ladder (W4-fly): pass 1
/// (`jk_miller_fly_lines`) runs the G2 preparation ladder with no Fq12
/// state and writes P-scaled line records step-major; pass 2
/// (`jk_miller_fly_fold`) replays the ate walk over the records with no
/// ladder state. Blocks of [`miller_fly_block_pairs`] pairs reuse one
/// scratch table inside a single command buffer (barriers order the
/// write→read and read→rewrite hazards). Partials are bit-identical to the
/// fused kernel's — same field ops on the same values in the same order.
pub fn miller_fly_split_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    qs: &[G2Affine],
) -> Result<Vec<u32>, MetalError> {
    assert_eq!(points.len(), qs.len());
    let n_pairs = points.len();
    if n_pairs == 0 {
        return Ok(Vec::new());
    }
    let block = miller_fly_block_pairs().min(n_pairs);
    let steps = ell_coeffs_per_pair();
    let ps_buf = ctx.wrap_slice(g1_points_as_u32s(points))?;
    let qs_buf = ctx.wrap_slice(g2_points_as_u32s(qs))?;
    let lines_buf = ctx.alloc_u32s(block * steps * ELL_COEFF_U32S)?;
    let flags_buf = ctx.alloc_u32s(block)?;
    let out_buf = ctx.alloc_u32s(n_pairs * FQ12_U32S)?;
    let mut pass = ctx.begin_pass()?;
    let mut base = 0usize;
    while base < n_pairs {
        let n_block = (n_pairs - base).min(block);
        let params = [
            u32::try_from(n_block).map_err(|_| MetalError::Execution("block pairs".into()))?,
            u32::try_from(base).map_err(|_| MetalError::Execution("block base".into()))?,
        ];
        if base != 0 {
            // Previous fold must finish reading the scratch table before
            // this block's lines pass rewrites it.
            pass.buffer_barrier();
        }
        pass.dispatch(
            KernelId::MillerFlyLines,
            &params,
            &[&ps_buf, &qs_buf, &lines_buf, &flags_buf],
            n_block,
        );
        pass.buffer_barrier();
        pass.dispatch(
            KernelId::MillerFlyFold,
            &params,
            &[&lines_buf, &flags_buf, &out_buf],
            n_block,
        );
        base += n_block;
    }
    pass.run()?;
    let mut partials = vec![0u32; n_pairs * FQ12_U32S];
    out_buf.copy_to_u32s(&mut partials);
    Ok(partials)
}

/// The fly-family dispatch the stage-8 hook uses: split ladder unless
/// [`ENV_MILLER_FLY_SPLIT`] disables it.
fn miller_fly_device_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    qs: &[G2Affine],
) -> Result<Vec<u32>, MetalError> {
    if miller_fly_split_enabled() {
        miller_fly_split_partials(ctx, points, qs)
    } else {
        miller_fly_partials(ctx, points, qs)
    }
}

/// Stage-0 twin of [`miller_fly_partials`]: G2 setup rows remain shared,
/// while `row_indices` selects one for each G1 point. This avoids expanding
/// repeated setup rows or building the prepared-coefficient table.
pub fn miller_fly_indexed_partials(
    ctx: &MetalContext,
    points: &[G1Affine],
    row_indices: &[u32],
    qs: &[G2Affine],
) -> Result<Vec<u32>, MetalError> {
    assert_eq!(points.len(), row_indices.len());
    assert!(
        row_indices.iter().all(|&row| (row as usize) < qs.len()),
        "Miller row index exceeds the G2 table"
    );
    let n_pairs = points.len();
    let ps_buf = ctx.wrap_slice(g1_points_as_u32s(points))?;
    let row_indices_buf = ctx.wrap_slice(row_indices)?;
    let qs_buf = ctx.wrap_slice(g2_points_as_u32s(qs))?;
    let out_buf = ctx.alloc_u32s(n_pairs * FQ12_U32S)?;
    let params = [u32::try_from(n_pairs).map_err(|_| MetalError::Execution("pair count".into()))?];
    ctx.run_once(
        KernelId::MillerFlyIndexed,
        &params,
        &[&ps_buf, &row_indices_buf, &qs_buf, &out_buf],
        n_pairs,
    )?;
    let mut partials = vec![0u32; n_pairs * FQ12_U32S];
    out_buf.copy_to_u32s(&mut partials);
    Ok(partials)
}

/// Per-pair Fq-mul-equivalents fed to [`super::metal_gate`] so the shared
/// `JOLT_METAL_MIN_TERMS` scale keeps meaning "work items": the shift
/// calibrates the default threshold (2^16) to a 2048-pair floor. Below
/// it, per-thread ate-ladder latency dominates (the W5a
/// ladder-latency-floor lesson) while dory's internally parallel CPU
/// multi-pair shrinks linearly. In-pipeline sweep (sha2-chain @2^22,
/// stage-8 wall): hook off → 2.20/2.18 s, ≥4096 pairs → 2.12,
/// **≥2048 → 2.02/2.02**, ≥1024 → 2.11 (the third reduce round loses).
pub(super) const MILLER_FLY_WORK_PER_PAIR_LOG2: usize = 5;

/// Percent of a served multi-pair evaluated on the CPU concurrently with
/// the device dispatch (`JOLT_MILLER_CPU_PCT`, clamped to 90; 0 = pure
/// device). **Default 0 — measured NO-GO on the M5 Max (W3-st8):** the
/// device sustains 2.75-3.5 µs/pair at production reduce-round sizes,
/// while the honest co-run CPU rate is 45-55 µs/pair — wave-1's 13.5
/// µs/pair "fly twin" was a lucky draw of `multi_miller_loop`'s internal
/// 4-pair re-chunking, and even the deterministic prepared-ladder path
/// hits a ~2.7×/18-thread parallel-scaling ceiling on chunky pairing
/// tasks. At 20% the split REGRESSED the 2^17 hook call 375 → ~900 ms.
/// The mechanism (exact-partition Miller split, one final exponentiation)
/// stays for machines where the ratio differs; parity is pinned across
/// shares. Read per call — the hook fires ~100 times per proof, and the
/// benches A/B it in-process.
pub const ENV_MILLER_CPU_PCT: &str = "JOLT_MILLER_CPU_PCT";
const DEFAULT_MILLER_CPU_PCT: usize = 0;

/// CPU shares below this many pairs stay on the device: the rayon fan-out
/// plus per-chunk G2 preparation has nothing to amortize against.
const MILLER_CPU_MIN_PAIRS: usize = 512;

fn miller_cpu_tail(n_pairs: usize) -> usize {
    let pct = std::env::var(ENV_MILLER_CPU_PCT)
        .ok()
        .and_then(|value| value.trim().parse::<usize>().ok())
        .unwrap_or(DEFAULT_MILLER_CPU_PCT)
        .min(90);
    let tail = n_pairs * pct / 100;
    if tail < MILLER_CPU_MIN_PAIRS {
        0
    } else {
        tail
    }
}

/// The CPU share of a split multi-pair: `jolt_dory`'s deterministic
/// chunked prepared-ladder Miller (NOT `Bn254::multi_miller_loop`, whose
/// internal 4-pair re-chunking is nondeterministically 3-4× slower on a
/// saturated rayon pool). Identity filtering matches the device sentinel
/// skip. Empty input is the empty product.
fn cpu_miller_product(ps: &[G1Affine], qs: &[G2Affine]) -> Fq12 {
    if ps.is_empty() {
        return Fq12::one();
    }
    jolt_dory::multi_miller_affine(ps, qs)
}

/// [`product_of_partials`] on rayon chunks — the same value by
/// associativity/commutativity of the Fq12 product, off the caller's
/// critical path at reduce-round sizes (10⁵ sequential Fq12 muls
/// otherwise).
pub fn product_of_partials_par(partials: &[u32]) -> Fq12 {
    #[cfg(feature = "parallel")]
    {
        use rayon::prelude::*;
        partials
            .par_chunks(256 * FQ12_U32S)
            .map(product_of_partials)
            .product()
    }
    #[cfg(not(feature = "parallel"))]
    product_of_partials(partials)
}

#[cfg(feature = "parallel")]
fn join<A, B, RA, RB>(a: A, b: B) -> (RA, RB)
where
    A: FnOnce() -> RA + Send,
    B: FnOnce() -> RB + Send,
    RA: Send,
    RB: Send,
{
    rayon::join(a, b)
}

#[cfg(not(feature = "parallel"))]
fn join<A, B, RA, RB>(a: A, b: B) -> (RA, RB)
where
    A: FnOnce() -> RA,
    B: FnOnce() -> RB,
{
    (a(), b())
}

/// The stage-8 device multi-pairing — dory's `multi_pair*` hook. Serves
/// the call with the exact GT the CPU path computes (device Miller
/// partials → Fq12 product → arkworks final exponentiation) or declines
/// (`None`) below the gate or on any device error, letting dory's CPU
/// path run. Both paths batch-normalize the same projective inputs, so
/// the device sees the same affine pairs (identities included — the
/// sentinel skip mirrors the CPU pair filter).
///
/// A tail share of the pairs is evaluated on the otherwise-idle CPU
/// concurrently with the device dispatch ([`ENV_MILLER_CPU_PCT`]); the two
/// partial Miller products multiply into one value before the single final
/// exponentiation, so the split is invisible to the transcript — Miller
/// products over any pair partition are exact and order-free.
#[tracing::instrument(
    skip_all,
    name = "miller_fly_device",
    fields(pairs = ps.len(), cpu_pairs = tracing::field::Empty)
)]
pub fn multi_pair_device(ps: &[ArkG1], qs: &[ArkG2]) -> Option<ArkGT> {
    if !super::metal_gate("miller_fly", ps.len() << MILLER_FLY_WORK_PER_PAIR_LOG2) {
        return None;
    }
    let ctx = MetalContext::global().ok()?;
    let ps_affine = G1Projective::normalize_batch(&ps.iter().map(|p| p.0).collect::<Vec<_>>());
    let qs_affine = G2Projective::normalize_batch(&qs.iter().map(|q| q.0).collect::<Vec<_>>());
    let cpu_pairs = miller_cpu_tail(ps_affine.len());
    let _ = tracing::Span::current().record("cpu_pairs", cpu_pairs as u64);
    let device_pairs = ps_affine.len() - cpu_pairs;
    let (device_partials, cpu_product) = join(
        || miller_fly_device_partials(ctx, &ps_affine[..device_pairs], &qs_affine[..device_pairs]),
        || cpu_miller_product(&ps_affine[device_pairs..], &qs_affine[device_pairs..]),
    );
    let partials = match device_partials {
        Ok(partials) => partials,
        Err(error) => {
            tracing::warn!(%error, "device multi-pair failed; falling back to the CPU path");
            return None;
        }
    };
    super::testing::note_miller_dispatch();
    let miller = product_of_partials_par(&partials) * cpu_product;
    // A `None` final exponentiation (zero Miller product) cannot arise from
    // well-formed pairs; decline and let the CPU path handle it identically.
    let gt = Bn254::final_exponentiation(MillerLoopOutput(miller))?;
    Some(ArkGT(gt))
}

/// Several multi-pairings served by ONE device dispatch (W4 st8 bundle).
/// Dory's reduce rounds issue their per-message multi-pairs (4 first, 2
/// second, each n/2 pairs) as separate hook calls: separate command
/// buffers, and per-call sizes that starve the device mid-ladder (4096-
/// and 2048-pair dispatches) then fall under the 2048-pair gate entirely
/// (rounds 7-8). Concatenating the calls into one dispatch exposes their
/// SUM of threads and gates on it.
///
/// Each returned GT is the exact value of the corresponding
/// `multi_pair_device` call: partials are per-pair, the partial buffer is
/// partitioned back by call range, and batch normalization inverts the
/// same field elements (inverses are unique) — identical bytes. Declines
/// (`None`) below the TOTAL-pairs gate or on any device error; callers
/// keep their per-call fallback. The CPU-share knob does not apply here
/// (measured NO-GO, default 0).
#[tracing::instrument(
    skip_all,
    name = "miller_fly_device_batch",
    fields(calls = calls.len(), pairs = tracing::field::Empty)
)]
pub fn multi_pair_device_batch(calls: &[(&[ArkG1], &[ArkG2])]) -> Option<Vec<ArkGT>> {
    let total: usize = calls.iter().map(|(ps, _)| ps.len()).sum();
    let _ = tracing::Span::current().record("pairs", total as u64);
    if total == 0 || !super::metal_gate("miller_fly", total << MILLER_FLY_WORK_PER_PAIR_LOG2) {
        return None;
    }
    let ctx = MetalContext::global().ok()?;
    let mut ps_proj = Vec::with_capacity(total);
    let mut qs_proj = Vec::with_capacity(total);
    for (ps, qs) in calls {
        assert_eq!(ps.len(), qs.len(), "multi-pair calls need equal sides");
        ps_proj.extend(ps.iter().map(|p| p.0));
        qs_proj.extend(qs.iter().map(|q| q.0));
    }
    let ps_affine = G1Projective::normalize_batch(&ps_proj);
    let qs_affine = G2Projective::normalize_batch(&qs_proj);
    let partials = match miller_fly_device_partials(ctx, &ps_affine, &qs_affine) {
        Ok(partials) => partials,
        Err(error) => {
            tracing::warn!(%error, "batched multi-pair failed; falling back to per-call hooks");
            return None;
        }
    };
    super::testing::note_miller_dispatch();
    let mut ranges = Vec::with_capacity(calls.len());
    let mut at = 0usize;
    for (ps, _) in calls {
        ranges.push(at * FQ12_U32S..(at + ps.len()) * FQ12_U32S);
        at += ps.len();
    }
    let fold_one = |range: std::ops::Range<usize>| {
        Bn254::final_exponentiation(MillerLoopOutput(product_of_partials_par(&partials[range])))
            .map(ArkGT)
    };
    #[cfg(feature = "parallel")]
    let gts: Option<Vec<ArkGT>> = {
        use rayon::prelude::*;
        ranges.into_par_iter().map(fold_one).collect()
    };
    #[cfg(not(feature = "parallel"))]
    let gts: Option<Vec<ArkGT>> = ranges.into_iter().map(fold_one).collect();
    // A `None` final exponentiation (zero Miller product) cannot arise from
    // well-formed pairs; decline the whole batch and let the CPU path
    // handle it identically.
    gts
}

#[cfg(test)]
#[expect(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests: fail loudly"
)]
mod tests {
    use ark_ec::pairing::MillerLoopOutput;
    use ark_ec::CurveGroup;
    use ark_ff::{UniformRand, Zero};
    use rand_chacha::ChaCha20Rng;
    use rand_core::SeedableRng;

    use super::super::testing::gpu_lock;
    use super::*;

    fn rng() -> ChaCha20Rng {
        ChaCha20Rng::seed_from_u64(0x77_6f)
    }

    /// Arithmetic edge values lifted through the tower: 0, ±1, and a
    /// random element per slot position (each nonresidue path in
    /// isolation).
    fn edge_fq12s(rng: &mut ChaCha20Rng) -> Vec<Fq12> {
        let mut out = vec![Fq12::zero(), Fq12::one(), -Fq12::one()];
        for slot in 0..12 {
            let mut limbs = [Fq::zero(); 12];
            limbs[slot] = Fq::rand(rng);
            let fq2 = |i: usize| Fq2::new(limbs[2 * i], limbs[2 * i + 1]);
            out.push(Fq12::new(
                Fq6::new(fq2(0), fq2(1), fq2(2)),
                Fq6::new(fq2(3), fq2(4), fq2(5)),
            ));
        }
        out
    }

    #[test]
    fn fq6_mul_sqr_match_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let mut xs: Vec<Fq6> = edge_fq12s(&mut rng).iter().map(|f| f.c0).collect();
        xs.extend((0..256).map(|_| Fq6::rand(&mut rng)));
        let ys: Vec<Fq6> = xs.iter().rev().copied().collect();
        let words = 6 * FR_U32_LIMBS;

        let x_limbs: Vec<u32> = xs.iter().flat_map(fq6_to_device_limbs).collect();
        let y_limbs: Vec<u32> = ys.iter().flat_map(fq6_to_device_limbs).collect();
        let x_buf = ctx.wrap_slice(&x_limbs).unwrap();
        let y_buf = ctx.wrap_slice(&y_limbs).unwrap();
        let out_buf = ctx.alloc_u32s(xs.len() * words).unwrap();
        ctx.run_once(
            KernelId::Fq6Mul,
            &[xs.len() as u32, 1],
            &[&x_buf, &y_buf, &out_buf],
            xs.len(),
        )
        .unwrap();
        let mut out = vec![0u32; xs.len() * words];
        out_buf.copy_to_u32s(&mut out);
        for (i, (x, y)) in xs.iter().zip(&ys).enumerate() {
            let got = fq6_from_device_limbs(&out[i * words..(i + 1) * words]);
            assert_eq!(got, *x * y, "fq6 mul mismatch at {i}");
        }

        let sqr_buf = ctx.alloc_u32s(xs.len() * words).unwrap();
        ctx.run_once(
            KernelId::Fq6Sqr,
            &[xs.len() as u32, 1],
            &[&x_buf, &sqr_buf],
            xs.len(),
        )
        .unwrap();
        sqr_buf.copy_to_u32s(&mut out);
        for (i, x) in xs.iter().enumerate() {
            let got = fq6_from_device_limbs(&out[i * words..(i + 1) * words]);
            assert_eq!(got, x.square(), "fq6 sqr mismatch at {i}");
        }
    }

    #[test]
    fn fq12_mul_sqr_match_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let mut xs = edge_fq12s(&mut rng);
        xs.extend((0..256).map(|_| Fq12::rand(&mut rng)));
        let ys: Vec<Fq12> = xs.iter().rev().copied().collect();

        let x_limbs: Vec<u32> = xs.iter().flat_map(fq12_to_device_limbs).collect();
        let y_limbs: Vec<u32> = ys.iter().flat_map(fq12_to_device_limbs).collect();
        let x_buf = ctx.wrap_slice(&x_limbs).unwrap();
        let y_buf = ctx.wrap_slice(&y_limbs).unwrap();
        let out_buf = ctx.alloc_u32s(xs.len() * FQ12_U32S).unwrap();
        ctx.run_once(
            KernelId::Fq12Mul,
            &[xs.len() as u32, 1],
            &[&x_buf, &y_buf, &out_buf],
            xs.len(),
        )
        .unwrap();
        let mut out = vec![0u32; xs.len() * FQ12_U32S];
        out_buf.copy_to_u32s(&mut out);
        for (i, (x, y)) in xs.iter().zip(&ys).enumerate() {
            let got = fq12_from_device_limbs(&out[i * FQ12_U32S..(i + 1) * FQ12_U32S]);
            assert_eq!(got, *x * y, "fq12 mul mismatch at {i}");
        }

        let sqr_buf = ctx.alloc_u32s(xs.len() * FQ12_U32S).unwrap();
        ctx.run_once(
            KernelId::Fq12Sqr,
            &[xs.len() as u32, 1],
            &[&x_buf, &sqr_buf],
            xs.len(),
        )
        .unwrap();
        sqr_buf.copy_to_u32s(&mut out);
        for (i, x) in xs.iter().enumerate() {
            let got = fq12_from_device_limbs(&out[i * FQ12_U32S..(i + 1) * FQ12_U32S]);
            assert_eq!(got, x.square(), "fq12 sqr mismatch at {i}");
        }
    }

    #[test]
    fn fq12_mul034_matches_arkworks() {
        let _lock = gpu_lock();
        let mut rng = rng();
        let n = 256usize;
        let fs: Vec<Fq12> = (0..n).map(|_| Fq12::rand(&mut rng)).collect();
        let coeffs: Vec<(Fq2, Fq2, Fq2)> = (0..n)
            .map(|_| {
                (
                    Fq2::rand(&mut rng),
                    Fq2::rand(&mut rng),
                    Fq2::rand(&mut rng),
                )
            })
            .collect();
        let points: Vec<G1Affine> = (0..n)
            .map(|_| ark_bn254::G1Projective::rand(&mut rng).into_affine())
            .collect();

        let ctx = MetalContext::global().unwrap();
        let f_limbs: Vec<u32> = fs.iter().flat_map(fq12_to_device_limbs).collect();
        let mut c_limbs = vec![0u32; n * ELL_COEFF_U32S];
        for (i, c) in coeffs.iter().enumerate() {
            let at = i * ELL_COEFF_U32S;
            write_fq2(&mut c_limbs[at..at + 16], &c.0);
            write_fq2(&mut c_limbs[at + 16..at + 32], &c.1);
            write_fq2(&mut c_limbs[at + 32..at + 48], &c.2);
        }
        let f_buf = ctx.wrap_slice(&f_limbs).unwrap();
        let c_buf = ctx.wrap_slice(&c_limbs).unwrap();
        let p_buf = ctx.wrap_slice(g1_points_as_u32s(&points)).unwrap();
        let out_buf = ctx.alloc_u32s(n * FQ12_U32S).unwrap();
        ctx.run_once(
            KernelId::Fq12Mul034,
            &[n as u32, 1],
            &[&f_buf, &c_buf, &p_buf, &out_buf],
            n,
        )
        .unwrap();
        let mut out = vec![0u32; n * FQ12_U32S];
        out_buf.copy_to_u32s(&mut out);

        for i in 0..n {
            let mut expected = fs[i];
            let mut c0 = coeffs[i].0;
            let mut c1 = coeffs[i].1;
            c0.mul_assign_by_fp(&points[i].y);
            c1.mul_assign_by_fp(&points[i].x);
            expected.mul_by_034(&c0, &c1, &coeffs[i].2);
            let got = fq12_from_device_limbs(&out[i * FQ12_U32S..(i + 1) * FQ12_U32S]);
            assert_eq!(got, expected, "mul034 mismatch at {i}");
        }
    }

    fn reference_miller(ps: &[G1Affine], qs: &[G2Affine]) -> Fq12 {
        let MillerLoopOutput(f) = Bn254::multi_miller_loop(ps.iter().copied(), qs.iter().copied());
        f
    }

    fn random_pairs(rng: &mut ChaCha20Rng, n: usize) -> (Vec<G1Affine>, Vec<G2Affine>) {
        let ps = (0..n)
            .map(|_| ark_bn254::G1Projective::rand(rng).into_affine())
            .collect();
        let qs = (0..n)
            .map(|_| ark_bn254::G2Projective::rand(rng).into_affine())
            .collect();
        (ps, qs)
    }

    fn table_product(ps: &[G1Affine], qs: &[G2Affine], ppt: usize) -> Fq12 {
        let ctx = MetalContext::global().expect("metal context");
        let preps: Vec<ArkG2Prepared> = qs.iter().map(|q| (*q).into()).collect();
        let refs: Vec<&ArkG2Prepared> = preps.iter().collect();
        let mut coeffs = Vec::new();
        flatten_prepared_coeffs(&refs, &mut coeffs);
        let indices: Vec<u32> = (0..ps.len() as u32).collect();
        let segs = uniform_seg_starts(ps.len(), ppt);
        let partials = miller_table_partials(ctx, ps, &indices, &segs, &coeffs, qs.len()).unwrap();
        product_of_partials(&partials)
    }

    /// Table-kernel Miller product vs arkworks: random pairs at several
    /// pairs-per-thread geometries (including a non-dividing one), a
    /// single pair, negated points, and G1 identity sentinels.
    #[test]
    fn miller_table_matches_arkworks() {
        let _lock = gpu_lock();
        let mut rng = rng();

        let (ps, qs) = random_pairs(&mut rng, 37);
        let expected = reference_miller(&ps, &qs);
        for ppt in [1usize, 4, 8] {
            assert_eq!(table_product(&ps, &qs, ppt), expected, "ppt {ppt}");
        }

        let (p1, q1) = random_pairs(&mut rng, 1);
        assert_eq!(table_product(&p1, &q1, 4), reference_miller(&p1, &q1));

        let neg: Vec<G1Affine> = ps.iter().map(|p| -*p).collect();
        assert_eq!(table_product(&neg, &qs, 4), reference_miller(&neg, &qs));

        // Identity G1s interleaved: arkworks filters the pair, the device
        // skips it via the (0, 0) sentinel — same product.
        let mut with_id = ps.clone();
        with_id[0] = G1Affine::identity();
        with_id[19] = G1Affine::identity();
        assert_eq!(
            table_product(&with_id, &qs, 4),
            reference_miller(&with_id, &qs)
        );
    }

    /// Production-scale pin: a 2^15-pair batch (one stage-0 tier-2 column
    /// at 2^22) against one G2 prep shared arkworks↔device, sentinels
    /// included — the exact shape the commit slot dispatches.
    #[test]
    fn miller_table_matches_arkworks_at_scale() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let n = 1usize << 15;

        // Cheap distinct G1s: a small random set permuted, plus scattered
        // identity sentinels (Miller cost is data-oblivious; the reference
        // cost is what bounds this test).
        let seeds: Vec<G1Affine> = (0..64)
            .map(|_| ark_bn254::G1Projective::rand(&mut rng).into_affine())
            .collect();
        let mut ps: Vec<G1Affine> = (0..n).map(|i| seeds[(i * 31 + 7) % 64]).collect();
        for i in (0..n).step_by(1013) {
            ps[i] = G1Affine::identity();
        }
        let q_seeds: Vec<G2Affine> = (0..64)
            .map(|_| ark_bn254::G2Projective::rand(&mut rng).into_affine())
            .collect();
        let qs: Vec<G2Affine> = (0..n).map(|i| q_seeds[(i * 17 + 3) % 64]).collect();

        let preps: Vec<ArkG2Prepared> = qs.iter().map(|q| (*q).into()).collect();
        let refs: Vec<&ArkG2Prepared> = preps.iter().collect();
        let mut coeffs = Vec::new();
        flatten_prepared_coeffs(&refs, &mut coeffs);
        let indices: Vec<u32> = (0..n as u32).collect();
        let segs = uniform_seg_starts(n, 8);
        let partials = miller_table_partials(ctx, &ps, &indices, &segs, &coeffs, n).unwrap();
        let device = product_of_partials(&partials);

        let live: Vec<usize> = (0..n).filter(|i| !ps[*i].is_zero()).collect();
        let MillerLoopOutput(expected) = Bn254::multi_miller_loop(
            live.iter().map(|&i| ps[i]),
            live.iter().map(|&i| preps[i].clone()),
        );
        assert_eq!(device, expected);
    }

    /// The commit-slot shape: a SHARED coefficient table addressed through
    /// repeating row indices, ragged per-thread segments, and per-segment
    /// partial folds — each segment's product must equal arkworks over
    /// exactly its pair subset.
    #[test]
    fn miller_table_shared_rows_ragged_segments() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();

        let n_rows = 24usize;
        let qs: Vec<G2Affine> = (0..n_rows)
            .map(|_| ark_bn254::G2Projective::rand(&mut rng).into_affine())
            .collect();
        let preps: Vec<ArkG2Prepared> = qs.iter().map(|q| (*q).into()).collect();
        let refs: Vec<&ArkG2Prepared> = preps.iter().collect();
        let mut coeffs = Vec::new();
        flatten_prepared_coeffs(&refs, &mut coeffs);

        let n = 173usize;
        let ps: Vec<G1Affine> = (0..n)
            .map(|_| ark_bn254::G1Projective::rand(&mut rng).into_affine())
            .collect();
        let indices: Vec<u32> = (0..n).map(|i| ((i * 13 + 5) % n_rows) as u32).collect();

        // Ragged segments: lengths cycle 1..=5.
        let mut segs = vec![0u32];
        let mut at = 0usize;
        let mut len = 1usize;
        while at < n {
            at = (at + len).min(n);
            segs.push(at as u32);
            len = len % 5 + 1;
        }

        let partials = miller_table_partials(ctx, &ps, &indices, &segs, &coeffs, n_rows).unwrap();
        for (t, window) in segs.windows(2).enumerate() {
            let (start, end) = (window[0] as usize, window[1] as usize);
            let MillerLoopOutput(expected) = Bn254::multi_miller_loop(
                ps[start..end].iter().copied(),
                indices[start..end]
                    .iter()
                    .map(|&r| preps[r as usize].clone()),
            );
            let got = product_of_partials(&partials[t * FQ12_U32S..(t + 1) * FQ12_U32S]);
            assert_eq!(got, expected, "segment {t} ({start}..{end})");
        }
    }

    /// W15 tile parity: a dispatch over a per-batch compact tile
    /// ([`MillerTile`]) must produce BIT-identical per-thread partials to
    /// the same batch against the whole flattened table — identical
    /// coefficient values at identical pair positions, only relocated.
    /// Second batch reuses the tile's recycled backing.
    #[test]
    fn miller_tile_partials_match_whole_table() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();

        let n_rows = 40usize;
        let qs: Vec<G2Affine> = (0..n_rows)
            .map(|_| ark_bn254::G2Projective::rand(&mut rng).into_affine())
            .collect();
        let preps: Vec<ArkG2Prepared> = qs.iter().map(|q| (*q).into()).collect();
        let refs: Vec<&ArkG2Prepared> = preps.iter().collect();
        let mut coeffs = Vec::new();
        flatten_prepared_coeffs(&refs, &mut coeffs);

        let n = 173usize;
        let ps: Vec<G1Affine> = (0..n)
            .map(|_| ark_bn254::G1Projective::rand(&mut rng).into_affine())
            .collect();
        let segs = uniform_seg_starts(n, 4);
        let mut tile = MillerTile::default();
        // Two batches: a sparse repeating 14-row subset, then (on the
        // recycled backing) one touching every row.
        let sparse: Vec<u32> = (0..n).map(|i| (((i * 11 + 3) % 14) * 3) as u32).collect();
        let dense: Vec<u32> = (0..n).map(|i| ((i * 7 + 1) % n_rows) as u32).collect();
        for indices in [sparse, dense] {
            let whole = miller_table_partials(ctx, &ps, &indices, &segs, &coeffs, n_rows).unwrap();
            tile.build(&preps, &indices);
            assert!(tile.n_rows() <= n_rows);
            let tiled = miller_table_partials(
                ctx,
                &ps,
                &tile.local_rows,
                &segs,
                &tile.coeffs,
                tile.n_rows(),
            )
            .unwrap();
            assert_eq!(whole, tiled, "tile relocation changed a partial bit");
        }
    }

    /// The dory hook: `multi_pair_device` must produce the exact GT of
    /// dory's CPU `multi_pair` (final exponentiation included) on
    /// projective inputs with identities mixed in.
    #[test]
    fn multi_pair_device_matches_dory_cpu() {
        let _lock = gpu_lock();
        // nextest gives each test its own process; force the gate open at
        // test sizes.
        std::env::set_var("JOLT_METAL_MIN_TERMS_MILLER_FLY", "1");
        let mut rng = rng();
        let n = 61usize;
        let mut ps: Vec<ArkG1> = (0..n)
            .map(|_| ArkG1(ark_bn254::G1Projective::rand(&mut rng)))
            .collect();
        let mut qs: Vec<ArkG2> = (0..n)
            .map(|_| ArkG2(ark_bn254::G2Projective::rand(&mut rng)))
            .collect();
        ps[7] = ArkG1(ark_bn254::G1Projective::zero());
        qs[23] = ArkG2(ark_bn254::G2Projective::zero());

        let before = super::super::testing::miller_dispatch_count();
        let device = multi_pair_device(&ps, &qs).expect("gate forced open");
        assert!(
            super::super::testing::miller_dispatch_count() > before,
            "the hook silently fell back"
        );
        let cpu = <dory::backends::arkworks::BN254 as
            dory::primitives::arithmetic::PairingCurve>::multi_pair(&ps, &qs);
        assert_eq!(device.0, cpu.0);
    }

    /// The device+CPU split: every share (device-only, calibrated default,
    /// extreme, and a non-dividing percent) must produce the exact GT of
    /// dory's CPU `multi_pair` on the same projective inputs, identities on
    /// both sides of the split boundary included. st8 is consensus-critical
    /// — this is the parity oracle for [`miller_cpu_tail`]'s partition.
    #[test]
    fn multi_pair_device_split_matches_dory_cpu() {
        let _lock = gpu_lock();
        std::env::set_var("JOLT_METAL_MIN_TERMS_MILLER_FLY", "1");
        let mut rng = rng();
        let n = 1500usize;
        let mut ps: Vec<ArkG1> = (0..n)
            .map(|_| ArkG1(ark_bn254::G1Projective::rand(&mut rng)))
            .collect();
        let mut qs: Vec<ArkG2> = (0..n)
            .map(|_| ArkG2(ark_bn254::G2Projective::rand(&mut rng)))
            .collect();
        // Identities in the device head and the CPU tail for every share
        // below (tails: 90% → 1350, 50% → 750, 20% → 0 via the 512 floor).
        ps[3] = ArkG1(ark_bn254::G1Projective::zero());
        qs[200] = ArkG2(ark_bn254::G2Projective::zero());
        ps[900] = ArkG1(ark_bn254::G1Projective::zero());
        qs[1400] = ArkG2(ark_bn254::G2Projective::zero());

        let cpu = <dory::backends::arkworks::BN254 as
            dory::primitives::arithmetic::PairingCurve>::multi_pair(&ps, &qs);
        for pct in ["0", "20", "37", "50", "90"] {
            std::env::set_var(ENV_MILLER_CPU_PCT, pct);
            let split = multi_pair_device(&ps, &qs).expect("gate forced open");
            assert_eq!(split.0, cpu.0, "cpu share {pct}%");
        }
        std::env::remove_var(ENV_MILLER_CPU_PCT);
    }

    /// One batched dispatch = the per-call hook GTs = dory's CPU
    /// `multi_pair`, on ragged ranges with aliased inputs (the reduce
    /// rounds reuse g1/g2 slices across calls) and identities inside
    /// ranges. st8 is consensus-critical — every GT must be exact.
    #[test]
    fn multi_pair_device_batch_matches_singles() {
        let _lock = gpu_lock();
        std::env::set_var("JOLT_METAL_MIN_TERMS_MILLER_FLY", "1");
        let mut rng = rng();
        let point = |rng: &mut ChaCha20Rng| ArkG1(ark_bn254::G1Projective::rand(rng));
        let g2point = |rng: &mut ChaCha20Rng| ArkG2(ark_bn254::G2Projective::rand(rng));
        let mut v1: Vec<ArkG1> = (0..300).map(|_| point(&mut rng)).collect();
        let mut v2: Vec<ArkG2> = (0..300).map(|_| g2point(&mut rng)).collect();
        let g1: Vec<ArkG1> = (0..150).map(|_| point(&mut rng)).collect();
        let g2: Vec<ArkG2> = (0..150).map(|_| g2point(&mut rng)).collect();
        v1[7] = ArkG1(ark_bn254::G1Projective::zero());
        v2[203] = ArkG2(ark_bn254::G2Projective::zero());

        // The first-message shape: g2/g1 aliased across ranges, ragged
        // halves (150 + 150 + 150 + 150 = 600 total pairs).
        let calls: [(&[ArkG1], &[ArkG2]); 4] = [
            (&v1[..150], &g2),
            (&v1[150..], &g2),
            (&g1, &v2[..150]),
            (&g1, &v2[150..]),
        ];
        let batch = multi_pair_device_batch(&calls).expect("gate forced open");
        assert_eq!(batch.len(), 4);
        for (i, ((ps, qs), got)) in calls.iter().zip(&batch).enumerate() {
            let single = multi_pair_device(ps, qs).expect("single hook serves");
            assert_eq!(got.0, single.0, "batch/single drift at call {i}");
            let cpu = <dory::backends::arkworks::BN254 as
                dory::primitives::arithmetic::PairingCurve>::multi_pair(ps, qs);
            assert_eq!(got.0, cpu.0, "batch/CPU drift at call {i}");
        }
    }

    /// The parallel partial fold is the sequential fold (associative +
    /// commutative product), across the chunk boundary.
    #[test]
    fn parallel_partial_fold_matches_sequential() {
        let mut rng = rng();
        let partials: Vec<u32> = (0..600)
            .flat_map(|_| fq12_to_device_limbs(&Fq12::rand(&mut rng)))
            .collect();
        assert_eq!(
            product_of_partials_par(&partials),
            product_of_partials(&partials)
        );
    }

    /// Fly-kernel Miller product vs arkworks: random pairs, single pair,
    /// negated G2s, and identity sentinels on both sides.
    #[test]
    fn miller_fly_matches_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();

        let fly = |ps: &[G1Affine], qs: &[G2Affine]| {
            product_of_partials(&miller_fly_partials(ctx, ps, qs).unwrap())
        };

        let (ps, qs) = random_pairs(&mut rng, 37);
        assert_eq!(fly(&ps, &qs), reference_miller(&ps, &qs));

        let (p1, q1) = random_pairs(&mut rng, 1);
        assert_eq!(fly(&p1, &q1), reference_miller(&p1, &q1));

        let neg_q: Vec<G2Affine> = qs.iter().map(|q| -*q).collect();
        assert_eq!(fly(&ps, &neg_q), reference_miller(&ps, &neg_q));

        let mut ps_id = ps.clone();
        ps_id[3] = G1Affine::identity();
        let mut qs_id = qs.clone();
        qs_id[11] = G2Affine::identity();
        assert_eq!(fly(&ps_id, &qs_id), reference_miller(&ps_id, &qs_id));
    }

    /// Split-ladder partials are BIT-identical to the fused fly kernel's
    /// (same field ops, same values, same order — the retention claim), on
    /// random pairs, negated G2s, identity sentinels on both sides, and
    /// across scratch-block boundaries (block 16 over a ragged 73), and the
    /// folded product still matches arkworks.
    #[test]
    fn miller_fly_split_bit_identical_to_fused() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();

        let (mut ps, mut qs) = random_pairs(&mut rng, 73);
        ps[3] = G1Affine::identity();
        qs[11] = G2Affine::identity();
        qs[40] = -qs[40];
        ps[72] = G1Affine::identity();

        for block_log2 in ["4", "20"] {
            std::env::set_var(ENV_MILLER_FLY_BLOCK_LOG2, block_log2);
            let split = miller_fly_split_partials(ctx, &ps, &qs).unwrap();
            let fused = miller_fly_partials(ctx, &ps, &qs).unwrap();
            assert_eq!(split, fused, "partial drift at block 2^{block_log2}");
            assert_eq!(
                product_of_partials(&split),
                reference_miller(&ps, &qs),
                "arkworks drift at block 2^{block_log2}"
            );
        }
        std::env::remove_var(ENV_MILLER_FLY_BLOCK_LOG2);
    }

    /// The dory hook under both fly forms: split on (default) and the
    /// fused-kernel opt-out produce the exact GT of dory's CPU
    /// `multi_pair`. st8 is consensus-critical — this pins the toggle.
    #[test]
    fn multi_pair_device_fly_split_matches_dory_cpu() {
        let _lock = gpu_lock();
        std::env::set_var("JOLT_METAL_MIN_TERMS_MILLER_FLY", "1");
        let mut rng = rng();
        let n = 97usize;
        let mut ps: Vec<ArkG1> = (0..n)
            .map(|_| ArkG1(ark_bn254::G1Projective::rand(&mut rng)))
            .collect();
        let mut qs: Vec<ArkG2> = (0..n)
            .map(|_| ArkG2(ark_bn254::G2Projective::rand(&mut rng)))
            .collect();
        ps[5] = ArkG1(ark_bn254::G1Projective::zero());
        qs[61] = ArkG2(ark_bn254::G2Projective::zero());

        let cpu = <dory::backends::arkworks::BN254 as
            dory::primitives::arithmetic::PairingCurve>::multi_pair(&ps, &qs);
        for split in ["1", "0"] {
            std::env::set_var(ENV_MILLER_FLY_SPLIT, split);
            let device = multi_pair_device(&ps, &qs).expect("gate forced open");
            assert_eq!(device.0, cpu.0, "GT drift at split={split}");
        }
        std::env::remove_var(ENV_MILLER_FLY_SPLIT);
    }

    #[test]
    fn miller_fly_indexed_matches_arkworks() {
        let _lock = gpu_lock();
        let ctx = MetalContext::global().expect("metal context");
        let mut rng = rng();
        let (mut ps, qs) = random_pairs(&mut rng, 73);
        let mut table = qs[..17].to_vec();
        ps[19] = G1Affine::identity();
        table[5] = G2Affine::identity();
        let indices: Vec<u32> = (0..ps.len())
            .map(|i| ((i * 11 + 3) % table.len()) as u32)
            .collect();
        let selected: Vec<G2Affine> = indices.iter().map(|&row| table[row as usize]).collect();
        let got =
            product_of_partials(&miller_fly_indexed_partials(ctx, &ps, &indices, &table).unwrap());
        assert_eq!(got, reference_miller(&ps, &selected));
    }
}
