[package]
name = "sum_check"
version = "0.1.0"
edition = "2021"


[dependencies]
jolt-core = { git = "https://github.com/arithmic/jolt.git", branch = "grumpkin"}

ark-bn254 = "0.5.0"
ark-ec = { version = "0.5.0", default-features = false }
ark-ff = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false, features = [
    "derive",
] }
regex = "1"

ark-std = { version = "0.5.0" }
num-bigint = {version = "0.4"}
serde_json = "1.0"
sha3 = "0.10.8"
rand_chacha = "0.3.1"
tracing = "0.1.41"
rayon = "1.10.0"
ark-grumpkin = "0.5.0"
# matrix = { path = "./../../R1CS_matrix" }
[features]
default = [
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-std/parallel",
    "ark-ff/asm"
]


