mod result_types;

pub(in crate::pass) use result_types::{
    COMPUTE_OPENING_BATCH_OPENING_RESULT_TYPES, COMPUTE_OPENING_BATCH_RESULT_TYPES,
    COMPUTE_OPENING_CLAIM_RESULT_TYPES, CPU_OPENING_BATCH_OPENING_RESULT_TYPES,
    CPU_OPENING_BATCH_RESULT_TYPES, CPU_OPENING_CLAIM_RESULT_TYPES,
};
