//! The stage-algebra relation on a real fibonacci 2^18 proof: the R1CS is
//! built from the profile alone, the witness is generated by replaying the
//! native verifier, and `check_witness` must pass. Tampering with a round
//! coefficient or an outsourced public input must fail inside the owning
//! stage's rows.
//!
//! `cargo nextest run -p jolt-wrapper --features prover-fixtures --cargo-quiet -E 'binary(relation_fixture)' --no-capture`

#![cfg(feature = "prover-fixtures")]
#![expect(clippy::expect_used, clippy::print_stdout, clippy::unwrap_used)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

use common::constants::ONEHOT_CHUNK_THRESHOLD_LOG_T;
use common::jolt_device::{JoltDevice, MemoryLayout};
use jolt_crypto::{Bn254G1, Pedersen};
use jolt_dory::DoryScheme;
use jolt_field::{Fr, One};
use jolt_program::execution::{JoltProgram, OwnedTrace, TraceOutput, TraceRow};
use jolt_prover::{JoltBackend, JoltProverPreprocessing, ProverConfig};
use jolt_prover_legacy::ark_bn254::Fr as LegacyFr;
use jolt_prover_legacy::curve::Bn254Curve;
use jolt_prover_legacy::host::Program;
use jolt_prover_legacy::poly::commitment::dory::DoryCommitmentScheme;
use jolt_prover_legacy::zkvm::preprocessing::JoltSharedPreprocessing;
use jolt_prover_legacy::zkvm::program::ProgramPreprocessing as LegacyProgramPreprocessing;
use jolt_prover_legacy::zkvm::proof::verifier_preprocessing_from_prover;
use jolt_prover_legacy::zkvm::prover::JoltProverPreprocessing as LegacyProverPreprocessing;
use jolt_r1cs::Variable;
use jolt_transcript::Blake3Transcript;
use jolt_verifier::proof::JoltProof;
use jolt_verifier::JoltVerifierPreprocessing;
use jolt_witness::{JoltVmWitnessConfig, JoltVmWitnessInputs, TraceBackend};
use jolt_wrapper::profile::WrapperProfile;
use jolt_wrapper::relation::{
    build_relation, generate_witness, outsourced_inputs, Relation, ScheduleEntry, SqueezeKind,
    StageValueInputs, Witness,
};
use jolt_wrapper::spartan::{ChallengeDecoder, PublicChallenge, SharedWitnessColumn};
use jolt_wrapper::wrap::{WrapConfig, WrapPreparation};
use tracer::execution_backend::TracerBackend;

type Pcs = DoryScheme;
type Vc = Pedersen<Bn254G1>;
type Proof = JoltProof<Pcs, Vc>;
type VerifierPreprocessing = JoltVerifierPreprocessing<Pcs, Vc>;
type LegacyPreprocessing = LegacyProverPreprocessing<LegacyFr, Bn254Curve, DoryCommitmentScheme>;

/// Fibonacci iterations filling a 2^18 trace; scaled linearly for larger traces.
const FIBONACCI_UNITS_2_18: u32 = 19_660;
/// Shared with the transcript-table fixture at 2^18: the same bincode triple.
const CACHE_DIR: &str = "/Volumes/Dev/scratch/wrapper-fixtures";

/// Pinned row counts of the fibonacci 2^20 relation (L = 20, K = 13, σ = 12).
const EXPECTED_CONSTRAINTS_2_20: usize = 5_454;
const EXPECTED_PER_STAGE_2_20: [(&str, usize); 9] = [
    ("stage1", 278),
    ("stage2", 383),
    ("stage3", 376),
    ("stage4", 230),
    ("stage5", 1_834),
    ("stage6a", 229),
    ("stage6b", 1_038),
    ("stage7", 795),
    ("stage8", 291),
];

/// Pinned row counts of the fibonacci 2^18 relation (L = 18, K = 13, σ = 11).
const EXPECTED_CONSTRAINTS_2_18: usize = 5_253;
const EXPECTED_PER_STAGE_2_18: [(&str, usize); 9] = [
    ("stage1", 268),
    ("stage2", 365),
    ("stage3", 342),
    ("stage4", 212),
    ("stage5", 1_790),
    ("stage6a", 229),
    ("stage6b", 974),
    ("stage7", 795),
    ("stage8", 278),
];

fn setup_total_vars(memory_layout: &MemoryLayout, max_padded_trace_length: usize) -> usize {
    let advice_vars = |bytes: u64| -> usize {
        ((bytes / 8) as usize).next_power_of_two().max(1).ilog2() as usize
    };
    let max_log_t = max_padded_trace_length.ilog2() as usize;
    let max_log_k_chunk = if max_log_t >= ONEHOT_CHUNK_THRESHOLD_LOG_T {
        8
    } else {
        4
    };
    (max_log_k_chunk + max_log_t)
        .max(advice_vars(memory_layout.max_trusted_advice_size))
        .max(advice_vars(memory_layout.max_untrusted_advice_size))
}

/// The `dory_byte_diff` fixture recipe: legacy guest build and preprocessing,
/// modular trace, derived config, padded witness, Dory setup, one proof.
fn generate(log_t: usize) -> (VerifierPreprocessing, JoltDevice, Proof) {
    let trace_length = 1usize << log_t;
    let units = FIBONACCI_UNITS_2_18 * (trace_length / (1 << 18)) as u32;
    let mut program = Program::new("fibonacci-guest");
    let inputs = postcard::to_stdvec(&units).expect("serialize inputs");
    let (bytecode, init_memory_state, _, entry_address) = program.decode();
    let trace_output = program
        .trace_with_backend(&mut TracerBackend::new(), &inputs, &[], &[])
        .expect("trace fibonacci");
    let elf_contents = program.get_elf_contents().expect("elf contents");
    let legacy_program =
        LegacyProgramPreprocessing::preprocess(bytecode, init_memory_state, entry_address)
            .expect("legacy preprocess");
    let memory_layout = trace_output.device.memory_layout.clone();
    let shared = JoltSharedPreprocessing::new(legacy_program, memory_layout.clone(), trace_length);
    let legacy_preprocessing = LegacyPreprocessing::new(shared);
    let verifier_preprocessing = verifier_preprocessing_from_prover(&legacy_preprocessing);
    let program_preprocessing = verifier_preprocessing
        .program
        .as_full_arc()
        .expect("full program preprocessing");
    let jolt_program = Arc::new(JoltProgram::from_elf_bytes(elf_contents));
    let config = ProverConfig::derive::<Fr>(
        trace_output.trace.rows(),
        &memory_layout,
        verifier_preprocessing.program.min_bytecode_address(),
        verifier_preprocessing.program.program_image_len_words(),
        trace_length,
    )
    .expect("derive config");
    assert_eq!(config.trace_length, trace_length);
    let public_io = trace_output.device.clone();
    let mut rows = trace_output.trace.rows().to_vec();
    rows.resize(config.trace_length, TraceRow::default());
    let padded = TraceOutput::new(
        OwnedTrace::new(rows),
        trace_output.device,
        trace_output.final_memory,
        trace_output.advice_tape,
    );
    let witness = TraceBackend::new(
        JoltVmWitnessConfig::new(
            config.trace_length.ilog2() as usize,
            config.ram_K,
            config.one_hot_config,
        ),
        JoltVmWitnessInputs::new(&jolt_program, &program_preprocessing, padded),
    );
    let preprocessing = JoltProverPreprocessing::<Pcs, Vc> {
        verifier: verifier_preprocessing,
        pcs_setup: Pcs::setup_prover(setup_total_vars(&memory_layout, trace_length)),
        committed_program: None,
    };
    let start = Instant::now();
    let proof = jolt_prover::dory::prove::<Fr, Pcs, Vc, Blake3Transcript, _>(
        &JoltBackend::<Fr, Pcs>::optimized(),
        &preprocessing,
        &config,
        None,
        &witness,
        &public_io,
    )
    .expect("prove fibonacci");
    println!("prove: {:.2} s", start.elapsed().as_secs_f64());
    (preprocessing.verifier, public_io, proof)
}

fn fixture(log_t: usize) -> (VerifierPreprocessing, JoltDevice, Proof) {
    let path = PathBuf::from(format!("{CACHE_DIR}/fibonacci_2_{log_t}_blake3.bin"));
    if let Ok(bytes) = std::fs::read(&path) {
        let (fixture, _): ((VerifierPreprocessing, JoltDevice, Proof), usize) =
            bincode::serde::decode_from_slice(&bytes, bincode::config::standard())
                .expect("decode cached fixture");
        println!("fixture: loaded {} ({} B)", path.display(), bytes.len());
        return fixture;
    }
    let fixture = generate(log_t);
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).expect("fixture cache dir");
    }
    let bytes = bincode::serde::encode_to_vec(&fixture, bincode::config::standard())
        .expect("encode fixture");
    std::fs::write(&path, &bytes).expect("write fixture cache");
    println!(
        "fixture: generated and cached {} ({} B)",
        path.display(),
        bytes.len()
    );
    fixture
}

struct Built {
    relation: Relation,
    witness: Witness,
    build_secs: f64,
    witness_secs: f64,
}

fn build(preprocessing: &VerifierPreprocessing, public_io: &JoltDevice, proof: &Proof) -> Built {
    let profile = WrapperProfile::new(preprocessing, proof).expect("supported proof shape");
    let start = Instant::now();
    let relation = build_relation(&profile).expect("build relation");
    let build_secs = start.elapsed().as_secs_f64();
    let start = Instant::now();
    let witness =
        generate_witness(&profile, preprocessing, public_io, proof).expect("generate witness");
    let witness_secs = start.elapsed().as_secs_f64();
    Built {
        relation,
        witness,
        build_secs,
        witness_secs,
    }
}

fn first_failure(relation: &Relation, values: &[Fr]) -> Option<String> {
    relation
        .matrices
        .check_witness(values)
        .err()
        .map(|row| format!("{} (row {row})", relation.row_label(row).unwrap_or("?")))
}

/// Byte encoding of `LabelWithCount(b"sumcheck_poly", _)`: the label padded
/// to 24 bytes, any count.
fn is_round_label(bytes: &[u8]) -> bool {
    bytes.len() == 32
        && bytes.starts_with(b"sumcheck_poly")
        && bytes[13..24].iter().all(|b| *b == 0)
}

fn relation_on_fixture(log_t: usize) -> (Built, BTreeMap<String, usize>) {
    let (preprocessing, public_io, proof) = fixture(log_t);
    let built = build(&preprocessing, &public_io, &proof);
    let Built {
        relation,
        witness,
        build_secs,
        witness_secs,
    } = &built;
    println!("build_relation: {build_secs:.3} s; generate_witness (incl. native verify): {witness_secs:.3} s");
    assert_eq!(first_failure(relation, &witness.values), None);

    let matrices = &relation.matrices;
    println!(
        "constraints {}; variables {}; public {}",
        matrices.num_constraints, matrices.num_vars, relation.public.num_public
    );
    let mut per_stage: BTreeMap<String, usize> = BTreeMap::new();
    for span in &relation.rows {
        println!("{:<28} {:>7}", span.label, span.end - span.start);
        let stage = span.label.split('/').next().unwrap_or("").to_string();
        *per_stage.entry(stage).or_default() += span.end - span.start;
    }
    println!("per stage: {per_stage:?}");
    (built, per_stage)
}

#[test]
fn fibonacci_2_18_relation() {
    let (built, per_stage) = relation_on_fixture(18);
    let (preprocessing, public_io, proof) = fixture(18);
    let prepare_start = Instant::now();
    let preparation =
        WrapPreparation::new(&preprocessing, &public_io, &proof, WrapConfig::default())
            .expect("prepare wrapper inputs");
    println!(
        "wrap preparation: {:.1} ms; T1 rows {} / 2^{}; R rows {}; public {}+{}",
        prepare_start.elapsed().as_secs_f64() * 1e3,
        preparation.hash_table.rows,
        preparation.hash_table.log_rows,
        preparation.relation.matrices.num_constraints,
        preparation.public_known.len(),
        preparation.public_challenges.len(),
    );
    assert_eq!(preparation.hash_table.log_rows, 18);
    assert_eq!(preparation.public_known.len(), 7);
    assert_eq!(preparation.public_challenges.len(), 38);
    assert_eq!(preparation.shared_witness.inner_member().rounds, 13);
    let Built {
        relation, witness, ..
    } = &built;
    let private_start = 1 + relation.public.num_public;
    let private_witness = witness
        .values
        .get(private_start..)
        .expect("private witness range");
    let shared_witness =
        SharedWitnessColumn::new(private_witness, 1 << 18).expect("embed Spartan witness");
    assert_eq!(shared_witness.inner_member().rounds, 13);
    assert_eq!(shared_witness.into_column().len(), 1 << 18);
    assert_eq!(relation.matrices.num_constraints, EXPECTED_CONSTRAINTS_2_18);
    for (stage, rows) in EXPECTED_PER_STAGE_2_18 {
        assert_eq!(per_stage[stage], rows, "{stage}");
    }
    let mut fr = 0;
    let mut squeezes = [0usize; 2];
    let mut opaque = 0;
    let mut constant_bytes = 0;
    for entry in &relation.link.schedule {
        match entry {
            ScheduleEntry::Bytes(bytes) => constant_bytes += bytes.len(),
            ScheduleEntry::Fr(_) => fr += 1,
            ScheduleEntry::Opaque { len } => opaque += len,
            ScheduleEntry::Squeeze { kind, .. } => {
                squeezes[matches!(kind, SqueezeKind::Scalar) as usize] += 1;
            }
        }
    }
    println!(
        "schedule: {} entries; {fr} field elements; {} challenge + {} scalar squeezes; {opaque} opaque bytes; {constant_bytes} constant bytes",
        relation.link.schedule.len(),
        squeezes[0],
        squeezes[1]
    );
    println!(
        "dory: num_vars {} sigma {} scalars {}",
        relation.link.dory.num_vars,
        relation.link.dory.sigma,
        relation.link.dory.scalars.len()
    );

    // The outsourced inputs recomputed from the public outputs alone.
    let read = |variable: &Variable| witness.values[variable.index()];
    let outputs = &relation.public.outputs;
    let ram_address: Vec<Fr> = outputs.ram_address.iter().map(read).collect();
    let bytecode_address: Vec<Fr> = outputs.bytecode_address.iter().map(read).collect();
    let register_address: Vec<Fr> = outputs.register_address.iter().map(read).collect();
    let gammas: Vec<Fr> = outputs.bytecode_gammas.iter().map(read).collect();
    let recorded_challenges = ram_address
        .iter()
        .chain(&bytecode_address)
        .chain(&register_address)
        .copied()
        .map(|value| PublicChallenge {
            value,
            decoder: ChallengeDecoder::Challenge125,
        })
        .chain(gammas.iter().copied().map(|value| PublicChallenge {
            value,
            decoder: ChallengeDecoder::Scalar128,
        }))
        .collect::<Vec<_>>();
    for challenge in &recorded_challenges {
        let packed = challenge
            .decoder
            .pack(challenge.value)
            .expect("pack recorded challenge");
        if challenge.decoder == ChallengeDecoder::Challenge125 {
            assert_eq!(packed[15] & 0xe0, 0);
        }
        assert_eq!(
            challenge.decoder.decode(packed).expect("decode challenge"),
            challenge.value
        );
    }
    let first = recorded_challenges.first().expect("recorded challenge");
    let mut tampered = first.decoder.pack(first.value).expect("pack challenge");
    tampered[0] ^= 1;
    assert_ne!(
        first.decoder.decode(tampered).expect("decode tamper"),
        first.value
    );
    let recomputed = outsourced_inputs(
        &preprocessing,
        &public_io,
        &ram_address,
        StageValueInputs {
            bytecode_address: &bytecode_address,
            register_address: &register_address,
            stage_gammas: gammas[1..].try_into().unwrap(),
        },
    )
    .expect("outsourced inputs");
    assert_eq!(recomputed, witness.outsourced);
    assert_eq!(
        witness.values[relation.public.val_io.index()],
        recomputed.val_io
    );

    // Tamper: a stage-1 round coefficient.
    let mut tampered = witness.values.clone();
    let round_var = relation
        .link
        .schedule
        .windows(2)
        .filter_map(|pair| match pair {
            [ScheduleEntry::Bytes(bytes), ScheduleEntry::Fr(var)] if is_round_label(bytes) => {
                Some(*var)
            }
            _ => None,
        })
        .nth(2)
        .expect("a round coefficient");
    tampered[round_var.index()] += Fr::one();
    let failure = first_failure(relation, &tampered).expect("tampered round rejected");
    println!("tampered round coefficient fails at {failure}");
    assert!(failure.starts_with("stage1/"), "{failure}");

    // Tamper: the outsourced `ValIo` public input.
    let mut tampered = witness.values.clone();
    tampered[relation.public.val_io.index()] += Fr::one();
    let failure = first_failure(relation, &tampered).expect("tampered public input rejected");
    println!("tampered ValIo fails at {failure}");
    assert!(failure.starts_with("stage2/"), "{failure}");

    // Tamper: a Dory challenge wire (the pairing scalars pin the inverses).
    let mut tampered = witness.values.clone();
    let (_, gamma_var) = relation
        .link
        .dory
        .scalars
        .iter()
        .find(|(scalar, _)| matches!(scalar, jolt_wrapper::relation::DoryScalar::Gamma))
        .expect("dory gamma");
    tampered[gamma_var.index()] += Fr::one();
    let failure = first_failure(relation, &tampered).expect("tampered dory challenge rejected");
    println!("tampered Dory gamma fails at {failure}");
    assert!(failure.starts_with("stage8/dory"), "{failure}");
}

/// The 2^20 proof takes minutes and several GiB to generate on first run; it
/// is cached afterwards.
///
/// `cargo nextest run -p jolt-wrapper --features prover-fixtures --cargo-quiet --test relation_fixture --run-ignored ignored-only --no-capture`
#[test]
#[ignore = "generates a 2^20 proof on first run"]
fn fibonacci_2_20_relation() {
    let (built, per_stage) = relation_on_fixture(20);
    assert_eq!(
        built.relation.matrices.num_constraints,
        EXPECTED_CONSTRAINTS_2_20
    );
    for (stage, rows) in EXPECTED_PER_STAGE_2_20 {
        assert_eq!(per_stage[stage], rows, "{stage}");
    }
}
