[package]
name = "jolt-inlines-blake3"
version = "0.1.0"
edition = "2021"
description = "BLAKE3 inline implementations for Jolt VM"

[features]
default = ["dep:tracer"]
host = ["dep:ctor", "dep:tracer", "dep:jolt-inlines-common"]

[dependencies]
ctor = { version = "0.2", optional = true }
tracer = { path = "../../tracer", optional = true }
jolt-inlines-common = { path = "../common", optional = true }

[dev-dependencies]
hex-literal = "0.4.1"
tracer = { path = "../../tracer", features = ["test-utils"] }
