#!/bin/bash

# Apply patch to riscv_config
RISCV_CONFIG_PARENT=$(python3 -c "import riscv_config; import os; print(os.path.dirname(riscv_config.__file__))") && \
echo "Applying patch to directory: $RISCV_CONFIG_PARENT" && \
patch -d "$RISCV_CONFIG_PARENT" -N -p2 --fuzz=3 < patches/fix-isa-regex.patch

# Apply patch to riscv-arch-test
patch -d third-party/riscv-arch-test/ -N -p1 --fuzz=3 < patches/fix-misalign.patch
