#!/bin/bash

git submodule update --init --recursive

apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3 python3-pip python3-dev build-essential device-tree-compiler gcc-riscv64-unknown-elf binutils-riscv64-unknown-elf

mkdir -p ~/.config/pip && printf "[global]\nbreak-system-packages = true\n" > ~/.config/pip/pip.conf
python3 -m pip install --force-reinstall --upgrade pip

mkdir -p /opt/riscv/
curl -L "https://github.com/a16z/jolt/releases/download/spike-v1.1.1/spike-1.1.1-$(uname -s)-$(uname -m).tar.gz" -o /tmp/spike.tar.gz && tar -xzf /tmp/spike.tar.gz -C /opt/riscv/

pushd third-party/riscv-arch-test/riscv-ctg && pip3 install -e . && popd
pushd third-party/riscv-arch-test/riscv-isac && pip3 install -e . && popd
pip3 install git+https://github.com/riscv/riscof.git@dev

riscof --version
