#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="${repo_root}/.bolt-dev-env"

usage() {
  cat <<'USAGE'
Usage: scripts/setup-bolt-dev.sh

Installs/configures the local dependencies needed by Bolt MLIR/codegen and
Jolt-on-Bolt perf oracle checks on macOS:

  - Homebrew llvm
  - rustup components: rust-src, rustfmt, clippy
  - cargo-nextest
  - .bolt-dev-env with MLIR_SYS_220_PREFIX, PATH, SDKROOT, and bindgen flags

After it finishes, run:

  source .bolt-dev-env
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ "$(uname -s)" != "Darwin" ]]; then
  cat >&2 <<'EOF'
scripts/setup-bolt-dev.sh currently supports macOS/Homebrew.

Bolt's MLIR path needs LLVM/MLIR 22 visible through llvm-config. On non-macOS
hosts, install an LLVM 22 toolchain and export:

  MLIR_SYS_220_PREFIX=<llvm-prefix>
  PATH=<llvm-prefix>/bin:$PATH

EOF
  exit 1
fi

if ! command -v brew >/dev/null 2>&1; then
  cat >&2 <<'EOF'
Homebrew is required to install the LLVM toolchain for this helper.
Install Homebrew first: https://brew.sh
EOF
  exit 1
fi

if ! command -v xcrun >/dev/null 2>&1; then
  cat >&2 <<'EOF'
xcrun is missing. Install the Xcode command line tools first:

  xcode-select --install
EOF
  exit 1
fi

if ! brew list llvm >/dev/null 2>&1; then
  brew install llvm
fi

if command -v rustup >/dev/null 2>&1; then
  rustup component add rust-src rustfmt clippy
else
  cat >&2 <<'EOF'
rustup is not installed. Install Rust from https://rustup.rs, then rerun this
script so it can add rust-src, rustfmt, and clippy.
EOF
  exit 1
fi

if ! cargo nextest --version >/dev/null 2>&1; then
  cargo install cargo-nextest --locked
fi

llvm_prefix="$(brew --prefix llvm)"
sdkroot="$(xcrun --show-sdk-path)"

cat >"${env_file}" <<EOF
# Generated by scripts/setup-bolt-dev.sh. Source this before Bolt MLIR checks.
export MLIR_SYS_220_PREFIX="${llvm_prefix}"
export PATH="${llvm_prefix}/bin:\${PATH}"
export SDKROOT="${sdkroot}"
export BINDGEN_EXTRA_CLANG_ARGS="-isysroot${sdkroot}"
EOF

"${llvm_prefix}/bin/llvm-config" --version >/dev/null

cat <<EOF
Wrote ${env_file}

Run:
  source .bolt-dev-env

Then Bolt/equivalence checks can find llvm-config and MLIR_SYS_220_PREFIX.
EOF
