//! Transpile Jolt verifier stages 1-6 to a Gnark circuit for Groth16 proving.
//!
//! # Overview
//!
//! This binary performs symbolic execution of the Jolt verifier to generate a Gnark circuit.
//! Instead of computing with actual field elements, we use `MleAst`, a symbolic type that
//! records all arithmetic operations as an AST (Abstract Syntax Tree). This AST is then
//! converted to Gnark/Go code.
//!
//! # Scope: Stages 1-6 Only (Sumcheck Verification)
//!
//! This transpiler covers stages 1-6, which verify all sumcheck proofs. The PCS (Polynomial
//! Commitment Scheme) verification in stage 7+ is NOT transpiled because:
//!
//! - **Dory PCS uses pairings**: Emulating BN254 pairings inside a BN254 circuit would add
//!   hundreds of millions of constraints, making the circuit infeasible.
//! - **Native implementation needed**: PCS verification must be implemented directly in Gnark
//!   using native curve operations (see `quangvdao/` fork for Hyrax-based approach).
//!
//! The transpiled stages 1-6 circuit produces ~2M constraints and verifies the core sumcheck
//! logic. A complete recursive verifier would combine this with a native PCS verifier.
//!
//! # Pipeline
//!
//! 1. Load proof, io_device, and preprocessing from files (generated by jolt-sdk)
//! 2. Convert proof values to symbolic variables (`MleAst`) with `symbolize_proof`
//! 3. Run the verifier with symbolic types: this records all operations to the AST
//! 4. Collect equality assertions (the verifier's `assert_eq!` calls become circuit constraints)
//! 5. Generate Gnark circuit code from the AST
//! 6. Extract witness values from the real proof for Groth16 proving
//!
//! # Output
//!
//! - `stages_circuit.go`: Gnark circuit (~2M constraints for stages 1-6)
//! - `stages_witness.json`: Witness values for the prover
//! - `stages_bundle.json`: Serialized AST bundle for debugging

use ark_serialize::CanonicalDeserialize;
use clap::Parser;
use std::collections::HashMap;
use std::path::PathBuf;

use gnark_transpiler::{
    symbolize_proof, extract_witness_values, generate_circuit_from_bundle,
    AstCommitmentScheme, MleOpeningAccumulator, PoseidonAstTranscript, sanitize_go_name,
};
use jolt_core::poly::commitment::dory::DoryCommitmentScheme;
use jolt_core::transcripts::Transcript;
use jolt_core::zkvm::transpilable_verifier::TranspilableVerifier;
use jolt_core::zkvm::verifier::JoltVerifierPreprocessing;
use jolt_core::zkvm::RV64IMACProof;
use common::jolt_device::JoltDevice;
use zklean_extractor::mle_ast::{enable_constraint_mode, take_constraints as take_assertions, AstBundle, InputKind, MleAst};

// Output file names
const CIRCUIT_FILENAME: &str = "stages_circuit.go";
const WITNESS_FILENAME: &str = "stages_witness.json";
const BUNDLE_FILENAME: &str = "stages_bundle.json";

/// Transpile Jolt proofs to gnark circuits for Groth16 proving.
///
/// Takes a Jolt proof, io_device, and preprocessing files as input,
/// and generates gnark circuit code and witness data.
#[derive(Parser)]
#[command(name = "gnark-transpiler")]
#[command(version, about)]
struct Args {
    /// Path to the proof file (serialized JoltProof)
    #[arg(long, default_value = "/tmp/fib_proof.bin")]
    proof: PathBuf,

    /// Path to the io_device file (inputs/outputs)
    #[arg(long, default_value = "/tmp/fib_io_device.bin")]
    io_device: PathBuf,

    /// Path to the preprocessing file
    #[arg(long, default_value = "/tmp/jolt_verifier_preprocessing.dat")]
    preprocessing: PathBuf,

    /// Output directory for generated Go files
    #[arg(long, short = 'o', default_value = "go")]
    output_dir: PathBuf,
}

fn main() {
    let args = Args::parse();

    println!("=== Transpiling Jolt Verifier Stages 1-6 to Gnark ===\n");

    // =========================================================================
    // Step 1: Load input files
    // =========================================================================
    // These files are generated by running a Jolt program with --save flag:
    //   cargo run -p fibonacci --features transcript-poseidon -- --save 50
    //
    // - proof: The JoltProof containing commitments, sumcheck polynomials, etc.
    // - io_device: Program inputs/outputs (needed for transcript initialization)
    // - preprocessing: Verifier setup data (bytecode commitments, memory layout)

    println!("Loading proof from: {:?}", args.proof);
    let proof_bytes = std::fs::read(&args.proof)
        .unwrap_or_else(|e| panic!("Failed to read proof file {:?}: {}", args.proof, e));
    let real_proof: RV64IMACProof =
        CanonicalDeserialize::deserialize_compressed(&proof_bytes[..])
            .expect("Failed to deserialize proof");
    println!("  trace_length: {}", real_proof.trace_length);
    println!("  commitments: {}", real_proof.commitments.len());

    println!("\nLoading io_device from: {:?}", args.io_device);
    let io_device_bytes = std::fs::read(&args.io_device)
        .unwrap_or_else(|e| panic!("Failed to read io_device file {:?}: {}", args.io_device, e));
    let io_device: JoltDevice = CanonicalDeserialize::deserialize_compressed(&io_device_bytes[..])
        .expect("Failed to deserialize io_device");
    println!("  inputs: {} bytes", io_device.inputs.len());
    println!("  outputs: {} bytes", io_device.outputs.len());

    // Preprocessing uses DoryCommitmentScheme, the default PCS in jolt-sdk.
    // We only need the `shared` field (memory layout, bytecode info) for transpilation;
    // the commitment scheme generators are replaced with stubs for symbolic execution.
    println!("\nLoading preprocessing from: {:?}", args.preprocessing);
    let preprocessing_bytes = std::fs::read(&args.preprocessing)
        .unwrap_or_else(|e| panic!("Failed to read preprocessing file {:?}: {}", args.preprocessing, e));
    let real_preprocessing: JoltVerifierPreprocessing<ark_bn254::Fr, DoryCommitmentScheme> =
        CanonicalDeserialize::deserialize_compressed(&preprocessing_bytes[..])
            .expect("Failed to deserialize preprocessing");
    println!("  memory_layout: {:?}", real_preprocessing.shared.memory_layout);

    // Convert to symbolic preprocessing: replace Dory generators with AstVerifierSetup stub.
    // The `shared` field (memory layout, bytecode info) is reused as-is.
    // AstCommitmentScheme satisfies the CommitmentScheme trait but performs no cryptographic
    // operations. PCS verification is skipped in stages 1-6.
    let symbolic_preprocessing: JoltVerifierPreprocessing<MleAst, AstCommitmentScheme> =
        JoltVerifierPreprocessing {
            generators: gnark_transpiler::ast_commitment_scheme::AstVerifierSetup,
            shared: real_preprocessing.shared.clone(),
        };

    // =========================================================================
    // Step 2: Convert proof to symbolic representation
    // =========================================================================
    // symbolize_proof() converts each proof field (commitments, sumcheck polynomials,
    // opening proofs) into MleAst symbolic variables. Each variable gets a unique ID
    // and descriptive name (e.g., "Stage1_Sumcheck_R0_0" for round 0, coefficient 0).
    //
    // Returns:
    // - symbolic_proof: JoltProof<MleAst> with symbolic variables instead of Fr values
    // - accumulator: MleOpeningAccumulator to collect polynomial opening claims
    // - var_alloc: Tracks variable IDs and names for witness generation
    println!("\n=== Symbolizing Proof ===");
    let (symbolic_proof, accumulator, var_alloc) = symbolize_proof(&real_proof);
    println!("  Total symbolic variables: {}", var_alloc.next_idx());

    // Create Poseidon transcript for Fiat-Shamir challenges.
    // IMPORTANT: The proof must have been generated with --features transcript-poseidon,
    // otherwise challenge values will mismatch and verification will fail.
    let transcript: PoseidonAstTranscript = Transcript::new(b"Jolt");

    // =========================================================================
    // Step 3: Set up symbolic verifier
    // =========================================================================
    // TranspilableVerifier is the same as the normal Jolt verifier, but parameterized
    // with symbolic types (MleAst, AstCommitmentScheme, etc.) instead of concrete ones.
    // When verify() is called (Step 4), it executes the verification logic but records
    // all arithmetic operations to the AST instead of computing actual results.
    println!("\n=== Creating TranspilableVerifier ===");
    let verifier = TranspilableVerifier::<
        MleAst,
        AstCommitmentScheme,
        PoseidonAstTranscript,
        MleOpeningAccumulator,
    >::new_with_accumulator(
        &symbolic_preprocessing,
        symbolic_proof,
        io_device,
        None, // trusted_advice_commitment (not used in stages 1-6)
        transcript,
        accumulator,
    );

    // =========================================================================
    // Step 4: Run symbolic verification
    // =========================================================================
    // Enable constraint mode so that equality comparisons (==) on MleAst values
    // register as constraints instead of returning bool. This captures the verifier's
    // assert_eq! calls as circuit constraints.
    enable_constraint_mode();

    // Execute verification stages 1-6. This performs symbolic execution:
    // - All field arithmetic (add, mul, sub, inv) builds up the AST
    // - Poseidon hashes for Fiat-Shamir challenges are computed symbolically
    // - Equality assertions are recorded as constraints
    //
    // Stages 1-6 cover all sumcheck verifications. Stage 7+ (PCS verification)
    // is not transpiled, it requires native curve operations in Gnark.
    println!("\n=== Running Symbolic Verification (Stages 1-6) ===");
    match verifier.verify() {
        Ok(()) => println!("  Verification completed successfully"),
        Err(e) => {
            println!("  Verification error: {e:?}");
            return;
        }
    }

    // Collect the assertions that were registered during verification.
    // Each assertion is an equality check: (lhs == rhs) becomes (lhs - rhs == 0).
    // These become api.AssertIsEqual(lhs, rhs) calls in the Gnark circuit.
    let assertions = take_assertions();
    println!("\n=== Accumulated Assertions ===");
    println!("  Total assertions: {}", assertions.len());

    // =========================================================================
    // Step 5: Build AstBundle for code generation
    // =========================================================================
    // AstBundle is the intermediate representation that bridges symbolic execution
    // and code generation. It contains:
    // - inputs: All symbolic variables (proof data that becomes circuit witness)
    // - constraints: Equality assertions that the circuit must enforce
    // - arena snapshot: The AST nodes representing all computed expressions
    println!("\n=== Building AstBundle ===");
    let mut bundle = AstBundle::new();
    bundle.snapshot_arena();

    // Register all symbolic variables as circuit inputs (witness values).
    // These will become struct fields in the generated Gnark circuit.
    for (idx, name) in var_alloc.descriptions() {
        bundle.add_input(*idx, name.clone(), InputKind::ProofData);
    }
    println!("  Inputs: {}", bundle.inputs.len());

    // Register all equality assertions as circuit constraints.
    // Each assertion (lhs == rhs) becomes api.AssertIsEqual(lhs, rhs) in Gnark.
    for (i, assertion) in assertions.iter().enumerate() {
        bundle.add_constraint_eq_zero(format!("assertion_{i}"), assertion.root());
    }
    println!("  Constraints: {}", bundle.constraints.len());

    // Resolve output directory path.
    // CARGO_MANIFEST_DIR is set at compile time to the gnark-transpiler/ directory.
    // With default `--output-dir go`, files are written to gnark-transpiler/go/
    // regardless of the current working directory when running the binary.
    let output_dir = if args.output_dir.is_relative() {
        let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        manifest_dir.join(&args.output_dir)
    } else {
        args.output_dir.clone()
    };

    // Save bundle to JSON for debugging and analysis.
    // This allows inspecting the AST structure without re-running transpilation.
    let bundle_path = output_dir.join(BUNDLE_FILENAME);
    bundle
        .write_json(&bundle_path)
        .unwrap_or_else(|e| panic!("Failed to write bundle file {bundle_path:?}: {e}"));
    println!("  Bundle written to: {bundle_path:?}");

    // =========================================================================
    // Step 6: Generate Gnark circuit code
    // =========================================================================
    // generate_circuit_from_bundle() traverses the AST and emits Go code:
    // - Each AST node (Add, Mul, Sub, etc.) becomes an api.Add/Mul/Sub call
    // - Common subexpressions are cached to avoid redundant computation
    // - The circuit struct contains all witness fields
    // - The Define() method contains all constraint logic
    println!("\n=== Generating Gnark Circuit ===");
    let circuit_code = generate_circuit_from_bundle(&bundle, "JoltStagesCircuit");

    let circuit_path = output_dir.join(CIRCUIT_FILENAME);
    std::fs::write(&circuit_path, &circuit_code)
        .unwrap_or_else(|e| panic!("Failed to write circuit file {circuit_path:?}: {e}"));
    println!("  Circuit written to: {circuit_path:?}");
    println!("  Circuit size: {} bytes", circuit_code.len());

    // =========================================================================
    // Step 7: Extract witness values from real proof
    // =========================================================================
    // The witness maps variable names to their concrete values from the actual proof.
    // This is what the prover uses when generating a Groth16 proof.
    // Variable names are sanitized for Go (e.g., "Stage1_Sumcheck_R0_0" stays as-is,
    // but names with special characters get cleaned up).
    //
    // Note: Witness extraction is done in the same pass as circuit generation because
    // both require loading the proof file. Separating them would duplicate expensive
    // I/O and deserialization.
    println!("\n=== Generating Witness Data ===");
    let witness_values = extract_witness_values(&real_proof);

    let mut witness_map: HashMap<String, String> = HashMap::new();
    for (idx, name) in var_alloc.descriptions() {
        let sanitized = sanitize_go_name(name);
        if let Some(value) = witness_values.get(&(*idx as usize)) {
            witness_map.insert(sanitized, value.clone());
        }
    }

    let witness_json = serde_json::to_string_pretty(&witness_map).expect("Failed to serialize witness");
    let witness_path = output_dir.join(WITNESS_FILENAME);
    std::fs::write(&witness_path, &witness_json)
        .unwrap_or_else(|e| panic!("Failed to write witness file {witness_path:?}: {e}"));
    println!("  Witness written to: {witness_path:?}");
    println!("  Witness variables: {}", witness_map.len());

    println!("\n=== SUCCESS ===");
    println!("Stages 1-6 transpiled to Gnark. Run 'go test' in the output directory to verify.");
}
