[package]
name = "jolt-inlines-bigint"
version = "0.1.0"
edition = "2021"
description = "BigInteger inline implementations for Jolt VM"
license = "MIT"
homepage = "https://github.com/a16z/jolt/README.md"
repository = "https://github.com/a16z/jolt"

[features]
default = []
host = ["dep:ctor", "dep:tracer", "dep:common", "dep:tracing"]

[dependencies]
ctor = { workspace = true, optional = true }
tracer = { workspace = true, optional = true, features = ["std"] }
common = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
hex-literal.workspace = true
ark-ff.workspace = true
rand = { workspace = true, features = ["std", "std_rng"] }
tracer = { workspace = true, features = ["std", "test-utils"] }
