//! Coefficient schedules for the degree-4/8 cyclotomic extension multiply,
//! generic over the lane type.
//!
//! One fold-algebra source of truth per schedule: the same formulas serve
//! the scalar [`PseudoMersenne`](crate::PseudoMersenne) kernel-hook defaults
//! and (via caller-supplied add/sub/mul) the packed SIMD and unreduced
//! integer-lane kernels, which is why they live in the unconditional layer
//! rather than a backend module. Coefficients are in the ring-subfield
//! basis `[1, e1, ...]` with `e_j = zeta^(jm) + zeta^(-jm)`; the basis
//! relations (`e_i·e_j = e_{i+j} + e_{|i−j|}` with `e_0 = 2`, `e_d = 0`,
//! `e_{d+k} = −e_{d−k}`) are already folded into the formulas.
//!
//! Every schedule is purely an additive combination of products, so callers
//! that reduce per operation (field lanes) and callers that defer reduction
//! (integer lanes) are both correct, provided the accumulator has headroom.

use crate::Ring;
use std::ops::{Add, Mul, Sub};

/// Multiplies degree-4 coefficient arrays in the `[1, e1, e2, e3]` basis.
#[inline(always)]
pub(crate) fn ext4_mul_coeffs<A>(a: [A; 4], b: [A; 4]) -> [A; 4]
where
    A: Copy + Add<Output = A> + Sub<Output = A> + Mul<Output = A>,
{
    let [a0, a1, a2, a3] = a;
    let [b0, b1, b2, b3] = b;
    let tail = a1 * b1 + a2 * b2 + a3 * b3;
    [
        a0 * b0 + tail + tail,
        a0 * b1 + a1 * b0 + a1 * b2 + a2 * b1 + a2 * b3 + a3 * b2,
        a0 * b2 + a2 * b0 + a1 * b1 + a1 * b3 + a3 * b1 - a3 * b3,
        a0 * b3 + a3 * b0 + a1 * b2 + a2 * b1 - a2 * b3 - a3 * b2,
    ]
}

/// Squares one degree-4 coefficient array in the `[1, e1, e2, e3]` basis.
///
/// Decomposes `a` over the degree-2 subfield generated by `e2` (with
/// `e2^2 = 2`) as `x + y·e1`, squares with three subfield multiplies, and
/// maps back — fewer base multiplies than the generic 4×4 product.
#[inline(always)]
pub(crate) fn ext4_square_coeffs<A>(a: [A; 4]) -> [A; 4]
where
    A: Copy + Add<Output = A> + Sub<Output = A> + Mul<Output = A>,
{
    let [a0, a1, a2, a3] = a;
    let x0 = a0;
    let x1 = a2;
    let y0 = a1 - a3;
    let y1 = a3;

    let x0x1 = x0 * x1;
    let y0y1 = y0 * y1;
    let x1_square = x1 * x1;
    let y1_square = y1 * y1;
    let aa = (x0 * x0 + x1_square + x1_square, x0x1 + x0x1);
    let bb = (y0 * y0 + y1_square + y1_square, y0y1 + y0y1);

    let v0 = x0 * y0;
    let v1 = x1 * y1;
    let ab = (v0 + v1 + v1, (x0 + x1) * (y0 + y1) - v0 - v1);
    let constant = (bb.0 + bb.0 + bb.1 + bb.1, bb.0 + bb.1 + bb.1);
    let coeff_e1 = (ab.0 + ab.0, ab.1 + ab.1);

    [
        aa.0 + constant.0,
        coeff_e1.0 + coeff_e1.1,
        aa.1 + constant.1,
        coeff_e1.1,
    ]
}

/// Chebyshev `φ` fold-back for a degree-8 accumulator: maps the product
/// index `k` onto the `[1, e1, ..., e7]` basis (`k = 0 → 2·constant`,
/// `1 ≤ k ≤ 7 → +e_k`, `k = 8 → 0`, `9 ≤ k ≤ 15 → −e_{16−k}`).
#[inline(always)]
fn ext8_add_phi<V: Copy>(
    out: &mut [V; 8],
    idx: usize,
    value: V,
    add: &impl Fn(V, V) -> V,
    sub: &impl Fn(V, V) -> V,
) {
    match idx {
        0 => out[0] = add(out[0], add(value, value)),
        1..=7 => out[idx] = add(out[idx], value),
        8 => {}
        9..=15 => out[16 - idx] = sub(out[16 - idx], value),
        _ => unreachable!("ext8 Chebyshev index out of range"),
    }
}

/// Karatsuba schedule for the degree-8 multiply in the Chebyshev basis,
/// generic over a lane type `V` and its add/sub/mul.
#[inline(always)]
pub(crate) fn ext8_mul_schedule<V, A, S, M>(
    a: [V; 8],
    b: [V; 8],
    zero: V,
    add: A,
    sub: S,
    mul: M,
) -> [V; 8]
where
    V: Copy,
    A: Fn(V, V) -> V,
    S: Fn(V, V) -> V,
    M: Fn(V, V) -> V,
{
    let diag: [V; 8] = std::array::from_fn(|i| mul(a[i], b[i]));
    let mut out = [zero; 8];
    out[0] = diag[0];

    for k in 1..8 {
        let mixed = sub(sub(mul(add(a[0], a[k]), add(b[0], b[k])), diag[0]), diag[k]);
        out[k] = add(out[k], mixed);
    }

    for (i, &diag_i) in diag.iter().enumerate().skip(1) {
        out[0] = add(out[0], add(diag_i, diag_i));
        ext8_add_phi(&mut out, i + i, diag_i, &add, &sub);
    }

    for i in 1..8 {
        for j in (i + 1)..8 {
            let mixed = sub(sub(mul(add(a[i], a[j]), add(b[i], b[j])), diag[i]), diag[j]);
            ext8_add_phi(&mut out, i + j, mixed, &add, &sub);
            ext8_add_phi(&mut out, j - i, mixed, &add, &sub);
        }
    }

    out
}

/// [`ext8_mul_schedule`] instantiated at a ring's own arithmetic (the
/// [`PseudoMersenne::ext8_mul`](crate::PseudoMersenne::ext8_mul) default).
#[inline(always)]
pub(crate) fn ext8_mul_coeffs<R: Ring>(a: [R; 8], b: [R; 8]) -> [R; 8] {
    ext8_mul_schedule(a, b, R::zero(), |x, y| x + y, |x, y| x - y, |x, y| x * y)
}

/// [`ext8_square_schedule`] instantiated at a ring's own arithmetic (the
/// [`PseudoMersenne::ext8_square`](crate::PseudoMersenne::ext8_square) default).
#[inline(always)]
pub(crate) fn ext8_square_coeffs<R: Ring>(a: [R; 8]) -> [R; 8] {
    ext8_square_schedule(a, R::zero(), |x, y| x + y, |x, y| x - y, |x, y| x * y)
}

/// Squaring schedule for the degree-8 extension, generic over a lane type.
///
/// Uses direct cross products `a_i·a_j` doubled once, saving one add and
/// two subs per cross term versus the Karatsuba mul schedule.
#[inline(always)]
pub(crate) fn ext8_square_schedule<V, A, S, M>(a: [V; 8], zero: V, add: A, sub: S, mul: M) -> [V; 8]
where
    V: Copy,
    A: Fn(V, V) -> V,
    S: Fn(V, V) -> V,
    M: Fn(V, V) -> V,
{
    let sq: [V; 8] = std::array::from_fn(|i| mul(a[i], a[i]));
    let mut out = [zero; 8];
    out[0] = sq[0];

    for k in 1..8 {
        let cross = mul(a[0], a[k]);
        out[k] = add(out[k], add(cross, cross));
    }

    for (i, &sq_i) in sq.iter().enumerate().skip(1) {
        out[0] = add(out[0], add(sq_i, sq_i));
        ext8_add_phi(&mut out, i + i, sq_i, &add, &sub);
    }

    for i in 1..8 {
        for j in (i + 1)..8 {
            let cross = mul(a[i], a[j]);
            let doubled = add(cross, cross);
            ext8_add_phi(&mut out, i + j, doubled, &add, &sub);
            ext8_add_phi(&mut out, j - i, doubled, &add, &sub);
        }
    }

    out
}
