import fs from 'node:fs';
import assert from 'node:assert/strict';
import solc from 'solc';
import {keccak_256} from '@noble/hashes/sha3.js';

// Policy is generated only from the actual module runtimes; callers never supply code hashes.
export function compileModules({writePolicy=false}={}) {
 const names=['SpartanDecodeModule','SpartanPrefixModule','SpartanSparseModule','SpartanLeafModule'];
 const paths=fs.readdirSync('contracts').filter(p=>p.endsWith('.sol')&&!['SpartanSparseCoordinator.sol','SpartanLeafCoordinator.sol','SpartanVerifier.sol','SpartanModulePolicy.sol'].includes(p));
 const sources=Object.fromEntries(paths.map(p=>[p,{content:fs.readFileSync('contracts/'+p,'utf8')}]));
 const settings={viaIR:true,optimizer:{enabled:true,runs:200},evmVersion:'prague',outputSelection:{'*':{'*':['evm.deployedBytecode','evm.bytecode','evm.methodIdentifiers'],'':['ast']}}};
 const compile=sources=>{const c=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources,settings})));for(const e of c.errors??[])if(e.severity==='error')throw Error(e.formattedMessage);return c;};
 const first=compile(sources);
 const hash=bytes=>Buffer.from(keccak_256(Buffer.from(bytes,'hex'))).toString('hex');
 const hashes=names.map(name=>hash(first.contracts[name+'.sol'][name].evm.deployedBytecode.object));
 const policy='// SPDX-License-Identifier: MIT\npragma solidity 0.8.30;\n// Generated by test/compile-modules.mjs from reviewed deployed module bytecode.\nlibrary SpartanModulePolicy {\n'+['DECODE','PREFIX','SPARSE','LEAF'].map((name,j)=>'    bytes32 internal constant '+name+'=hex"'+hashes[j]+'";\n').join('')+'}\n';
 if(writePolicy)fs.writeFileSync('contracts/SpartanModulePolicy.sol',policy);
 else assert.equal(fs.readFileSync('contracts/SpartanModulePolicy.sol','utf8'),policy,'module policy update requires explicit reviewed regeneration');
 sources['SpartanModulePolicy.sol']={content:policy};
 for(const name of ['SpartanSparseCoordinator','SpartanLeafCoordinator','SpartanVerifier'])sources[name+'.sol']={content:fs.readFileSync('contracts/'+name+'.sol','utf8')};
 const complete=compile(sources);
 for(let j=0;j<names.length;j++)assert.equal(hash(complete.contracts[names[j]+'.sol'][names[j]].evm.deployedBytecode.object),hashes[j],'module policy must not change its own hashed runtime');
 for(const name of [...names,'SpartanSparseCoordinator','SpartanLeafCoordinator','SpartanVerifier'])assert(complete.contracts[name+'.sol'][name].evm.deployedBytecode.object.length/2<=24576,name+' EIP170 code size');
 return {complete,sources,settings,hashes,names};
}
if(process.argv[1]?.endsWith('/compile-modules.mjs')){
 const result=compileModules({writePolicy:process.argv.includes('--write-policy')});fs.mkdirSync('evidence/sparse',{recursive:true});fs.writeFileSync('evidence/sparse/compiled.json',JSON.stringify(result));
 console.log(JSON.stringify(Object.fromEntries([...result.names,'SpartanSparseCoordinator','SpartanLeafCoordinator','SpartanVerifier'].map(name=>[name,result.complete.contracts[name+'.sol'][name].evm.deployedBytecode.object.length/2])),null,2));
}
