[package]
name = "blake3-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", path = "../../../jolt-sdk", features = [] }
jolt-inlines-blake3 = { package = "jolt-inlines-blake3", path = "../../../jolt-inlines/blake3" }
