LEGACY_SCHEMA_VERSION = 1
TEMPLATE_SCHEMA_VERSION = 2
RUN_SCHEMA_VERSION = 2
EVENT_SCHEMA_VERSION = 2
GOAL_SCHEMA_VERSION = 2
TIER_RESULT_SCHEMA_VERSION = 1
TIER_RESULT_SCHEMA = "metal_autoresearch_tier_result_v1"

